SUB1

{
	type "convo"
	descr "PA"
	singleton

	multisub trg0001 {
		{ time 00 length 3000 text "Welcome to the Ramsey Center UNN Recruitment Facility." }
		{ time 3000 length 2200 text "Please watch your step when leaving the train." }
		{ time 5200 length 4700 text "The gravshafts at the end of the hall will take you to the street-level training and recruitment center." }
		{ time 10000 length 2200 text "Please proceed to the gravshafts." }
	}

	sub trg0002 { text "Step into the gravshafts to proceed to the street-level recruitment." }
}

{
	type "convo"
	descr "Trainer"

	multisub trg0004 {
		{ time 00 length 3800 text "Before you choose your career, you'll want to learn some basic abilities." }
		{ time 3800 length 2450 text "First, you should go into the Basic Training center." }
		{ time 6270 length 3700 text "When you're done with Basic Training, proceed to the Advanced Training area." }
	}

	multisub trg0014 {
		{ time 00 length 4400 text "If you've completed basic training, you're ready for the advanced lessons provided here." }
		{ time 4500 length 4700 text "Advanced training will familiarize you with the three key areas of military service--" }
		{ time 9160 length 4000 text "Weapons training, technical training, and psionics training." }
		{ time 13170 length 3500 text "Approach the cyberlink booth of your choice to train in that area." }
		{ time 16800 length 7000 text "When you've finished training in the three areas, proceed directly to the recruitment center to choose and start your military career." }
	}

	multisub trg0031 {
		{ time 00 length 2000 text "Here's where you make your choice, soldier." }
		{ time 2000 length 3000 text "Here's where you enlist in one of the three branches of the military." }
		{ time 5000 length 3700 text "Once you decide on your branch of service, there's no going back." }
		{ time 8700 length 6100 text "A shuttle will take you to a UNN orbital space station, where you'll receive a briefing regarding your yearly postings." }
		{ time 15000 length 1000 text "Good luck." }
	}

	// Basic training

	multisub trg0005 {
		{ time 600 length 4700 text "To pick up some basic skills you'll need to get by in the service, enter this cyberlink booth." }
		{ time 5500 length 3200 text "Inside you'll learn the basic skills you'll need to get started." }
	}

	multisub trg0006 {
		{ time 00 length 1000 text "Welcome, trainee." }
		{ time 1200 length 4900 text "While you're in our virtual training courses, we provide you with a simulated cyber-interface." }
		{ time 6370 length 4800 text "This training interface is identical to an actual military-grade cyber-interface." }
	}

	multisub trg0007 {
		{ time 00 length 1800 text "Now, let's try it out." }
		{ time 2100 length 1000 text "Move the mouse." }
		{ time 3700 length 1700 text "See how it changes where you look?" }
		{ time 5900 length 1600 text "That means you're in Shoot mode." }
		{ time 8200 length 1000 text "Hit the Tab key." }
		{ time 10300 length 4500 text "This puts you in Use mode, where you can use your mouse to interact with items in the world." }
		{ time 16160 length 7000 text "Open your primary MFD - or multi-function display - by clicking on the MFD button near the bottom of the screen." }
		{ time 24570 length 2800 text "This display shows your strengths in various areas." }
		{ time 27600 length 3700 text "When you're ready to continue, press the Tab key to go back to Shoot mode." }
		{ time 32200 length 2860 text "Try changing between modes until you get the hang of it." }
		{ time 35800 length 3500 text "Follow the red path along the ground to the next training station." }
	}

	multisub trg0008 {
		{ time 00 length 5560 text "To use items like buttons and computers, center them in your view and click the right mouse button." }
		{ time 5920 length 2380 text "All useable items will have brackets around them." }
		{ time 8910 length 2500 text "Highlight the button on the pillar and right-click." }
		{ time 11600 length 1500 text "This will activate the lift." }
		{ time 13800 length 700 text "Try it out." }
		{ time 16300 length 3800 text "If you can still see your inventory display, it means you're in Use mode." }
		{ time 20500 length 2000 text "Hit Tab to return to Shoot mode." }
	}

	multisub trg0009 {
		{ time 00 length 3800 text "To pick up items, center them on your screen and right-click." }
		{ time 3890 length 2930 text "This will automatically place that item into your inventory." }
		{ time 7170 length 2800 text "To view your inventory, press the Tab key." }
		{ time 10150 length 4510 text "You can move items around your inventory by left-clicking and dragging them around." }
		{ time 15000 length 5150 text "To drop an item, drag it from your inventory into the 3D view and release the mouse button." }
	}

	multisub trg0010 {
		{ time 00 length 1600 text "See the crate in front of you?" }
		{ time 1900 length 2900 text "To search it, center it on your screen and right-click." }
		{ time 5020 length 4120 text "If you are in Use mode, simply move the pointer to the crate and right-click." }
		{ time 9440 length 3260 text "To take an item from that container, simply left-click on it." }
		{ time 12870 length 2840 text "This will automatically place that item in your inventory." }
		{ time 15980 length 4170 text "To close the container window and return to Shoot mode, press the Tab key." }
	}

	multisub trg0011 {
		{ time 00 length 2500 text "Now it's time to learn about jumping and mantling." }
		{ time 2700 length 2500 text "To jump, simply press the space bar." }
		{ time 6050 length 3940 text "Some surfaces can be mantled onto by holding down the space bar." }
		{ time 10740 length 4410 text "Mantling lets you pull yourself up to ledges and other high places in front of you." }
		{ time 15690 length 1020 text "Give it a try." }
	}

	multisub trg0012 {
		{ time 00 length 3300 text "To climb a ladder, simply walk into it and look upward." }
		{ time 3600 length 2500 text "You'll automatically start climbing the ladder." }
	}

	multisub trg0032 {
		{ time 00 length 2300 text "The object before you is a med hypo." }
		{ time 2500 length 2700 text "Pick it up and then press Tab to go into Use mode." }
		{ time 5700 length 4300 text "Right-clicking on the med hypo will use it and restore some needed hit points." }
		{ time 10500 length 4000 text "Your hit points are displayed by a bar in the lower-left corner of your screen." }
		{ time 15000 length 3900 text "Many objects in your inventory can be used by right-clicking on them." }
	}

	multisub trg0033 {
		{ time 00 length 3600 text "One of the most important tools you have as a soldier is your PDA." }
		{ time 4000 length 4000 text "This device stores audio logs, emails, and other useful information." }
		{ time 8700 length 4000 text "Click on the disc icon near the bottom of your screen to bring up the PDA display." }
		{ time 13300 length 3000 text "Currently, the contents of your PDA are empty." }
		{ time 16700 length 2300 text "Now pick up the audio log in front of you." }
	}

	multisub trg0013 {
		{ time 600 length 900 text "You've done well." }
		{ time 1900 length 6400 text "Remember, if you're unclear on any aspect of what you just learned, you can repeat the training as often as you wish." }
	}

	// Weapons training

	multisub trg0015 {
		{ time 650 length 6200 text "Alright wannabe, if you want to learn the weapon skills it takes to even think about joining the Marines, come on in." }
		{ time 7200 length 1500 text "We're looking for a few good men." }
	}

	multisub trg0016 {
		{ time 00 length 1400 text "Good to have you on board." }
		{ time 1700 length 8900 text "You'll notice when you're in the cyberlink booth, the UNN has kindly provided you with a virtual cyber-interface and all the simulated skill levels you'll need for the training tasks." }
		{ time 10800 length 3400 text "But don't get too cocky. They'll disappear once you leave the booth." }
	}

	multisub trg0017 {
		{ time 00 length 2100 text "Now we'll teach you how to handle a firearm." }
		{ time 2500 length 4900 text "Pick up the pistol and the clip from the table. You can equip the weapon in one of two ways." }
		{ time 7700 length 5800 text "Bring up your inventory, and drag the pistol to your weapons equip slot near the right-hand side of your inventory." }
		{ time 13800 length 4500 text "If that's too slow for you, you can use the hotkeys on the keyboard. Press 2." }
		{ time 18900 length 3700 text "If the pistol was in your inventory, it will equip for you automatically." }
		{ time 23000 length 6300 text "To lock and load the ammo clip, hit the R key or hit the reload button on the lower-right corner of your screen." }
		{ time 29700 length 6100 text "Once you've loaded the firearm, take a shot at the dummy robot by pressing your left mouse button when in Shoot mode." }
		{ time 36500 length 3100 text "Notice how its health bar gets shorter as you chip away at it." }
	}

	multisub trg0018 {
		{ time 00 length 3500 text "Some items need to be charged with energy before they can be used." }
		{ time 3900 length 3800 text "Pick up the laser pistol. Now use the recharging station nearby." }
		{ time 8100 length 3500 text "The recharge station will juice up all of your energy-based items." }
		{ time 11800 length 2500 text "Weapons, batteries, you name it." }
	}

	multisub trg0019 {
		{ time 00 length 3600 text "Weapons are not fine wines. They do not get better with age." }
		{ time 3900 length 4700 text "The colored dot on the lower-right corner of the screen tells you what kind of shape your firearm is in." }
		{ time 8800 length 1900 text "Green is good. Red is bad." }
		{ time 11200 length 6600 text "To fight the effects of wear and tear, a soldier with maintenance skill can use a maintenance tool to improve the condition of his weapon." }
		{ time 18500 length 4300 text "Just pick up the tool, open your inventory, and drag the tool onto your pistol." }
		{ time 23100 length 3800 text "Remember that maintenance tools are only good for a single use." }
	}

	multisub trg0020 {
		{ time 500 length 2400 text "Good work, now you're ready for the Marines." }
		{ time 3500 length 2900 text "Take a look at the other training areas first before you enlist." }
		{ time 6800 length 1200 text "They might just come in handy." }
	}

	// Technical training

	multisub trg0021 {
		{ time 600 length 3800 text "Inside, we'll teach you the basics of some technical skills you'll need in the Navy." }
	}

	multisub trg0022 {
		{ time 100 length 500 text "Welcome." }
		{ time 1200 length 7300 text "You'll notice when you're in the cyberlink booth, we'll provide you with a temporary cyber-interface and the skills you need to accomplish the training tasks." }
		{ time 8800 length 2600 text "But they'll only last so long as you're in the booth." }
	}

	multisub trg0023 {
		{ time 00 length 2700 text "The object in front of you is a container of nanites." }
		{ time 2900 length 4900 text "Nanites are consumed whenever you perform technical tasks, such as hacking or repairing." }
		{ time 8200 length 8200 text "When you pick up the container of nanites, they do not go in your general inventory, but are instead displayed in Use mode on the bottom-left of your screen." }
		{ time 17000 length 3000 text "Walk over to the keypad by the door and try out hacking." }
	}

	multisub trg0034 {
		{ time 00 length 1800 text "Use the keypad by right-clicking on it." }
		{ time 2300 length 3300 text "To the right of the number pad, you'll see an orange tab labeled \"Hack\"." }
		{ time 6000 length 1100 text "Left-click on the tab." }
		{ time 7800 length 3600 text "Text will appear, indicating the difficulty of the hack and any bonuses that apply." }
		{ time 12400 length 1800 text "Click on the Start button to begin hacking." }
		{ time 14900 length 1400 text "You'll see a grid of nodes." }
		{ time 16500 length 2500 text "Clicking on a node will either turn it bright or dark." }
		{ time 20000 length 3900 text "To succesfully hack, you must connect three bright nodes in a straight line." }
		{ time 24500 length 2500 text "Beware of the ICE nodes with the red outlines." }
		{ time 27400 length 5300 text "If one of these turns dark, you fail the hack and you might break the item you are working on, or worse." }
		{ time 33500 length 5900 text "You can restart your hack attempt at any time by hitting the Reset button, though you'll have to pay the nanite cost again." }
	}

	multisub trg0024 {
		{ time 00 length 2900 text "You can use nanites to buy items from replicators." }
		{ time 3100 length 2100 text "To use a replicator, right-click on it." }
		{ time 5600 length 2200 text "Then left-click on the item you wish to purchase." }
		{ time 8300 length 2500 text "The item you purchased will drop into the slot below." }
		{ time 11500 length 2600 text "Make sure you pick up your purchases before you leave." }
	}

	multisub trg0025 {
		{ time 600 length 1900 text "You learned the basics of the technical skills." }
		{ time 3000 length 6000 text "There are several other technical skills you'll learn throughout the course of your career, such as repairing items and modifying weapons." }
		{ time 9500 length 3500 text "The cyber-interfaces for these tasks are similar to the hacking interface." }
		{ time 13500 length 3200 text "Before you enlist in the Navy, try out the other training courses." }
		{ time 17000 length 700 text "They'll be useful." }
	}

	// Psionics training

	multisub trg0026 {
		{ time 700 length 3000 text "Inside you will learn how to reach out with your mind." }
		{ time 4200 length 2100 text "Do not let fear block your path." }
	}

	multisub trg0027 {
		{ time 00 length 6600 text "We've provided you with a virtual interface and the temporary ability to project simulated psionic powers." }
		{ time 7000 length 3900 text "Once you leave this area, these powers will be lost to you." }
	}

	multisub trg0028 {
		{ time 00 length 4900 text "The red bar at the lower left of your screen tells you how many psi points you have." }
		{ time 5200 length 4300 text "Psi points symbolize the current ability to use your psi powers." }
		{ time 9800 length 2900 text "Psi hypos replenish your psi points." }
		{ time 13000 length 4000 text "Try using a psi hypo and watch your psi points increase." }
		{ time 17400 length 4000 text "When you've reached your maximum in psi points, move to the next station." }
	}

	multisub trg0029 {
		{ time 00 length 5500 text "This psi amp amplifies your psi powers and lets you project them into the real world." }
		{ time 5800 length 3700 text "To equip it, pick it up and then hit the tilde key." }
		{ time 10000 length 4300 text "Firing the psi amp activates your currently selected psi discipline." }
		{ time 14700 length 5800 text "You currently have access to two disciplines, Cryokinesis and Kinetic Redirection." }
		{ time 21200 length 5000 text "Go into Use mode and click on the arrows on the bottom-right of the screen." }
		{ time 26700 length 3300 text "This will cycle through your available psi disciplines." }
		{ time 30400 length 7000 text "Later, clicking on the arrows above the number to the left will allow you to select psi disciplines from higher tiers." }
		{ time 37900 length 7000 text "Use Cryokinesis to destroy the robot, and Kinetic Redirection to pull that nanite container towards you." }
		{ time 45500 length 8500 text "Be careful, holding down the mouse button can augment the power, but holding it down for too long will cause burnout, which will damage you." }
		{ time 54500 length 3800 text "If you run out of psi points, use another psi hypo." }
	}

	multisub trg0030 {
		{ time 600 length 3600 text "Mastery of the mind is a slow but rewarding process." }
		{ time 4600 length 2700 text "Return to this area if you need more guidance." }
		{ time 7800 length 5800 text "Before you enlist in the OSA, it would be useful to experiment in the other training courses." }
	}
}

{
	type "convo"
	descr "Trainer"

	multisub init_0 {
		{ time 00 length 2400 text "Welcome to space station Wake Island, Marine." }
		{ time 2500 length 2700 text "So you survived basic training at Camp Lejeune." }
		{ time 5400 length 3900 text "Better still, you managed to learn a thing or two about standard weapons." }
		{ time 9800 length 2000 text "But now it's time for the real deal." }
		{ time 12600 length 3800 text "Your tour of duty will consist of four postings over four years." }
		{ time 16900 length 3300 text "The Corps demands a lot of you grunts, but the Corps is generous." }
		{ time 20500 length 1900 text "You get to choose your own postings." }
		{ time 23100 length 4200 text "Head up to the shuttle bays in the center of Wake Island and you'll be briefed on what's ahead." }
		{ time 27900 length 4000 text "When you find the right posting, head into that bay to accept the assignment." }
		{ time 32300 length 1000 text "Good luck, Marine!" }
	}

	multisub init_1 {
		{ time 00 length 2800 text "Welcome aboard the space station Chesapeake Bay, sailor." }
		{ time 3200 length 3900 text "It looks like you've picked up some standard weapon skills at basic on Coronado Island." }
		{ time 7500 length 1600 text "Now it's time for your tour of duty." }
		{ time 9600 length 2900 text "Your tour will consist of four postings over four years." }
		{ time 12800 length 3200 text "In this man's navy you're given a choice of three different postings a year." }
		{ time 16400 length 3500 text "It's up to you to decide what kind of career you want to have, so choose wisely." }
		{ time 20400 length 2700 text "Just approach your shuttle bay to receive a briefing on a posting." }
		{ time 23600 length 4000 text "If you think that posting is right for you, head into that bay to accept the assignment." }
	}

	multisub init_2 {
		{ time 00 length 4000 text "The OSA welcomes you to orbital station Chun Lo." }
		{ time 4200 length 4000 text "Ready yourself to feel the limitations of your mind slipping away." }
		{ time 8700 length 3200 text "We will guide your path over the next four years." }
		{ time 12200 length 4600 text "The shuttle bays at the center of this station will ferry you to your next stage of growth." }
		{ time 17300 length 3500 text "When you've chosen, head into the appropriate shuttle bay." }
		{ time 21100 length 3200 text "Get ready to learn things you've never imagined." }
	}

	// Marine briefings

	multisub brief01 {
		{ time 600 length 4500 text "If you're partial to spending time with a lot of high explosives, this posting is for you." }
		{ time 5600 length 5800 text "There's a lot of heavy lifting, but ordnance also gets the first pick of booze and other goodies coming aboard the supply ship Gallo." }
		{ time 11850 length 1100 text "Lock and load!" }
	}

	multisub brief02 {
		{ time 850 length 4700 text "The Navy maintains a survival training school on the surface of Io, the third moon of Jupiter." }
		{ time 6100 length 3600 text "Pros: there's no better way to improve stamina and survival skills." }
		{ time 9950 length 3200 text "Cons: the 21.2% mortality rate." }
		{ time 13550 length 3700 text "Plus, you've gotta spend the year with a bunch of Navy skanks." }
	}

	multisub brief03 {
		{ time 900 length 7700 text "Not every boarding party has the luxury of gravity, so the Corps strongly recommends every one of its brethren get in some zero-g training." }
		{ time 9150 length 3200 text "A year aboard the training station Guadalcanal should suffice." }
	}

	multisub brief04 {
		{ time 700 length 6100 text "A tour of duty aboard the Antigua should let you pick up some one-on-one beam weapon training from Gunnery Sergeant Malloy." }
		{ time 7200 length 2700 text "But heads up, she's a world-class SOB." }
	}

	multisub brief05 {
		{ time 800 length 7400 text "The automated asteroid ore facility in JM-432 supply the UNN shipyards, so they're crucial to defense." }
		{ time 8500 length 3000 text "However, they're also prime candidates for hackers." }
		{ time 11500 length 7100 text "Somebody has gotten their claws into the primary data loop and they need a team to head in there and blast their way past the automated defense systems." }
	}

	multisub brief06 {
		{ time 800 length 5800 text "Dummy ammunition, live ammunition, moving targets, stationary targets, live targets..." }
		{ time 7300 length 4400 text "The Port MacArthur training facility has enough hardware to warm the heart of any leatherneck." }
	}

	multisub brief07 {
		{ time 700 length 3900 text "The UNN Secretary-General's office needs a full staff of armed guards." }
		{ time 5000 length 4200 text "When things are dull, it requires a lot of standing around looking good in a uniform." }
		{ time 9700 length 4000 text "When things are bad, it can require fending off a psi-terrorist assault." }
	}

	multisub brief08 {
		{ time 700 length 3400 text "The Polidies trading station's long been a haven for the black market." }
		{ time 4400 length 4000 text "However, up until now they have not interfered with the running of station operations." }
		{ time 9100 length 6900 text "Recent reports indicate that the Polidies command staff has been overthrown, and the station is under the control of a self-appointed \"Magnate\"." }
		{ time 16500 length 3700 text "This must be rectified and a Marine presence maintained on the station." }
	}
 
	multisub brief09 {
		{ time 800 length 5400 text "The Colony Air Service gets the dregs of the fleet, and the Antigua is the dregs of the dregs." }
		{ time 7000 length 6800 text "You'll learn a lot about recalcitrant machinery on a tour of duty aboard the Antigua, if it doesn't blow you to hell and back first." }
	}

	// Navy briefings

 	multisub brief10 {
		{ time 800 length 5200 text "The UNN Lucille is looking for an ops training officer to learn the ship's navigation and data control systems." }
		{ time 6400 length 3700 text "You'll get your feet wet with the high-tech systems, but also expect some heavy lifting." }
	}

	multisub brief11 {
		{ time 900 length 4600 text "The UNN Lucille is looking for an engineer's mate to help maintain the ship's core energy systems." }
		{ time 5900 length 3800 text "There's some heavy lifting involved, sailor, but you'll learn your way around the high-tech equipment." }
	}

	multisub brief12 {
		{ time 800 length 3600 text "The UNN Lucille is looking for volunteers for their military police detachment." }
		{ time 4900 length 4500 text "Those sailors can get pretty rowdy on these year-long cruises, so you better not be afraid of a tussle." }
	}

	multisub brief13 {
		{ time 800 length 6300 text "The UNN Carfax is undertaking a mission to examine a newly discovered class B comet approaching the outer solar system." }
		{ time 8000 length 5500 text "You'll likely pick up some useful skills working with the high-tech navigation systems aboard this newly commissioned heavy cruiser." }
	}

	multisub brief14 {
		{ time 800 length 4600 text "The UNN Pierce is ferrying liberated political prisoners back home from their detention near Saturn." }
		{ time 6100 length 6300 text "The Pierce has been assigned a detachment of Marines and needs sailors to load, administer, and maintain the arms on board the ship." }
	}

	multisub brief15 {
		{ time 800 length 3200 text "LaVerne, Florida hosts the Navy's premiere Tactical Training School." }
		{ time 4500 length 4400 text "While maybe not as respected as the Marine's facility at Fort Bush, there's a lot to be learned here." }
	}

	multisub brief16 {
		{ time 800 length 9500 text "The Navy's Marie Curie Research Facility on Aquinas IV is currently conducting research on a new strain of spaceborne virus that killed 220,000 citizens of New Atlanta." }
		{ time 11100 length 4500 text "To lift the quarantine, we must determine how the virus pierced the city's micronanite shielding." }
	}

	multisub brief17 {
		{ time 800 length 4500 text "The Navy maintains a survival training school on the surface of Io, the third moon of Jupiter." }
		{ time 5900 length 3700 text "Pros: there's no better way to improve stamina and survival skills." }
		{ time 10000 length 3100 text "Cons: the 21.2% mortality rate." }
	}

	multisub brief18 {
		{ time 900 length 3800 text "The Navy strongly encourages every sailor to undertake some amount of zero-g training." }
		{ time 5400 length 4300 text "A year at the Yamamoto space station in Earth's orbit will more than suffice." }
	}

	// OSA briefings

	multisub brief19 {
		{ time 800 length 4100 text "The sensory deprivation tanks aboard the TOS Shao Ling await you." }
		{ time 5300 length 6400 text "There, you will spend a solitary year focused in a meditation on motion and sound, and how they may serve your will." }
	}

	multisub brief20 {
		{ time 700 length 4200 text "The sensory deprivation tanks abord the TOS Ru Nang await you." }
		{ time 5400 length 3800 text "A year in meditation on the nature of matter will grant you power over it." }
	}

	multisub brief21 {
		{ time 800 length 5400 text "The sensory deprivation tanks abord the TOS Chu Lun are modulated for your training." }
		{ time 6700 length 6700 text "You shall spend a year in contemplation of mass - both yours and that of objects - until you can bend them to your intentions." }
	}

	multisub brief22 {
		{ time 900 length 7900 text "Sifting the thoughts of treachery and disloyalty from the morass of emotion and internal conflict that fill most mundanes can be disquieting." }
		{ time 9200 length 7700 text "You shall spend a year building the general strength of your mind, while learning how to probe the thoughts of the less capable without losing yourself." }
	}

	multisub brief23 {
		{ time 900 length 5800 text "Doctor Chandrisvilan's research labs have produced many of this decade's advances in psionic technique." }
		{ time 7000 length 5200 text "You shall spend a year serving his genius, learning to understand his insights and whims." }
	}

	multisub brief24 {
		{ time 800 length 2900 text "Your body has been neglected in your training of your mind." }
		{ time 4100 length 3700 text "On Io, you will find soldiers who wish to test their endurance." }
		{ time 8200 length 4400 text "You will surpass their physical prowess without compromising your mental dicipline." }
	}

	multisub brief25 {
		{ time 800 length 5600 text "Acts of political terrorism and corporate coercion disturb corporate and political stability." }
		{ time 6900 length 5700 text "You shall spend a year battling these chaotic elements, both psionically and by physical force." }
	}

	multisub brief26 {
		{ time 800 length 4900 text "In the grand scheme, individuals are no more important than pieces on a game board." }
		{ time 5900 length 5600 text "Occasionally it becomes necessary to remove a piece, without disturbing the flow of the game." }
		{ time 12200 length 3700 text "These removals will be done in silence and with complete secrecy." }
		{ time 16300 length 2600 text "You shall spend a year learning these skills." }
	}

	multisub brief27 {
		{ time 800 length 3700 text "Many threats to security can only be defeated from inside." }
		{ time 4800 length 5200 text "Your mind shall be carefully blanked and conditioned with the nature and past of a criminal." }
		{ time 10600 length 8400 text "Join with the criminal and rebellious, endure their squalor and chaos, and then, when it is time, liquidate them from within." }
	}
}
