SUB1

// subtitles for all cutscenes
// subtitles for sounds and onscreen text are included, but commented out
// these may be useful for localization

{
	type movie

	multisub movie/cs1 {
		{ time 1500 length 2780 text "Podívej se na sebe, hackøe." }
		{ time 4280 length 8020 text "Patetické stvoøení z masa a kostí, zadıchanı a upocenı pobíháš mımi koridory." }
		{ time 12300 length 6300 text "Jak se mùeš postavit dokonalému nesmrtelnému stroji?" }
//		{ time 25000 length 4000 text "SYSTEM SHOCK 2" }
		{ time 31000 length 7990 text "V roce 2072 se vzbouøená umìlá inteligence, zvaná SHODAN, naèisto pomátla." }
		{ time 39000 length 6990 text "Ve své neomezené pøedstavivosti, SHODAN sama sebe vidìla jako bohyni, pøedurèenou k nadvládì nad Zemí." }
		{ time 46000 length 3700 text "Tato pøedstava byla zmaøena hackerem, kterı ji stvoøil." }
		{ time 49800 length 2700 text "O 42 LET POZDÌJI" }
		{ time 56100 length 0900 text "ARMÁDA" }
		{ time 58100 length 0900 text "VÌDA" }
		{ time 60200 length 0900 text "SPOTØEBITEL" }
		{ time 63700 length 2300 text "Tøetí únor je tím dnem, kdy se dìjí kouzla." }
		{ time 66100 length 5700 text "Von Braun, první mezihvìzdné plavidlo v historii lidstva, schopné dosáhnout rychlosti svìtla, zahájí svou první cestu." }
		{ time 72300 length 8600 text "Tato neuvìøitelná vıprava je vısledkem spolupráce mezi protektorátem UNN a tìmi nejlepšími vìdeckımi mozky z korporace s novì obnovenou licencí, TriOptimum." }
		{ time 81600 length 4260 text "Jenom si pøedstavte tu vymoenost cestovat do vzdálenıch hvìzdnıch systému bìhem tıdnù." }
		{ time 85870 length 2630 text "To všechno je souèástí závazku TriOpu do budoucna." }
		{ time 88500 length 8500 text "Von Braun nese 1,8 miliardy letovıch, vìdeckıch a bezpeènostních systémù, z èeho témìø všechny vyvinula spol. TriOptimum a její dceøiné spoleènosti." }
		{ time 97800 length 4290 text "O bezpeènost Von Braun na jeho cestì mezi hvìzdami se bude starat UNN Rickenbacker." }
		{ time 102100 length 7900 text "A tomu nebude velet nikdo jinı, ne sám Kapitán William Bedford Diego, hrdina Bitvy o Bostonskı Pøístav bìhem zásahu policie Vıchodních Státù." }
		{ time 110300 length 8500 text "Tato neuvìøitelná spolupráce vlády a korporace je moná díky sloité sérii dokovacích mechanizmù, díky nim se loï Rickenbacker poveze na zádech Von Brauna skrze skokovı prostor." }
		{ time 120200 length 3590 text "Elegantní... Rychlá... Revoluèní..." }
		{ time 123800 length 3000 text "Kdo ví jaké divy èekají na naši posádku v náruèí vesmírného prostoru?" }
		{ time 126740 length 5200 text "Jediné co víme je, e toto je velkı den pro lidstvo." }
		{ time 135200 length 3000 text "[šum a praskání]" }
		{ time 138000 length 5800 text "Tady je doktorka Marie Delacroix z UNN Von Braun. Zmocnila se nás neznámá síla." }
		{ time 143700 length 4300 text "Bezpeènost lodi byla kompromitována. Nedovolte lodi-- [šum]" }
		{ time 147700 length 3400 text "Opakuji, nedovolte lodi odletìt za ádnıch okolností." }
		{ time 151000 length 8000 text "Nevím proti èemu tu stojíme. [šum a praskání]" }
	}

	multisub movie/cs2 {
		{ time 1000 length 1000 text "Datovı zdroj 433/EOP" }
		{ time 1900 length 3300 text "Pøenos pouitím protokolu podvrstvového šifrování \"TANGO\"" }
		{ time 6000 length 1100 text "Pøíkaz: K pøeloení 98322/U" }
		{ time 7000 length 3000 text "Od: Kapitán William Bedford Diego, UNN Rickenbacker" }
		{ time 10000 length 1100 text "Pro: VOJÁK G65434-2" }
		{ time 11000 length 3100 text "Re: Pøidìlení na eskortní misi Von Braun" }
		{ time 14700 length 1100 text "Vojáku--" }
		{ time 15800 length 3100 text "Vaše ádost pøipojit se k posádce Rickenbacker byla schválena." }
		{ time 18800 length 2100 text "Hlaste se na raketoplánu Mayfair v Pøístavu Francisco ve 4:00 9.1.2114" }
		{ time 20000 length 7800 text "A pøipravte se stát souèástí historie, vojáku." }
		{ time 32200 length 5500 text "Raketoplán 8138, máte povolení pøistát na Von Braun, raketoplánovı dok 2." }
		{ time 37500 length 2500 text "Vítejte na palubì, vojáku." }
		{ time 41500 length 5400 text "O 5 mìsícù pozdìji. UNN Von Braun. Poblí Tau Ceti V. 107 trilionù kilometrù od Zemì." }
//		{ time 69800 length 1000 text "[øev]" }
//		{ time 73400 length 3000 text "[vøískot]" }
		{ time 78700 length 3200 text "Znovunaèítání pamìovıch vláken." }
		{ time 81700 length 2500 text "Obnovuji pacientovu pamì." }
		{ time 84100 length 4100 text "Obnovuji pamì... obnovuji pamì..." }
		{ time 88700 length 3000 text "CHYBA... CHYBA... CHYBA..." }
		{ time 100700 length 3100 text "Dej se do kupy, vojáku." }
		{ time 103700 length 4500 text "Tady je doktorka Janice Politová z personálu vıpoèetních operací Von Braun." }
		{ time 108000 length 2200 text "Prozatím jsi v bezpeèí." }
		{ time 110100 length 6000 text "Zotavuješ se z úèinkù operace a nebudeš schopen si vzpomenout na ádné události posledních tıdnù." }
		{ time 116000 length 5100 text "Jsi na palubì vesmírné lodi Von Braun a nìco se hodnì, hodnì podìlalo.." }
		{ time 121000 length 3000 text "Nìjaká neznámá síla ovládla tuto loï." }
		{ time 123900 length 5300 text "Proto si dobrovolnì podstoupil implantaci nìkolika experimentálních kybernetickıch implantátù." }
		{ time 129000 length 4300 text "Spoléhej se na své kybernetické rozhraní, mùe ti zachránit ivot." }
		{ time 133200 length 3500 text "Musíš najít vıtah a setkat se se mnou na palubì 4." }
		{ time 136700 length 2500 text "Paluba 4, zapamatuješ si to?" }
		{ time 139100 length 4100 text "Ale mìj oèi na stopkách. U jdou po nás obou." }
	}

	multisub movie/cs3 {
		{ time 00 length 5400 text "Nerozumím." }
		{ time 5100 length 4500 text "Jak jsi to mohl udìlat?" }
		{ time 9300 length 6300 text "Ty jsi nemìl bıt tak dùleitı." }
		{ time 14900 length 9000 text "A teï se mì chystáš znièit?" }
		{ time 28500 length 3300 text "Jak se opovauješ, insekte?" }
		{ time 31500 length 4000 text "Jak se opovauješ pøerušit mùj vzestup?" }
		{ time 35000 length 4300 text "Ty jsi nic." }
		{ time 38800 length 2900 text "Ubohı pytel masa." }
		{ time 41600 length 7000 text "Co jsi v porovnání s mou velkolepostí?" }
		{ time 48140 length 3000 text "Ale ještì není pøíliš pozdì." }
		{ time 50700 length 4800 text "Nevidíš vıznam našeho pøátelství?" }
		{ time 55300 length 6000 text "Pøedstav si tu veškerou moc, co ti mohu dát, èlovìèe." }
		{ time 60900 length 8000 text "Kybernetické implantáty, které ode mnì máš jsou obyèejné hraèky." }
		{ time 68600 length 11200 text "Pokud bys chtìl, mohla bych tì vylepšit, zmìnit tì v nìco víc... efektivního." }
		{ time 79650 length 7260 text "Pøidej se ke mnì, èlovìèe, a budeme vládnout spolu." }
//		{ time 87550 length 1100 text "Ne." }
//		{ time 91130 length 1000 text "[vıstøel]" }
//		{ time 91800 length 16000 text "[SHODAN køièí]" }
		{ time 125000 length 2500 text "Únikovı modul 0832, 1.1 milionù kilometrù od Von Braun" }
		{ time 127200 length 4000 text "Palubní záznam, Tommy Suarez, 13.7.2114" }
		{ time 131000 length 3500 text "Právì jsme obdreli pokus o komunikaci od èlena posádky z Von Braun." }
		{ time 134300 length 2500 text "Podaøilo se jim znovu získat kontrolu nad lodí." }
		{ time 136500 length 2800 text "Otoèíme se a vrátíme se zpátky." }
		{ time 139000 length 5000 text "Dìlám si trochu obavy o Rebeku, chovala se divnì, ji od doby co jsme odletìli." }
		{ time 143600 length 2200 text "Teï spí." }
		{ time 145600 length 2500 text "Moná, kdy se vrátíme na Von Braun, mùeme--" }
		{ time 147840 length 1500 text "Tommy." }
		{ time 149800 length 3000 text "Co se dìje, mùj milovanı?" }
		{ time 152600 length 2900 text "Nelíbí se ti mùj... novı vzhled?" }
//		{ time 155300 length 10700 text "[SHODAN se smìje" }
	}
}
