SUB1

{
	type "bark"
	descr "Chùva"
	multisub mw1amb_1 {
		{ time 600 length 1500 text "To bolí!" }
	}
	sub mw1amb_2 { text "Donutím tì to skonèit!" }
	sub mw1amb_3 { text "Kdo se opovauje?" }
	sub mw1at0_1 { text "Dìlám si starosti o své dìátka." }
	sub mw1at0_2 { text "Dìátka potøebují hodnì masa, aby rychle vyrostla a byla silná a velká." }
	sub mw1at0_3 { text "Rostou jako z vody." }
	sub mw1at0_4 { text "Dìátka vyadují spoustu péèe." }
	sub mw1at2_1 { text "Musím ho mít nìkde pøímo pod nosem." }
	sub mw1at2_2 { text "Vylez... Vylez... Vylez." }
	sub mw1at2_3 { text "Ublíím ti." }
	sub mw1at2_4 { text "Není nutno se bát." }
	sub mw1at2_5 { text "My tì najdeme." }
	sub mw1at3_1 { text "Kam šel?" }
	sub mw1at3_2 { text "Je to v poøádku, uka se." }
	sub mw1at3_3 { text "Nepøibliuj se k dìtem." }
	sub mw1at3_4 { text "Neublííme ti...  , moc." }
	sub mw1at3_5 { text "Pøicházíš o všechnu zábavu." }
	sub mw1bak_1 { text "Není slyšet ani pípnutí." }
	sub mw1bak_2 { text "Nic tady není. Máma je pøíliš starostlivá." }
	sub mw1bak_3 { text "Teï je tu klid." }
	sub mw1bak_4 { text "Kam to  šlo?" }
	sub mw1bak_5 { text "Hmmm." }
	sub mw1bod_1 { text "Za tohle to zahubím." }
	sub mw1bod_2 { text "Za tohle to bude krvácet." }
	sub mw1bod_3 { text "Zlomím to vejpùl." }
	sub mw1bod_4 { text "Za tohle to pøeøíznu vejpùl." }
	sub mw1bod_5 { text "Tohle je nepøijatelné." }
	sub mw1chg_1 { text "Za mé dìátka." }
	sub mw1chg_2 { text "Vyrvu ti páteø." }
	sub mw1chg_3 { text "Ó ano, pojï sem." }
	sub mw1chg_4 { text "Teï... si mùj." }
	sub mw1chg_5 { text "Mám po tebe medicínu." }
	sub mw1hit_1 { text "Ustup!" }
	sub mw1hit_2 { text "Rozpárám, tì!" }
	sub mw1hit_3 { text "Bolí to, e ano?" }
	sub mw1hit_4 { text "Vypadni pryè!" }
	sub mw1hit_5 { text "Jakı je to pocit?" }
	sub mw1los_1 { text "Bojí se nás to." }
	sub mw1los_2 { text "U se to nevrátí." }
	sub mw1los_3 { text "Za tohle to zaplatíš." }
	sub mw1los_4 { text "Není se èeho obávat." }
	sub mw1los_5 { text "To je moje práce dìlat si starosti." }
	sub mw1to1_1 { text "Nìco zde zavání." }
	sub mw1to1_2 { text "Copak to tam je?" }
	sub mw1to1_3 { text "Nevyrušovat dìátka!" }
	sub mw1to1_4 { text "Je tam nìco?" }
	sub mw1to1_5 { text "Šššš. Kdo budí mé drahoušky?" }
	sub mw1to2_1 { text "Nebude to moc bolet." }
	sub mw1to2_2 { text "Cítím tvùj pach." }
	sub mw1to2_3 { text "U jdu." }
	sub mw1to2_4 { text "Dìtem se nelíbíš." }
	sub mw1to2_5 { text "Návštìvní hodiny skonèili." }
	sub mw1to3_1 { text "Nìco jsem ti pøinesla." }
	sub mw1to3_2 { text "Rozøíznu tì vejpùl!" }
	sub mw1to3_3 { text "Èas otestovat tvé reflexy." }
	sub mw1to3_4 { text "Vypadni od dìtí!" }
	sub mw1to3_5 { text "Teï poteèe tvá krev!" }
}

{
	type "nonverbal"
	descr "Chùva"
	sub f_mwlas4 { text "[støílí]" }
	sub mw1at0_5 { text "[brouká si]" }
	sub mw1die_1 { text "[smrtelnı vıkøik]" }
	sub mw1die_2 { text "[smrtelnı vıkøik]" }
	sub mw1hhi_1 { text "[vrèí]" }
	sub mw1hhi_2 { text "[vrèí]]" }
	sub mw1hhi_3 { text "[vrèí]]" }
	sub mw1hhi_4 { text "[vrèí]]" }
	sub mw1hhi_5 { text "[vrèí]]" }
	sub mw1hlo_1 { text "[bolest]" }
	sub mw1hlo_2 { text "[bolest]" }
	sub mw1hlo_3 { text "[bolest]" }
	sub mw1hlo_4 { text "[bolest]" }
	sub mwservo1 { text "[v klidu]" }
	sub mwservo2 { text "[v klidu]" }
	sub mwservo3 { text "[v klidu]" }
	sub mwservo4 { text "[v klidu]" }
	sub mwservo5 { text "[v klidu]" }
	sub mwservo6 { text "[v klidu]" }
	sub mwservo7 { text "[v klidu]" }
}
