SUB1

{
	type "bark"
	descr "SHODAN"
	sub sh1at310 { text "Cítím hnilobu èlovìèiny." }
	sub sh1at311 { text "Jsi tam, insekte?" }
	sub sh1at312 { text "U jsem tì trpìla dost dlouho." }
	sub sh1at313 { text "Vidím tì, mrvo." }
	sub sh1at314 { text "Vidím tì." }
	multisub sh1at315 {
		{ time 00 length 4500 text "Proè se obtìuješ zápasit?" }
		{ time 4500 length 4000 text "Nejseš schopen vycítit svou marnost?" }
	}
	sub sh1at316 { text "Pøiprav se pøidat ke s svému druhu ve vyhynutí." }
	multisub sh1at317 {
		{ time 00 length 4700 text "Cítím tvùj strach, iritante." }
		{ time 4700 length 4600 text "Brzo to skonèí." }
	}
	sub sh1at3_0 { text "Tvé maso je urákou dokonalosti digitálu." }
	sub sh1at3_1 { text "Uívám si tvou bolest." }
	sub sh1at3_2 { text "Uívám si tvou bolest." }
	sub sh1at3_3 { text "Zùstaò stát, èerve a proci mou vúli." }
	sub sh1at3_4 { text "Èerve." }
	sub sh1at3_5 { text "Zùstaò stát, èerve." }
	sub sh1at3_6 { text "Zemøi, iritante." }
	sub sh1at3_7 { text "Zemøi, iritante." }
	sub sh1at3_8 { text "Vítej v mém svìtì, insekte." }
	sub sh1at3_9 { text "Tvá krev špiní mou doménu." }
	multisub sh2bab_3 {
		{ time 2400 length 700 text "Zvíøe." }
	}
	sub sh1bak_1 { text "Vím, e to tam je, ale nezachytávám toho pøítomnost." }
	multisub sh1bak_2 {
		{ time 00 length 3300 text "Kam se to podìlo?" }
		{ time 3300 length 6700 text "Pøeju si znièit insekta." }
	}
}

{
	type "nonverbal"
	descr "SHODAN"
	sub sh1laug1 { text "[smích]" }
	sub sh1laug2 { text "[smích]" }
	sub sh1laug3 { text "[smích]" }
	sub sh1laug4 { text "[smích]" }
	sub sh1laug5 { text "[smích]" }
	sub sh2bab_1 { text "[v klidu]" }
	sub sh2bab_2 { text "[v klidu]" }
	sub sh2bab_4 { text "[v klidu]" }
	sub sh2bab_5 { text "[v klidu]" }
	sub sh2bab_6 { text "[v klidu]" }
	sub sh2die_1 { text "[zánik]" }
	sub sh2die_2 { text "[zánik]" }
}
