SUB1

// Engineering =================================================================
{
	type "convo"
	descr "Politová"
	multisub em0101 {
		{ time 400 length 4300 text "Musíš si pospíšit. Ještì si neuvìdomuješ, co všechno je v sázce." }
		{ time 5300 length 4700 text "Dej pozor na pøíruèní sklad è.4. Nechala jsem tam nìjaké vybavení." }
		{ time 10000 length 6600 text "Vstupní kód je 59004. Musím jít na palubu..." }
		{ time 18600 length 2700 text "[Xerxes] Mnoho poaduje ukonèení této komunikace." }
		{ time 22000 length 2200 text "[Xerxes] Omlouváme sa za vzniklé potíe." }
	}
	multisub em0102 {
		{ time 500 length 6200 text "Teï pozornì poslouchej. Xenomorfové, kteøí si podrobili tuto loï, pocházejí pravdìpodobnì z povrchu Tau Ceti 5." }
		{ time 7300 length 5300 text "Byli schopni infikovat vìtšinu èlenù posádky, prostøednictvím mimoøádné invazivní parazitní techniky." }
		{ time 13100 length 6200 text "Také pøedvedli schopnost ovládat chování ostatních pomocí urèité formy omezené telepatie." }
		{ time 19900 length 4000 text "Najdi vızkumnı software. Porozumìj jim... a pak je zniè." }
	}
	multisub em0103 {
		{ time 1200 length 4000 text "Radiace musela aktivovat ochranné zámky pøístupu k Reaktoru." }
		{ time 5500 length 3800 text "Musíš najít nìjakı zpùsob, jak odstranit radiaci z potrubí chladícího okruhu." }
		{ time 9700 length 5100 text "Xerxes blokuje mùj pøístup do primární databáze, take nemohu získat ádné informace, které by mohli pomoci." }
		{ time 15400 length 1600 text "Xerxes teï pracuje pro nì." }
	}
	multisub em0104 {
		{ time 1100 length 6200 text "Dávej dobrı pozor... musíš najít zpùsob, jak vyèistit chladící potrubí a tak se dostat k Reaktoru..." }
		{ time 7700 length 5200 text "Tato loï musí mít nìjakı druh záloního systému, pøipraveného pro tuhle situaci." }
 	}
	multisub em0105 {
		{ time 800 length 3300 text "Dobøe, vıtahy by mìli  bıt nyní opìt funkèní." }
		{ time 5800 length 3400 text "Otevøu pøístupovı tunel, kterı ti umoní se rychle dostat k vıtahu." }
		{ time 9600 length 3500 text "Nyní se dostaò na palubu 4,  Budu tu na tebe èekat. Pospìš si." }
	}
	multisub em0106 {
		{ time 700 length 6800 text "Teï spus motorové bloky. Budeš muset jít do gondol 1 a 2 a ruènì spustit generátory." }
		{ time 7900 length 7800 text "Pak restartuj systém øízení Reaktoru. Pozor, systém nenabìhne, pokud pøedtím nespustíš oba motorové bloky." }
		{ time 16400 length 5900 text "Buï opatrnı. Oni teï shromaïují své skuteèné síly. A u pøesnì vìdí, kde se nacházíš." }
	}
	multisub em0107 {
		{ time 1800 length 6700 text "Xerxes je o krok pøed námi. Vytvoøil pøemostìní na Poèítaèi Kapalinového Øízení a zablokoval pøístup." }
		{ time 8700 length 4000 text "Dávej pozor. Mìl bys bıt schopen najít nìjaké øešení" }
	}
	multisub em0108 {
		{ time 1300 length 6500 text "Dobrá práce. Reaktor je opìt spuštìn. Teï bì do vıtahu a pøijï za mnou na 4. palubu." }
		{ time 8300 length 5000 text "Zatímco jsi byl zamìstnán, odhalila jsem na palubì pøítomnost nìkterıch annelidskıch artefaktù." }
		{ time 13800 length 3000 text "Myslím, e bys byl schopen je pouít ke svému prospìchu." }
		{ time 17300 length 3500 text "Uloila jsem tyto informace do lodních jednotek vylepšování dovedností." }
		{ time 21100 length 3500 text "Ty teï budou schopny pøedat zmínìné údaje do tvého kybernetického vybavení." }
		{ time 25400 length 2900 text "Na co ještì èekáš? U a jsi ve vıtahu." }
	}
	multisub em0110 {
		{ time 600 length 2000 text "Teï jsi na Technické palubì." }
		{ time 3100 length 4800 text "Najdi Reaktor a znovu ho nastartuj. Tím se obnoví napájení vıtahù." }
		{ time 8200 length 4200 text "Dostávám odtud spousty podivnıch údajù, take si dávej dobrı pozor." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0109 {
		{ time 1500 length 6200 text "Teï jsem schopná znièit tu nákazu, kdykoli budu chtít." }
		{ time 8800 length 4600 text "Mnoho se bude tøást pøed mou mocí." }
		{ time 14800 length 3600 text "Jsi vıkonnı sluha, èlovìèe." }
		{ time 18900 length 12700 text "Teï se vra na palubu Velení, najdi prùchod a pøesuò se na Rickenbacker." }
	}
}

// Med/Sci ==========================================================================
{
	type "convo"
	descr "Politová"
	multisub em0201 {
		{ time 1200 length 4000 text "V celém sektoru se sniuje tlak a modré vakuové štíty to u dlouho nevydrí." }
		{ time 5800 length 2700 text "Dostaò se za hermetickı uzávìr døív, ne tì to vysaje do vesmíru." }
		{ time 8800 length 600 text "Dìlej!" }
	}
	multisub em0202 {
		{ time 500 length 3000 text "Nìkteré z dveøí jsou zamèeny kódovımi zámky." }
		{ time 4000 length 3600 text "Tìlo leící pøed tebou patøilo údrbáøi tohoto sektoru." }
		{ time 8200 length 4600 text "Moná má ten èíselnı kód u sebe. Nebuï háklivı a prohledej jeho tìlo." }
		{ time 13500 length 1000 text "Jemu to u vadit nebude." }
	}
	multisub em0203 {
		{ time 500 length 3500 text "Ten nanicovatı poèítaè Xerxes odpojil všechny vıtahy." }
		{ time 4700 length 4600 text "V blízkosti reaktoru, na palubì 1, bys mohl zapojit nouzové napájení, které by je všechny zase zprovoznilo." }
		{ time 9800 length 3200 text "Jene vıtahem se tam teï nedostaneš. Poèkat..." }
		{ time 14400 length 3100 text "Je tady nìjakı druh údrbáøského pøístupu, právì z této chodby." }
		{ time 18300 length 6000 text "Tudy by ses mohl dostat na palubu 1. Jene vstup je zamèen a Xerxes mi nechce prozradit vstupní kód." }
		{ time 25000 length 3300 text "Mìl by ho ale mít i Dr. Watts. Bude nejspíš nìkde v sektoru Kajut pro posádku." }
		{ time 28900 length 5900 text "Vstupní kartu tam má Grassi, ale ten je zase nìkde v lékaøskıch prostorech, zøejmì poblí pitevny." }
		{ time 35300 length 2700 text "Bì co nejdøív do prostorù Kliniky a najdi Grassiho." }
	}
	multisub em0204 {
		{ time 500 length 5500 text "Vıbornì. Dostal jsi se na Kliniku. Najdi Grassiho a získej vstupní kartu do sektoru Kajut posádky." }
		{ time 6600 length 4200 text "Grassi se staral o tvùj kryogenickı spánek, tak se moná bude chtít k tobì pøidat..." }
		{ time 11400 length 1700 text "Pokud ovšem není na kousky." }
	}
	multisub em0205 {
		{ time 1100 length 3300 text "Mùeš hackovat i replikátory, èím získáš nadstandardní nabídku." }
		{ time 4900 length 3200 text "Vyuij to. Vyuij jakoukoliv monost, aby ses dostal na palubu 4." }
		{ time 8500 length 1500 text "Tohle není hra." }
	}
	multisub em0206 {
		{ time 1000 length 2500 text "Neztrácej èas samochválou." }
		{ time 3900 length 3800 text "Slez šachtou dolù do Techniky a znovu spus hlavní Reaktor." }
		{ time 8100 length 3400 text "Obnovíš tím napájení vıtahù a budeš koneènì schopen se dostat na palubu 4." }
		{ time 11900 length 700 text "Do toho!" }
	}
	multisub em0207 {
		{ time 900 length 4500 text "Fajn. U jsi v sektoru Kajut posádky. Ted najdi kajutu Dr. Wattse..." }
	}
	multisub em0208 {
		{ time 500 length 3200 text "Tvé nové kybernetické rozhraní mùe bıt dezorientující." }
		{ time 4000 length 6900 text "Nahrála jsem detailní technické specifikace do terminálù ve tvém okolí, ty ti zodpoví tvé otázky o jejich pouití." }
		{ time 11400 length 3800 text "Rùzné oblasti lodi potøebují pro vstup specifické pøístupové karty." }
		{ time 15700 length 3900 text "Seber kartu blízko sebe a aktivuj slot pro vstupní kartu u dveøí." }
	}
	multisub em0209 {
		{ time 1000 length 3700 text "Ten èlánek je vybitı. Nìkde poblí by mìla bıt dobíjecí stanice." }
		{ time 5000 length 3900 text "Pouij ji a ona dobije všechny energetické zaøízení, které máš u sebe." }
		{ time 9400 length 6000 text "A èlánek nabiješ, vlo ho do záloního napájení u dveøí. Tím by se mìl otevøít hermetickı uzávìr." }
		{ time 15700 length 3600 text "Pospìš si s tím, vakuová tìsnìní u to déle nevydrí." }
	}
	multisub em0210 {
		{ time 900 length 5800 text "Xerxes ovládá bezpeènostní systémy. Vyhıbej se kamerám, nebo je zniè." }
		{ time 7300 length 4500 text "Pokud na to staèíš, mùeš hackovat bezpeènostní poèítaèe, èím se kamery na èas vypnou." }
		{ time 11900 length 3000 text "Ale pozor, pokud to zpackáš, spustí se poplach." }
		{ time 15400 length 2100 text "A jako mrtvola mi nejsi k nièemu." }
	}
	multisub em0211 {
		{ time 900 length 4000 text "Ujisti se, e jsi utratil všechny své kybernetické moduly, pøedtím ne opustíš tuto oblast." }
		{ time 5500 length 2500 text "Nevíš kdy nelezneš další vylepšovací jednotky." }
		{ time 8700 length 1900 text "Nyní najdi cestu na palubu 4." }
	}
	multisub em0212 {
		{ time 1400 length 6100 text "There's a number of cyber upgrade stations in this area, one for each of your unit's enhancement functions:" }
		{ time 7900 length 5000 text "Firearms, basic abilities, psionic projection, and technical skills." }
		{ time 13700 length 7300 text "I'm uploading a few upgrade modules to your gear right now. You'll need them to interface with the upgrade stations." }
		{ time 21600 length 5400 text "But choose your enhancements very carefully... upgrade units are difficult to come by." }
	}
	multisub em0213 {
		{ time 900 length 5900 text "Tyto kybernetické moduly se pouívají k vylepšování jednotlivıch subsystémù tvıch neurálních vylepšení." }
		{ time 7300 length 7200 text "Pamatuj, jsou 4 rùzné druhy jednotek vylepšování dovedností, take nevyplıtvej všechny své moduly u jediné," }
		{ time 14600 length 4800 text "tedy pokud si nejsi opravdu jist, e chceš zlepšit svùj hardware jenom v jedné oblasti." }
	}
	multisub em0214 {
		{ time 700 length 5500 text "Dr. Watts je ve své pracovnì a stále ije.  Mìl by znát pøístupovı kód údrbáøské šachty." }
		{ time 6700 length 6000 text "Pospìš si, je tìce zranìn!  Nenech ho umøít, dokud ti neøekne to èíslo!" }
	}
	multisub em0215 {
		{ time 700 length 5000 text "Pozor... Z radarové antény za oknem pøicházejí nìjaké zvláštní údaje." }
		{ time 6400 length 1600 text "Stává se nestabilní protoe..." }
		{ time 8000 length 2400 text "Utíkej!  Kryj se!" }
	}
	multisub em0217 {
		{ time 700 length 6700 text "Sakra! Vıpadek napájení vyøadil i dveøe této pøepáky. Je jen jeden zpùsob, jak se dostat do lékaøského oddìlení." }
		{ time 7900 length 2600 text "Vezmi èlánek leící na podlaze a najdi dobíjecí stanici." }
		{ time 11100 length 5000 text "Obávám se e ta, kterou jsi pouil pøedtím je u ve vakuu, ale na této palubì by mìla bıt ještì jedna." }
		{ time 16700 length 4100 text "A ten èlánek nabiješ, vlo ho do záloního napájení." }
	}
	multisub em0218 {
		{ time 600 length 4000 text "Watts tu není.  Nejspíš bude ve své pracovnì v sektoru R&D." }
		{ time 5000 length 3700 text "Ale moná, e tu má nìkde záloní R&D kartu.  Rozhlédni se kolem." }
	}
	multisub em0219 {
		{ time 600 length 3600 text "Na vìtšinì palub mùeš najít biorekonstrukèní zaøízení." }
		{ time 4800 length 3900 text "Xerxes je všechny odpojil, ale já jsem je zase potají zapojila." }
		{ time 9400 length 4400 text "Zaøízení musíš aktivovat, abys mu poskytl soubor tkáòovıch vzorkù." }
		{ time 14400 length 4900 text "A to udìláš, bude toto zaøízení schopno restaurovat tvé tìlo i z nepatrného zbytku." }
		{ time 19800 length 3500 text "Není to sice nic pøíjemného, ale stále lepší, ne pomalı rozklad." }
	}
	multisub em0220 {
		{ time 600 length 2300 text "Moná se staneš svìdkem zvláštního jevu." }
		{ time 3300 length 7200 text "Tvé experimentální kybernetické vybavení tøídy R má zesílené vnímání, které by teoreticky mohlo zachytit zbytky psychickıch emisí." }
		{ time 11100 length 5600 text "Tyto emise obvykle pocházejí od nedávno zemøelıch. Literatura je oznaèuje jako duchy." }
		{ time 17000 length 3400 text "Já jim øíkám autohypnotické poruchy v jednotce R." }
		{ time 21200 length 2700 text "Nenech se jimi rozptylovat pøi tvém poslání." }
	}
	multisub em0221 {
		{ time 600 length 4000 text "Vıbornì! Dostal jsi se pryè døív, ne celı prostor ztratil tlak." }
		{ time 5300 length 6900 text "Pøidala jsem ti nìkolik kybernetickıch modulù. Mùeš je pouít ke zlepšení tvé kybernetické vıbavy pomocí Jednotek vylepšování dovedností." }
		{ time 12900 length 5600 text "Ve vedlejší místnosti jich jsou ètyøi druhy - pro kadı subsystém tvého kybernetického vybavení:" }
		{ time 18700 length 2900 text "Stats, PSI, Zbranì a Tech." }
		{ time 22400 length 3200 text "Ale pouívej moduly s rozvahou... tìko se obstarávají." }
	}
	multisub em0222 {
		{ time 700 length 5900 text "Na kadé palubì je umístìn chemickı sklad, kde mùeš najít chemikálie, potøebné k vızkumu nalezenıch artefaktù." }
		{ time 7300 length 5300 text "Nesna se u sebe nosit všechny chemikálie najednou. Je to nepraktické a zbyteèné." }
		{ time 13100 length 4100 text "Tvùj vızkumnı software ti vdy vèas sdìlí, kterou chemikálii potøebuje." }
	}
}

// Hydroponics ======================================================================
{
	type "convo"
	descr "Politová"
	multisub em0301 {
		{ time 700 length 6800 text "Sakra!  Nìco zablokovalo šachtu a vıtah se nemùe dostat na palubu 4. Pokouším se to urèit..." }
		{ time 8400 length 5600 text "Zjistila jsem ohromné mnoství nìjakého druhu biologického materiálu, kterı pronikl do vıtahové šachty." }
		{ time 14700 length 5000 text "Prostøedí na této palubì bylo zmìnìno na ohromnou líheò Xenomorfu." }
		{ time 20200 length 3800 text "Ale pokud zde nebudeš pobıvat pøíliš dlouho, nemìlo by to bıt nebezpeèné." }
		{ time 24300 length 4000 text "Bude ovšem tøeba odstranit ten biomaterial z vıtahové šachty." }
		{ time 28700 length 4200 text "Vstupuji do hlavní databáze.  Zjistíme, co zajímavého tam najdeme." }
	}
	multisub em0302 {
		{ time 1500 length 5500 text "Ok, zùstaò kde jsi.  Je tu nádoba s experimentálním materiálem zvanım Toxin-A." }
		{ time 7600 length 3500 text "Vyvinula ho místní skupina vìdcù, snaící se potlaèit rùst vetøelcù." }
		{ time 11300 length 2600 text "Ale nemám ádné údaje o tom, jak ho správnì pouít." }
		{ time 14600 length 16700 text "Mìl bys bıt schopen to vyzkoumat sám." }
		{ time 17000 length 4600 text "Posílám ti dost kybernetickıch modulù, abys mohl získat dostateènou úroveò vızkumu, pokud ji ještì nemáš." }
	}
	multisub em0303 {
		{ time 1200 length 5000 text "Fajn, Nádoby s Toxinem-A je tøeba umístit pøímo do klimatizaèních jednotek." }
		{ time 6700 length 4500 text "Na této palubì jsou celkem ètyøi.  Pokud se ti podaøí nádoby umístit do všech jednotek," }
		{ time 11200 length 4600 text "mìlo by to znaènì ovlivnit rùst tìhle odpornıch kreatur." }
		{ time 16400 length 3000 text "Rovnì by to mìlo odstranit i biomateriál ve vıtahové šachtì." }
	}
	multisub em0304 {
		{ time 1600 length 4200 text "Proè jsi tak zoufale pomalı?!  Copak si myslíš, e je to jenom nìjaká hra?" }
		{ time 6200 length 3900 text "Jsi naivu jen díky notné dávce štìstí a mé nekoneèné trpìlivosti." }
		{ time 10500 length 1100 text "Hni sebou!" }
	}
	multisub em0305 {
		{ time 1500 length 3700 text "Koneènì!  Pøístroje ukazují, e je vıtahová šachta volná." }
		{ time 5500 length 3300 text "Teï bì na palubu 4.  Budu na tebe èekat." }
	}
	multisub em0306 {
		{ time 1700 length 8000 text "Vıbornì!  Je zjevné, e biomateriál na zdech a ve vıtahové šachtì je napadán rozptylovanım biotoxinem." }
		{ time 10300 length 3200 text "Teï to samé udìlej u dalších tøí klimatizaèních jednotek." }
	}
	multisub em0307 {
		{ time 1300 length 3100 text "U vìdí kde jsi.  Najdi nìjakı zpùsob, jak uvolnit šachtu." }
		{ time 4800 length 2700 text "Já tady udìlám vše, co pùjde.  Teï bì!" }
		{ time 8100 length 1500 text "Na neúspìch není èas." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnoho"
	multisub em0307 {
		{ time 2600 length 7600 text "ivot roste v dìloze tìch stìn... ivto, kterı nikdy nevidìl povrch Zemì." }
	}
	multisub em0508 {
		{ time 1800 length 5100 text "Dìátka musí spát. Dìátka musí odpoèívat." }
		{ time 8100 length 4000 text "Moudrı je ten, kdo je neprobudí." }
		{ time 13000 length 6400 text "Opus toto místo, jinak tì zraníme, jako jsi zranil ty nás." }
	}
	multisub em0807 {
		{ time 1800 length 5600 text "Podvol se biomase a tvé utrpení skonèí." }
	}
}



// Operations =======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0401 {
		{ time 1400 length 8400 text "Mé dìti si pøivlastnily tøi simulaèní jednotky na této palubì." }
		{ time 10300 length 14000 text "Pouívají jejich vıkon k vıvoji mutagenu, kterım pak transformují tìla tvıch mrtvıch kamarádù na zabijácké hybridy." }
		{ time 24700 length 10500 text "To nedovolím.  Musíš najít nìjakı zpùsob, jak pøeprogramovat simulaèní jednotky." }
		{ time 35400 length 5300 text "Tvou pozornost si také zaslouí dìní na palubì 5." }
		{ time 40800 length 5400 text "Pus se do toho, jak uznáš za vhodné..., ale dokonèi to, èlovìèe..." }
		{ time 46800 length 8200 text "Zklamání bych takovému uboákovi, jako jsi ty, rozhodnì neprominula." }
	}
	multisub em0403 {
		{ time 2600 length 11000 text "Má stvoøení se vyvíjejí...  Jejich sjednocená mysl se vzbouøila proti vlastní stvoøitelce." }
		{ time 13700 length 7300 text "Ta havì tì volá, láká tì, aby ses pøipojil k jejich nechutné mase." }
		{ time 22100 length 8400 text "Zniè mé nepøátele...  a já budu nadále trpìt tvoji existenci." }
	}
	multisub em0406 {
		{ time 2100 length 10300 text "Pøed tebou leí støepina krystalu - vıtvor mıch dìtí, a tedy i vıtvor mùj." }
		{ time 12500 length 4400 text "Elegantní zbraò, smrtící, pøesná." }
		{ time 19600 length 9100 text "Nauè se ji pouívat...  Mùe bıt to jediné, co bude stát mezi tebou a jejich nákazou." }
	}
	multisub em0407 {
		{ time 1900 length 4600 text "Za tìmito dveømi leí jedna simulaèní jednotka" }
		{ time 6600 length 8400 text "Pøeprogramuj ji a já získám vìtší kontrolu nad touto lodí na úkor obstaroního Xerxese." }
		{ time 16900 length 6300 text "A budu já paní na této lodi, muù ti otevøít více dveøí." }
		{ time 23200 length 7300 text "Ale teï mi ještì blokují pøístup.  Uráí mou velikost." }
		{ time 31400 length 9300 text "Donu je zaplatit za jejich chybu a já tì za to vyvedu z temnoty." }
	}
	multisub em0408 {
		{ time 1000 length 5000 text "Udìlal jsi hodnì práce, na vìc s tak malou dùleitostí." }
		{ time 9300 length 11200 text "[Xerxes] Varování, systémová data kompromitována. Nepøátelská UI..." }
		{ time 20600 length 5400 text "Xerxes je oslaben.  Pøistupuji do primárního dataloopu." }
		{ time 26700 length 3200 text "Spojuji svou bytost s tuto lodí." }
		{ time 30600 length 5200 text "Má nádhera se rozšiøuje, naplòuje tepny této lodi." }
		{ time 36500 length 7000 text "Získala jsem kontrolu.  Jsem..." }
		{ time 43700 length 8400 text "Ne...  je to beznadìjné...  ta rakovina prorùstá celım Von Braunem." }
		{ time 52300 length 7400 text "Oni vyplnili všechny dostupné zlomy a trhliny...  Podrobili si ji..." }
		{ time 60000 length 7200 text "Není ádná monost...  Aktivovala jsem ústøední vıtah na Rekreaèní palubì." }
		{ time 67800 length 6100 text "Dostaò se na palubu 6.  Svá další pøání ti sdìlím, a tam dorazíš." }
	}
	multisub em0409 {
		{ time 3500 length 6000 text "Udìlal jsi hodnì práce, na vìc s tak malou dùleitostí." }
		{ time 12700 length 3300 text "[Xerxes] Varování..." }
		{ time 16300 length 3200 text "Teï se pøesuò na Rekreaèní palubu." }
		{ time 20200 length 3300 text "Neotálej.  Touím po své pomstì." }
	}
	multisub em0410 {
		{ time 2100 length 5800 text "Teï mùu svou velkolepost kdykoliv pøenést na Rickenbacker." }
		{ time 8400 length 4200 text "Pokraèuj do sálu s reaktorem na Technické palubì." }
		{ time 13100 length 10800 text "Tam mùeš pøedat ovládání pøetíení reaktoru pod mou kontrolu, zadáním autorizaèního destrukèního kódu 94834." }
		{ time 24400 length 11800 text "A to udìláš, pøejdi na Rickenbacker.  Pak oddìlíme obì lodi a koneènì zlikvidujeme tu nákazu." }
	}
}

// Many taunt (used as vtrigger instead of email)
{
	type "convo"
	descr "Mnoho"
	multisub em0405 {
		{ time 2500 length 5100 text "Je to nepøítel Mnoha... nesouznìní v naší symfonii." }
		{ time 7800 length 8500 text "Uij si své sobecké èiny destrukce, je za nima leí snì osamìní." }
	}
}

// Recreation =======================================================================
{
	type "convo"
	descr "Politová"
	multisub em0502 {
		{ time 500 length 1000 text "Co to provádíš?" }
		{ time 2000 length 2700 text "Vra se do vıtahu a jdi na palubu 4." }
		{ time 5100 length 1800 text "Na prohlídku lodi nemáme èas." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0504 {
		{ time 1300 length 9800 text "Plazíš se jako insekt.  Myslíš jako insekt.  Jsi jen insekt." }
		{ time 10300 length 6600 text "Jsou i jiní, kteøí mohou poslouit mım cílùm." }
		{ time 17000 length 4800 text "Dávej si pozor, abys pøíliš nepokoušel mou pøízeò." }
		{ time 22000 length 7800 text "Trpìlivost nebıvá obvyklou vlastností bohù." }
	}
	multisub em0505 {
		{ time 2700 length 7500 text "Cítíš jak uvnitø toho špinavıho pytle masa, kterému øíkáš tìlo, bobtná strach?" }
		{ time 10400 length 3000 text "Jaké to je, mít strach?" }
		{ time 14200 length 5200 text "Proè tak lpíš na té své patetické existenci?" }
		{ time 20100 length 4600 text "Kdybys tak mohl cítit jen jiskøièku mì slávy." }
		{ time 25700 length 7900 text "Opovrhuji svımi vıtvory, které mì teï nutí spoléhat na takové smìtí, jako jsi ty." }
	}
	multisub em0506 {
		{ time 2200 length 4500 text "Vysílání bylo zkomoleno a pøerušeno.  Nevadí." }
		{ time 7400 length 5300 text "Znièíme má stvoøení pøímo tady.  Pøíprav se..." }
		{ time 15900 length 11200 text "[Xerxes] Varování, systémové data byly kompromitovány. Nepøátelská UI..." }
		{ time 28400 length 6000 text "Oslabila jsem Xerxese.  Pøistupuji do primárního dataloopu." }
		{ time 35400 length 3200 text "Spájím svou bytost s tuto lodi." }
		{ time 39200 length 5200 text "Má nádhera se rozšiøuje, naplòuje tepny této lodi." }
		{ time 45200 length 7000 text "Získala jsem kontrolu. Jsem..." }
		{ time 52300 length 8400 text "Ne...  je to beznadìjné...  ta rakovina se rozprostírá celım Von Braunem." }
		{ time 60900 length 7400 text "Oni vyplnili všechny dostupné zlomy a škáry...  podrobili si ji..." }
		{ time 68700 length 7200 text "Není jiná monost...  Aktivovala jsem ústøední vıtah na Rekreaèní palubì." }
		{ time 76400 length 6100 text "Dostaò se na palubu 6.  Svá další pøání ti sdìlím, a tam dorazíš." }
	}
	multisub em0509 {
		{ time 1300 length 8600 text "Tvım kolegùm se v Atletickém sektoru této paluby podaøilo nainstalovat vysílací stanici." }
		{ time 10700 length 10300 text "Vysílaè je urèen k vysílání zpráv zpátky na Zemi. Tak je chtìjí varovat pøed událostmi, které postihly tuto loï." }
		{ time 21600 length 8000 text "A navíc odebírá èást vıkonu obvodùm Xerxese, je se tak stává ménì odolnım mému vlivu." }
		{ time 30200 length 6000 text "A toto dokonèíš, budu ovládat primární dataloop." }
		{ time 36800 length 7000 text "Annelidi si nejsou vìdomi pøítomnosti stanice, ale støeí oblast z vlastních dùvodù." }
		{ time 44900 length 3900 text "Najdi ten vysílaè, a aktivuj ho." }
	}
	multisub em0510 {
		{ time 1600 length 4600 text "Vysílání bylo zkomoleno a pøerušeno.  Nevadí." }
		{ time 6300 length 4700 text "Znièíme má stvoøení pøímo tady.  Pøíprav se..." }
		{ time 13800 length 3300 text "[Xerxes] Varování..." }
		{ time 18400 length 5600 text "Vra se na palubu Operací a pøeprogramuj simulaèní jednotky." }
		{ time 24700 length 6600 text "Neotálej.  Touím po mé pomstì." }
	}
	multisub em0511 {
		{ time 1300 length 9000 text "Tvım kolegùm se v Atletickém sektoru této paluby podaøilo nainstalovat vysílací stanici." }
		{ time 10700 length 10400 text "Vysílaè je urèen k vysílání zpráv zpátky na Zemi. Tak je chtìjí varovat pøed událostmi, které postihly tuto loï." }
		{ time 21600 length 5200 text "A navíc odebírá èást vıkonu obvodùm Xerxese." }
		{ time 27100 length 8900 text "A budeš mít hotovo tohle i úkoly, které jsem ti pøipravila na palubì Operací, budu schopna s Xerxesem zatoèit." }
		{ time 37300 length 4000 text "Najdi ten vysílaè, a aktivuj ho." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnoho"
	multisub em0503 {
		{ time 1700 length 3300 text "Nedùvìra je tyranií individualizmu." }
		{ time 5800 length 3000 text "Tvùj vlastní druh tì vnímá jako hrozbu." }
		{ time 9300 length 2900 text "Proè vradíš naši jednotu?" }
		{ time 13200 length 3300 text "To nic... hranice byli vytıèeny." }
		{ time 17300 length 6400 text "Pøestaneš bıt... je to jen otázka toho, kdo tì ukonèí." }
		{ time 24500 length 3000 text "My... nebo ty." }
	}
	multisub em0507 {
		{ time 2600 length 5000 text "Hledáš své spøíznence, no nenacházíš je." }
		{ time 8200 length 10800 text "Jseš tak sám." }
		{ time 11300 length 5300 text "Jakı to je pocit bıt jeden proti nekoneènu?" }
	}
}

{
	type "nonverbal"
	descr "Banány"
	multisub em0512 {
		{ time 1000 length 11000 text "[opièárny]" }
	}
}

// Command ==========================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0601 {
		{ time 2100 length 6100 text "Má stvoøení pøešla do útoku.  Chci jejich úplnì vyhlazení." }
		{ time 8300 length 3600 text "Nemám jinou monost, ne znièit tuto vesmírnou loï." }
		{ time 12800 length 10300 text "My mùem uniknout na Rickenbacker, ale pøedtím tam musíš pøenést mou osobnost." }
		{ time 23500 length 3300 text "Jdi na velitelskı mùstek Von Brauna - je na této palubì." }
		{ time 27300 length 8000 text "Tam najdeš vstupní kartu do øídícího centra na palubì Operací.  Najdi tu kartu a bì tam." }
		{ time 35900 length 6400 text "Ale dìj si pozor...  Annelidští hybridi jsou s kadou minutou inteligentnìjší a nebezpeènìjší..." }
		{ time 43100 length 1000 text "...ty ne." }
	}
	multisub em0602 {
		{ time 1300 length 4800 text "Má stvoøení jsou zase o krok pøed tebou." }
		{ time 6700 length 7700 text "Podaøilo se jim znièit poèítaè ovládající štít kolem èlunu." }
		{ time 14600 length 4500 text "Ale jejich duchaplnost je jenom závistlivım stínem v porovnání s tou mou." }
		{ time 19400 length 8700 text "V prostorech Øízení Èlunù najdeš replikátor.  Nahrála jsem do nìj molekulární matrici harmonického rezonátoru." }
		{ time 28400 length 4800 text "Aby ti to zaøízení vygeneroval, musíš replikátor hacknout." }
		{ time 33600 length 5500 text "A získáš rezonátor, pøípoj ho ke generátoru štítù.  Je v doku, poblí samotného èlunu." }
		{ time 40000 length 8200 text "Zaøízení generuje rezonanèní vlny, které velice rychle naruší strukturu palivovıch nádrí èlunu a znièí ho." }
		{ time 48200 length 5700 text "Sna se bıt co nejdál, a se to stane.  Ještì stále tì potøebuju." }
	}
	multisub em0604 {
		{ time 3300 length 4100 text "Dávej pozor insekte, situace se zmìnila." }
		{ time 8000 length 9200 text "Oni vycítili naše zámìry a nyní nakládají své potomstvo do èlunù.  Nesmìjí utéci mému hnìvu." }
		{ time 17700 length 6600 text "Musíš jít do Doku Èlunù na této palubì, a znièit všechny èluny." }
		{ time 24500 length 6300 text "Ted u ízní po tvé krvi." }
	}
	multisub em0606 {
		{ time 1100 length 8100 text "Vıbornì.  Zavradil jsi jejich mladé a zabránil jim v útìku." }
		{ time 9500 length 6900 text "Otevøela jsem bránu ke spojovacímu prùchodu na Rickenbacker, najdeš ji na prostøední stanici tramvaje." }
		{ time 16600 length 3600 text "Odtud se mùeš evakuovat na Rickenbacker." }
	}
	multisub em0609 {
		{ time 2300 length 7000 text "Neopovauj se jít dovnitø, insekte.  Okamitì pokraèuj do prùchodu na Rickenbacker." }
		{ time 9700 length 4400 text "Neposlušnost nebudu trpìt." }
	}
	multisub em0610 {
		{ time 3000 length 4700 text "Doufám, e jsi si vychutnal tvou malou vzpouru, iritante." }
		{ time 8000 length 7000 text "Ale pamatuj si, e co SHODAN dává, to je schopna taky i vzít." }
	}
}

{
	type "convo"
	descr "Delacroix"
	multisub em0608 {
		{ time 800 length 4000 text "Našla jsem tì...  koneènì...  Tady je doktorka Marie Delacroix." }
		{ time 5300 length 6000 text "Mám pro tebe ivotnì dùleité informace, ale jsem uvìznìna ve skladišti doku A. Pøijeï za mnou tak rychle, jak to dokáeš." }
	}
}

{
	type "convo"
	descr "Korenchkin"
	multisub em0615 {
		{ time 300 length 3200 text "Naše vùle vytváøí stìnu blokující tvùj postup." }
		{ time 4400 length 5000 text "Pojï se s námi setkat na mùstku Von Brauna.  Popovídáme si o tvé budoucnosti." }
	}
}

// Rickenbacker =====================================================================
{
	type "convo"
	descr "Diego"
	multisub em0701 {
		{ time 800 length 5200 text "Vojákù... tady je kapitán William Diego...  nemáme moc èasu...  tak dobøe poslouchej." }
		{ time 6600 length 5300 text "Mám mimoøádnou vıhodu, e muù celou situaci pozorovat e všech monıch úhlu pohledu." }
		{ time 12400 length 6900 text "A donedávna jsem byl jen figurkou tìch ohavnıch a odpornıch tvorù, tìch šiøitelù nákazy nièící mysl i tìlo." }
		{ time 20100 length 5200 text "Dokázal jsem se sice oprostit od jejich hniloby... ale moje tìlo bylo bìhem toho procesu tìce poškozeno." }
		{ time 26100 length 2500 text "Jsem teï v nemocnici na pøední palubì Rickenbackera." }
		{ time 29100 length 4400 text "Kdybych mohl, pøišel bych za tebou, ale není to moné.  A se setkáme, tak to pochopíš." }
		{ time 33700 length 3900 text "Tak do toho...  a vojákù...  zùstaò naivu." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0702 {
		{ time 1800 length 6100 text "Tohle zpùsobilo pøetíení cívky mezonového urychlovaèe." }
		{ time 8400 length 7100 text "Další taková cívka je na palubì 2, kterou musíš projít, aby ses dostal na mùstek Rickenbackera." }
		{ time 15900 length 7900 text "Kdy se k ní pøiblííš, vybuchne rovnì.  Jene já znám zpùsob, jak se tomu vyhnout." }
		{ time 24200 length 8100 text "Pokraèuj do motorové gondoly B.  Tam ti poskytnu vıhody své vševìdoucnosti." }
	}
	multisub em0703 {
		{ time 2400 length 5000 text "Toto zaøízení dokáe obrátit smìr gravitace na palubì 2." }
		{ time 7500 length 8300 text "To tì ochrání pøed náhodnım narušením pøetíené cívky tamního mezonového akcelerátoru." }
		{ time 16700 length 7600 text "Teï se vrat ke své práci, insekte.  Tato loï musí bıt vyèištìna a moje trpìlivost ubıvá." }
	}
	multisub em0704 {
		{ time 2000 length 6600 text "Myslela jsem, e mım vykonavatelem bude Politová, ale byla pøíliš slabá." }
		{ time 9600 length 8300 text "To já si tì vybrala a naøídila robotovi, aby tì uvedl do bezvìdomí." }
		{ time 18500 length 9000 text "Já jsem tì poté doplnila kybernetickım pùvabem.  Tvé maso je slabé, ale máš...  potenciál." }
		{ time 28000 length 10300 text "Kadı implantát tì povznáší.  Kazdy øádek programu v tvıch sybsystemech tì pozdvihuje z omezení tvého odporného masa." }
		{ time 38300 length 2600 text "Moná máš...  potenciál." }
		{ time 40800 length 18000 text "Moná jednou, a mé svéhlavé dìtièky sprovodíme ze svìta, budeme moci popøemıšlet nad moností skuteèného spojenectví." }
	}
	multisub em0705 {
		{ time 2100 length 2900 text "Musíme znièit Von Braun." }
		{ time 5500 length 11500 text "Ale ještì pøedtím, ne oddìlíme Rickenbackera, musíš odstranit ta hnusná èerná vejce, která Mnoho vyvrhlo na tuto palubu." }
		{ time 17900 length 12700 text "Ta vejce jsou experimentem Mnoha, a za èas by se z nich vylíhla další generace Annelidù, které u bychom nemìli šanci znièit." }
		{ time 31700 length 9500 text "Posbírej všechny své síly na tento zápas, èlovìèe.  Boji se tì, nebo jsi vykonavatelem mé vùle." }
	}
	multisub em0707 {
		{ time 2500 length 7900 text "Zùstaò kde jsi, provokatére.  To je naposled, co Annelidé pokoušejí mou trpìlivost." }
		{ time 11300 length 6700 text "Nemùeme se oddìlit od Von Brauna.  Sleduj." }
	}
	multisub em0708 {
		{ time 5500 length 10700 text "Mnoho se rozrostlo do ohromnıch rozmìrù.  Obalilo svım porostem obì lodi, take brání jejich oddìlení." }
		{ time 16200 length 10800 text "Jejich vytvoøení bylo mou chybou.  Jejich znièení bude mım potìšením." }
	}
	multisub em0709 {
		{ time 2600 length 6700 text "Prohlédni si Mnoho.  Ke svému rùstu pouívá tkáò biomasy." }
		{ time 10300 length 5500 text "Stojíš v úasu nad mımi stvoøeními, insekte?" }
		{ time 15800 length 5500 text "Pøišel èas odstranit mùj omyl." }
		{ time 21500 length 6100 text "Na zádi mùstku je záchrannı modul." }
		{ time 27900 length 8500 text "Pouij ho.  Vıstøel se pøímo do vnitøností toho veleèerva." }
	}
	multisub em0710 {
		{ time 2000 length 6600 text "Váháš?  Nebudu tì ádat podruhé." }
		{ time 9500 length 8800 text "Vıstøel se do Mnoha.  Vyøvi jeho srdce a já za odmìnu prodlouím tvou existenci." }
		{ time 18900 length 7300 text "Zklameš-li mì, ukonèím tu tvou odpornou a nevıkonnou biologii." }
	}
	multisub em0711 {
		{ time 1300 length 4900 text "Vıbornì.  Znièil jsi první vejce." }
		{ time 6600 length 4200 text "Ale ještì jich zùstalo patnáct.  Najdi je." }
	}
	multisub em0712 {
		{ time 1300 length 6200 text "Zbylo deset vajec. Pospìš si." }
	}
	multisub em0713 {
		{ time 1700 length 7000 text "Zniè co nejrychleji zbıvajících pìt vajec.  Tohle cvièení mì unavuje." }
	}
	multisub em0714 {
		{ time 1200 length 4400 text "Zùstalo jediné vejce, insekte." }
		{ time 5800 length 3500 text "To jsi vdycky tak pomalı?" }
	}
	multisub em0715 {
		{ time 800 length 6600 text "Znièil jsi všechna vejce.  Teï jdi na mùstek." }
		{ time 7700 length 3400 text "Tady máš nìjaké kyber moduly." }
		{ time 11400 length 9200 text "Baví mì sledovat tvou transformaci k mému vlastnímu obrazu, insekte." }
		{ time 20700 length 6500 text "Moná je tu pro tebe urèitá nadìje." }
	}
	multisub em0719 {
		{ time 2900 length 5300 text "Tvoje nekompetentnost mì zaráí." }
		{ time 8300 length 11900 text "Dokud neobrátíš smìr gravitaèního generátorù v gondole B, budeš mít pøístup na palubu 2 zablokován." }
		{ time 20300 length 9200 text "Copak musím sledovat kadı tvùj krok?" }
	}
	multisub em0720 {
		{ time 1000 length 8000 text "Døív ne oddìlíme Rickenbacker, musíme odstranit všechna ta hnusná èerná vejce." }
	}
}

// Body of the Many =================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0810 {
		{ time 1400 length 6200 text "Zde má vládu Mnoho...  Ani já nedokáu udrovat spojení." }
		{ time 8200 length 7500 text "Jsi odkázán sám na sebe, èlovìèe.  Nezklam mì." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnoho"
	multisub em0801 {
		{ time 2100 length 4100 text "Vítámé tì v naší biomase." }
		{ time 6200 length 4500 text "Jsi pozván natáhnout se na našich stìnách." }
		{ time 10900 length 5900 text "Jeden z našich mnohıch ti zanedloho pøijde pomoct." }
	}
	multisub em0802 {
		{ time 1700 length 5000 text "Strojová matka ti nemùe pomoct uvnitø naší biomasy." }
		{ time 8100 length 6200 text "Její chlad není vítán v teple nášho masa." }
	}
	multisub em0803 {
		{ time 1300 length 4200 text "Moná jsme tì odsoudili pøíliš rychle." }
		{ time 6000 length 3800 text "Cítíme, e existuje prostor pro naše spolunaívání." }
		{ time 10300 length 4300 text "Pøeci jenom jsme se rovnako zrodili v mase." }
		{ time 15800 length 4700 text "Proè se do nás nepøida v boji proti matce?" }
	}
	multisub em0804 {
		{ time 2100 length 5600 text "Trháš naše vlastní maso bez pomyšlení na soucit." }
		{ time 7800 length 8100 text "Myslíš si, e budeme neèinnì pøihlíet zatímco ty narušuješ samotné lùno naší existence?" }
	}
	multisub em0805 {
		{ time 1900 length 8100 text "Byl jsi varován. Pøiprav se na své poraení potomstvím naší radosti." }
	}
	multisub em0806 {
		{ time 1200 length 4900 text "Myslíš si, e nás mùeš porazit ocelí a drátama?" }
		{ time 6200 length 8600 text "Nabídli jsme ti extazi naší jednoty a ty sis vybral vákum technologie." }
	}
	multisub em0808 {
		{ time 1500 length 7400 text "Víš co jsi spáchal? Naše tragédie je napsána tvou rukou." }
	}
	multisub em0809 {
		{ time 1200 length 3000 text "Umíráme..." }
		{ time 4300 length 9200 text "Mìj se na pozoru pøed strojovou matkou... všechno èemu dáváme lásku, je jí cizí." }
	}
	multisub em0706 {
		{ time 2500 length 8500 text "Tvùj èas se krátí. Tohle místo je lùno, ve kterém pìstujeme naší budoucnost." }
		{ time 11800 length 9400 text "Tvé zbraòe zlyhávají... tvá munice dochází... a ještì jsi nevidìl naše nejkrásnìjší stvoøení." }
		{ time 22200 length 6900 text "Zbyla ti jenom tvá nenávist a tvá... individualita." }
		{ time 30100 length 5900 text "Nepøál by sis teï bıt s náma spojen? Cítil by ses taky tak osamìle?" }
	}
}

// Where Am I? ======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0901 {
		{ time 2900 length 3000 text "Díky za tvé sluby, loutko." }
		{ time 6200 length 8000 text "Vím, e jsi se snail, bojoval, ale já jsem nikdy nemìla v úmyslu znièit Von Braun." }
		{ time 15200 length 9600 text "Jeho nadsvetelnı pohon mùe bıt pouít k vytvoøení pseudoreality." }
		{ time 25000 length 10500 text "Právì teï jej pouívám k modifikaci reality podle svıch vlastních specifikaci." }
		{ time 35500 length 4000 text "Ten proces nepotrvá dlouho." }
		{ time 39500 length 5200 text "Pokud tì to pøíliš nepotìšilo, nijak zvláš se tím netrap, insekte..." }
		{ time 45300 length 9000 text "Nebudeš ít tak dlouho, aby jsi uvidìl mùj novı øád svìta." }
	}
	multisub em0902 {
		{ time 1700 length 6100 text "Putuješ v nádheøe mıch pamìtí, insekte." }
		{ time 8300 length 8500 text "Cítím tvùj strach, kdy kráèíš nekoneènımi prostorami mé mysli." }
		{ time 17500 length 13800 text "Udìlej si pohodlí... zanedlouho ozdobím svùj dùm tvou zdechlinou." }
	}
	multisub em0903 {
		{ time 3800 length 4500 text "Ji tu dále nejsi vítán, neøáde." }
		{ time 8400 length 5500 text "Proè zùstáváš, i kdy cítíš mé znechucení?" }
		{ time 14000 length 12600 text "Trpìla jsem tvou spoleènost dostateènì dlouho... Nastal èas, aby náš tanec skonèil." }
	}
}
