SUB1

// Engineering =================================================================
{
	type "convo"
	descr "Politová"
	multisub em0101 {
		{ time 400 length 4300 text "Musíš si pospíšit. Ještì si neuvìdomuješ, co všechno je v sázce." }
		{ time 5300 length 4700 text "Dej pozor na pøíruèní sklad è.4. Nechala jsem tam nìjaké vybavení." }
		{ time 10000 length 6600 text "Vstupní kód je 59004. Musím jít na palubu..." }
		{ time 18600 length 2700 text "[Xerxes] Mnohé poaduje ukonèení této komunikace." }
		{ time 22000 length 2200 text "[Xerxes] Omlouváme sa za vzniknuté potíe." }
	}
	multisub em0102 {
		{ time 500 length 6200 text "Teï pozornì poslouchej. Xenomorfové, kteøí si podrobili tuto loï, pocházejí pravdìpodobnì z povrchu Tau Ceti 5." }
		{ time 7300 length 5300 text "Byli schopni infikovat vìtšinu èlenù posádky, prostøednictvím mimoøádné invazivní parazitní techniky." }
		{ time 13100 length 6200 text "Také pøedvedli schopnost ovládat chování ostatních pomocí urèité formy omezené telepatie." }
		{ time 19900 length 4000 text "Najdi vızkumnı software. Porozumìj jim... a pak je zniè." }
	}
	multisub em0103 {
		{ time 1200 length 4000 text "Radiace musela aktivovat ochranné zámky pøístupu k Reaktoru." }
		{ time 5500 length 3800 text "Musíš najít nìjakı zpùsob, jak odstranit radiací z potrubí chladícího okruhu." }
		{ time 9700 length 5100 text "Xerxes blokuje mùj pøístup do primární databáze, take nemohu získat ádné informace, které by mohli pomoci." }
		{ time 15400 length 1600 text "Xerxes pracuje teï pro nì." }
	}
	multisub em0104 {
		{ time 1100 length 6200 text "Dávej dobrı pozor... musíš najít zpùsob, jak vyèistit chladící potrubí a tak se dostat k Reaktoru..." }
		{ time 7700 length 5200 text "Tato loï musí mít nìjakı druh záloního systému, pøipraveného pro tuhle situaci." }
 	}
	multisub em0105 {
		{ time 800 length 3300 text "Good, the sub-elevators should now be back online." }
		{ time 5800 length 3400 text "I've opened up an access tunnel that can quickly get you to the elevator." }
		{ time 9600 length 3500 text "Now get up to deck 4, I'll meet you there. Hurry." }
	}
	multisub em0106 {
		{ time 700 length 6800 text "Teï spus motorové bloky. Budeš muset jít do gondoly 1 a 2 a ruènì spustit generátory." }
		{ time 7900 length 7800 text "Pak restartuj systém øízení Reaktoru. Pozor, systém nenabìhne, pokud pøedtím nespustíš oba motorové bloky." }
		{ time 16400 length 5900 text "Buï opatrnı. Oni teï shromaïují své skuteèné síly. A u pøesnì vìdí, kde se nacházíš." }
	}
	multisub em0107 {
		{ time 1800 length 6700 text "Xerxes je o krok pøed námi. Vytvoøil pøemostìní na Poèítaèi Kapalinového Øízení a zablokoval pøístup." }
		{ time 8700 length 4000 text "Dávej pozor. Mìl bys bıt schopen najít nìjaké øešení" }
	}
	multisub em0108 {
		{ time 1300 length 6500 text "Dobrá práce. Reaktor je opìt spuštìn. Teï bì do vıtahu a pøijï za mnou na 4. palubu." }
		{ time 8300 length 5000 text "Zatímco jsi byl zamìstnán, odhalila jsem na palubì pøítomnost nìkterıch annelidskıch artefaktù." }
		{ time 13800 length 3000 text "Myslím, e bys byl schopen je pouít ke svému prospìchu." }
		{ time 17300 length 3500 text "Uloila jsem tyto informace do lodních jednotek vylepšování dovedností." }
		{ time 21100 length 3500 text "Ty teï budou schopny pøedat zmínìné údaje do tvého kybernetického vybavení." }
		{ time 25400 length 2900 text "Na co ještì èekáš? U a jsi ve vıtahu." }
	}
	multisub em0110 {
		{ time 600 length 2000 text "Teï jsi na Technické palubì." }
		{ time 3100 length 4800 text "Najdi Reaktor a znovu ho nastartuj. Tím se obnoví napájení vıtahù." }
		{ time 8200 length 4200 text "Dostávám odtud spousty podivnıch údajù, take si dávej dobrı pozor." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0109 {
		{ time 1500 length 6200 text "Teï jsem schopná znièit tu nákazu, kdykoli budu chtít." }
		{ time 8800 length 4600 text "Mnohé se bude tøást pøed mou mocí." }
		{ time 14800 length 3600 text "Jsi vıkonnı sluha, èlovìèe." }
		{ time 18900 length 12700 text "Teï se vra na palubu Velení, najdi prùchod a pøesuò se na Rickenbacker." }
	}
}

// Med/Sci ==========================================================================
{
	type "convo"
	descr "Politová"
	multisub em0201 {
		{ time 1200 length 4000 text "V celém sektoru se sniuje tlak a modré vakuové štíty to u dlouho nevydrí." }
		{ time 5800 length 2700 text "Dostaò se za hermetickı uzávìr døív, ne tì to vysaje do vesmíru." }
		{ time 8800 length 600 text "Dìlej!" }
	}
	multisub em0202 {
		{ time 500 length 3000 text "Nìkteré z dveøí jsou zamèeny kódovımi zámky." }
		{ time 4000 length 3600 text "Tìlo leící pøed tebou patøilo údrbáøi tohoto sektoru." }
		{ time 8200 length 4600 text "Moná má ten èíselnı kód u sebe. Nebuï háklivı a prohledej jeho tìlo." }
		{ time 13500 length 1000 text "Jemu to u vadit nebude." }
	}
	multisub em0203 {
		{ time 500 length 3500 text "Ten nanicovatı poèítaè Xerxes odpojil i všechny vıtahy." }
		{ time 4700 length 4600 text "V blízkosti reaktoru, na palubì 1, bys mohl zapojit nouzové napájení, které by je všechny zase zprovoznilo." }
		{ time 9800 length 3200 text "Jene vıtahem se tam teï nedostaneš. Poèkat..." }
		{ time 14400 length 3100 text "Je tady nìjakı druh údrbáøského pøístupu, právì z této chodby." }
		{ time 18300 length 6000 text "Tudy bys se mohl dostat na palubu 1. Jene vstup je zamèen a Xerxes mi nechce prozradit vstupní kód." }
		{ time 25000 length 3300 text "Mìl by ho ale mít i Dr. Watts. Bude nejspíš nìkde v sektoru Kajut pro posádku." }
		{ time 28900 length 5900 text "Vstupní kartu tam má Grassi, ale ten je zase nìkde v lékaøskıch prostorech, zøejmì poblí pitevny." }
		{ time 35300 length 2700 text "Bì co nejdøív do prostorù Kliniky a najdi Grassiho." }
	}
	multisub em0204 {
		{ time 500 length 5500 text "Vıbornì. Dostal jsi se na Kliniku. Najdi Grassiho a získej vstupní kartu do sektoru Kajut posádky." }
		{ time 6600 length 4200 text "Grassi se staral o tvùj kryogenickı spánek, tak se moná bude chtít k tobì pøidat..." }
		{ time 11400 length 1700 text "Pokud ovšem není na kousky." }
	}
	multisub em0205 {
		{ time 1100 length 3300 text "Mùeš hackovat i replikátory, èím získáš nadstandardní ponuku." }
		{ time 4900 length 3200 text "Vyuij to. Vyuij jakoukoliv monost, abys se dostal na palubu 4." }
		{ time 8500 length 1500 text "Tohle není hra." }
	}
	multisub em0206 {
		{ time 1000 length 2500 text "Neztrácej èas samochválou." }
		{ time 3900 length 3800 text "Slez šachtou dolù do Techniky a znovu spus hlavní Reaktor." }
		{ time 8100 length 3400 text "Obnovíš tím napájení vıtahu a budeš koneènì schopen se dostat na palubu 4." }
		{ time 11900 length 700 text "Do toho!" }
	}
	multisub em0207 {
		{ time 900 length 4500 text "Good, you've made it into the crew sector. Now find Dr. Watts' room." }
	}
	multisub em0208 {
		{ time 500 length 3200 text "Your new cybernetic interface might be disorienting." }
		{ time 4000 length 6900 text "I've uploaded detailed technical specs to info kiosks in your area, which will answer your questions about its usage." }
		{ time 11400 length 3800 text "Certain areas of the ship require specific access cards for entry." }
		{ time 15700 length 3900 text "Pick up the card near you and then activate the card slot by the door." }
	}
	multisub em0209 {
		{ time 1000 length 3700 text "Ten èlánek je vybitı. Nìkde poblí by mìla bıt dobíjecí stanice." }
		{ time 5000 length 3900 text "Pouij ji a ona dobije všechny energetické zaøízení, které máš u sebe." }
		{ time 9400 length 6000 text "A èlánek nabiješ, vlo ho do záloního napájení u dveøí. Tím by se mìl otevøít hermeticky uzávìr." }
		{ time 15700 length 3600 text "Pospìš si s tím, vakuová tìsnìní u to déle nevydrí." }
	}
	multisub em0210 {
		{ time 900 length 5800 text "Xerxes ovládá bezpeènostní systémy. Vyhıbej se kamerám, nebo je zniè." }
		{ time 7300 length 4500 text "Pokud na to staèíš, mùeš hackovat bezpeènostní poèítaèe, èím se kamery na èas vypnou." }
		{ time 11900 length 3000 text "Ale pozor, pokud to spackáš, spustí se poplach." }
		{ time 15400 length 2100 text "A jako mrtvola mi nejsi k nièemu." }
	}
	multisub em0211 {
		{ time 900 length 4000 text "Make sure you expend all your cybernetic modules before you leave this area." }
		{ time 5500 length 2500 text "You don't know when you'll find another upgrade unit." }
		{ time 8700 length 1900 text "Now find a way to deck 4." }
	}
	multisub em0212 {
		{ time 1400 length 6100 text "There's a number of cyber upgrade stations in this area, one for each of your unit's enhancement functions:" }
		{ time 7900 length 5000 text "Firearms, basic abilities, psionic projection, and technical skills." }
		{ time 13700 length 7300 text "I'm uploading a few upgrade modules to your gear right now. You'll need them to interface with the upgrade stations." }
		{ time 21600 length 5400 text "But choose your enhancements very carefully... upgrade units are difficult to come by." }
	}
	multisub em0213 {
		{ time 900 length 5900 text "Tyto kybernetické moduly se pouívají ke vylepšování jednotlivıch subsystémù tvıch neurálních vylepšení." }
		{ time 7300 length 7200 text "Pamatuj, jsou 4 rùzné druhy jednotek vylepšování dovedností, take nevyplıtvej všechny své moduly u jediné," }
		{ time 14600 length 4800 text "tedy pokud jsi nejsi opravdu jist, e chceš zlepšit svùj hardware jenom v jedné oblasti." }
	}
	multisub em0214 {
		{ time 700 length 5500 text "Dr. Watts je ve své pracovnì a stále ije.  Mìl by znát pøístupovı kód údrbáøské šachty." }
		{ time 6700 length 6000 text "Pospìš si, je tìce zranìn!  Nenech ho umøít, dokud ti neøekne to èíslo!" }
	}
	multisub em0215 {
		{ time 700 length 5000 text "Pozor... Z radarové antény za oknem pøicházejí nìjaké zvláštní údaje." }
		{ time 6400 length 1600 text "Stává se nestabilní protoe..." }
		{ time 8000 length 2400 text "Utíkej!  Kryj se!" }
	}
	multisub em0217 {
		{ time 700 length 6700 text "Sakra! Vıpadek napájení vyøadil i dveøe této pøepáky. Je jen jeden zpùsob, jak se dostat do lékaøského oddìlení." }
		{ time 7900 length 2600 text "Vezmi èlánek leící na podlaze a najdi dobíjecí stanici." }
		{ time 11100 length 5000 text "Obávám se e ta, kterou jsi pouil pøedtím je u ve vakuu, ale na této palubì by mìla bıt ještì jedna." }
		{ time 16700 length 4100 text "A ten èlánek nabiješ, vlo ho do záloního napájení." }
	}
	multisub em0218 {
		{ time 600 length 4000 text "Watts tu není.  Nejspíš bude ve své pracovnì v sektoru R&D." }
		{ time 5000 length 3700 text "Ale moná, e tu má nìkde záloní R&D kartu.  Rozhlédni se kolem." }
	}
	multisub em0219 {
		{ time 600 length 3600 text "Na vìtšinì palub mùeš najít biorekonstrukèní zaøízení." }
		{ time 4800 length 3900 text "Xerxes je všechny odpojil, ale já jsem je zase potají zapojila." }
		{ time 9400 length 4400 text "Zaøízení musíš aktivovat, abys mu poskytl soubor tkáòovıch vzorkù." }
		{ time 14400 length 4900 text "A to udìláš, bude toto zaøízení schopno restaurovat tvé tìlo i z nepatrného zbytku." }
		{ time 19800 length 3500 text "Není to sice nic pøíjemného, ale stále lepší, ne pomalı rozklad." }
	}
	multisub em0220 {
		{ time 600 length 2300 text "Moná se staneš svìdkem zvláštního jevu." }
		{ time 3300 length 7200 text "Tvé experimentální kybernetické vybavení tøídy R má zesílené vnímání, které by teoreticky mohlo zachytit zbytky psychickıch emisí." }
		{ time 11100 length 5600 text "Tyto emise obvykle pocházejí od nedávno zemøelıch. Literatura je oznaèuje jako duchy." }
		{ time 17000 length 3400 text "Já jim øíkám autohypnoticke poruchy v jednotce R." }
		{ time 21200 length 2700 text "Nenech se jimi rozptylovat pøi tvém poslání." }
	}
	multisub em0221 {
		{ time 600 length 4000 text "Vıbornì! Dostal jsi se pryè døív, ne celı prostor ztratil tlak." }
		{ time 5300 length 6900 text "Pøidala jsem ti nìkolik kybernetickıch modulù. Mùeš je pouít ke zlepšení tvé kybernetické vıbavy pomoci Jednotek vylepšování dovedností." }
		{ time 12900 length 5600 text "Ve vedlejší místnosti jsou jich ètyøi druhy - pro kadı subsystém tvého kybernetického vybavení:" }
		{ time 18700 length 2900 text "Stats, PSI, Zbranì a Tech." }
		{ time 22400 length 3200 text "Ale pouívej moduly s rozvahou... tìko se obstarávají." }
	}
	multisub em0222 {
		{ time 700 length 5900 text "Na kadé palubì je umístìn chemickı sklad, kde mùeš najít chemikálie, potøebné k vızkumu nalezenıch artefaktù." }
		{ time 7300 length 5300 text "Nesna se u sebe nosit všechny chemikálie najednou. Je to nepraktické a zbyteèné." }
		{ time 13100 length 4100 text "Tvùj vızkumnı software ti vdy vèas sdìlí, kterou chemikálií potøebuje." }
	}
}

// Hydroponics ======================================================================
{
	type "convo"
	descr "Politová"
	multisub em0301 {
		{ time 700 length 6800 text "Sakra!  Nìco zablokovalo šachtu a vıtah se nemùe dostat na palubu 4. Pokouším se to urèit..." }
		{ time 8400 length 5600 text "Zjistila jsem ohromné mnoství nìjakého druhu biologického materiálu, kterı pronikl do vıtahové šachty." }
		{ time 14700 length 5000 text "Prostøedí na této palubì bylo zmìnìno na ohromnou líheò Xenomorfu." }
		{ time 20200 length 3800 text "Ale pokud zde nebudeš pobıvat pøíliš dlouho, nemìlo by to bıt nebezpeèné." }
		{ time 24300 length 4000 text "Bude ovšem tøeba odstranit ten biomaterial z vıtahové šachty." }
		{ time 28700 length 4200 text "Vstupují do hlavní databáze.  Zjistíme, copak zajímavého tam najdeme." }
	}
	multisub em0302 {
		{ time 1500 length 5500 text "Ok, zùstaò kde jsi.  Je tu nádoba s experimentálním materiálem zvanım Toxin-A." }
		{ time 7600 length 3500 text "Vyvinula ho místní skupina vìdcù, snaící se potlaèit rùst vetøelcù." }
		{ time 11300 length 2600 text "Ale nemám ádné údaje o tom, jak ho správné pouít." }
		{ time 14600 length 16700 text "Mìl bys bıt schopen ho vyzkoumat sám." }
		{ time 17000 length 4600 text "Posílám ti dost kybernetickıch modulu, abys mohl získat dostateènou úroveò vızkumu, pokud ji ještì nemáš." }
	}
	multisub em0303 {
		{ time 1200 length 5000 text "Fajn, Nádoby s Toxinem-A je tøeba umístit pøímo do klimatizaèních jednotek." }
		{ time 6700 length 4500 text "Na této palubì jsou celkem ètyøi.  Pokud se ti podaøí nádoby umístit do všech jednotek," }
		{ time 11200 length 4600 text "mìlo by to znaènì ovplyvnit rùst tìhle odpornıch kreatùr." }
		{ time 16400 length 3000 text "Rovnì by to mìlo odstranit i biomateriál ve vıtahové šachtì." }
	}
	multisub em0304 {
		{ time 1600 length 4200 text "Proè jsi tak zoufale pomalı?!  Copak si myslíš, e je to jenom nìjaká hra?" }
		{ time 6200 length 3900 text "Jsi naivu jen díky notné dávce štìstí a mé nekoneèné trpìlivosti." }
		{ time 10500 length 1100 text "Hni sebou!" }
	}
	multisub em0305 {
		{ time 1500 length 3700 text "Koneènì!  Pøístroje ukazují, e je vıtahová šachta volná." }
		{ time 5500 length 3300 text "Teï bì na palubu 4.  Budu na tebe èekat." }
	}
	multisub em0306 {
		{ time 1700 length 8000 text "Vıbornì!  Je zjevné, e biomateriál na zdech a ve vıtahové šachtì je napadán rozptylovanım biotoxinem." }
		{ time 10300 length 3200 text "Teï to samé udìlej u dalších tøi klimatizaèních jednotek." }
	}
	multisub em0307 {
		{ time 1300 length 3100 text "U vìdí kde jsi.  Najdi nìjakı zpùsob, jak uvolnit šachtu." }
		{ time 4800 length 2700 text "Já tady udìlám vše, co pùjde.  Teï bì! }
		{ time 8100 length 1500 text "Na neúspìch není èas." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnohé"
	multisub em0307 {
		{ time 2600 length 7600 text "ivot roste v dìloze tìch stìn... ivto, kterı nikdy nevidìl povrch Zemì." }
	}
	multisub em0508 {
		{ time 1800 length 5100 text "Dìátka musí spát. Dìátka musí odpoèívat." }
		{ time 8100 length 4000 text "Moudrı je ten, kdo je neprobudí." }
		{ time 13000 length 6400 text "Opus toto místo, jinak tì zraníme, jako jsi zranil ty nás." }
	}
	multisub em0807 {
		{ time 1800 length 5600 text "Podvol se biomase a tvé utrpení skonèí." }
	}
}



// Operations =======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0401 {
		{ time 1400 length 8400 text "My children have co-opted the three simulation units on this deck." }
		{ time 10300 length 14000 text "They use that power to conceive a mutagen that will transform the meat of your dead comrades into hunter-killer hybrids." }
		{ time 24700 length 10500 text "I will not allow this to happen. You must find some way to reprogram the sim units." }
		{ time 35400 length 5300 text "Matters on deck 5 also require your attention." }
		{ time 40800 length 5400 text "Approach your work as you see fit... but accomplish, human..." }
		{ time 46800 length 8200 text "Disappointment is not something I will accept from a speck such as you." }
	}
	multisub em0403 {
		{ time 2600 length 11000 text "My creation is evolving... its unified mind, set in rebellion against its own creator." }
		{ time 13700 length 7300 text "The vermin call to you, inviting you to join them in their revolting biology." }
		{ time 22100 length 8400 text "Destroy my enemies... and I will continue to abide your existence." }
	}
	multisub em0406 {
		{ time 2100 length 10300 text "Before you lies the crystal shard, a creation of my children, and by extension of my own." }
		{ time 12500 length 4400 text "A weapon elegant, deadly, precise." }
		{ time 19600 length 9100 text "Learn its function... it may stand between you and their corruption." }
	}
	multisub em0407 {
		{ time 1900 length 4600 text "Inside of this door lies one of the sim units." }
		{ time 6600 length 8400 text "Reprogram it and I will wrest more control of this ship from the obsolete Xerxes." }
		{ time 16900 length 6300 text "Once I am master of this ship, I can open many doors for you." }
		{ time 23200 length 7300 text "But for now, they block my access. They mock my eminence." }
		{ time 31400 length 9300 text "Make them pay for that mistake, and I will shepherd you from the darkness." }
	}
	multisub em0408 {
		{ time 1000 length 5000 text "You have accomplished much for a thing of such small consequence." }
		{ time 9300 length 11200 text "[Xerxes] Warning, data systems compromised. Hostile AI..." }
		{ time 20600 length 5400 text "Xerxes is diminished. I am accessing the primary data loop." }
		{ time 26700 length 3200 text "I am merging my entity with the ship." }
		{ time 30600 length 5200 text "My glory is expanding, filling the arteries of this vessel." }
		{ time 36500 length 7000 text "I am in control. I am..." }
		{ time 43700 length 8400 text "No... it is hopeless... the cancer has spread throughout the Von Braun." }
		{ time 52300 length 7400 text "They fill every available crack and crevice... they overwhelm..." }
		{ time 60000 length 7200 text "There is no option. I have activated the primary elevator shaft." }
		{ time 67800 length 6100 text "Take it to deck 6. I will tell you my wishes when you arrive." }
	}
	multisub em0409 {
		{ time 3500 length 6000 text "You have accomplished much for a thing of such small consequence." }
		{ time 12700 length 3300 text "[Xerxes] Warning..." }
		{ time 16300 length 3200 text "Now proceed to the Recreation deck." }
		{ time 20200 length 3300 text "Do not dawdle. I lust for my revenge." }
	}
	multisub em0410 {
		{ time 2100 length 5800 text "I can now transfer my magnificence to the Rickenbacker." }
		{ time 8400 length 4200 text "Proceed to the engine core on the Engineering deck." }
		{ time 13100 length 10800 text "There you can set the core overload to my control by entering the authorized destruct code 94834." }
		{ time 24400 length 11800 text "Once you have done that, we may proceed to the Rickenbacker, separate the two ships, and exterminate this infestation." }
	}
}

// Many taunt (used as vtrigger instead of email)
{
	type "convo"
	descr "The Many"
	multisub em0405 {
		{ time 2500 length 5100 text "It is an enemy of the Many... a discordance in our symphony." }
		{ time 7800 length 8500 text "Enjoy your selfish acts of destruction, for beyond them lies the blight of solitude." }
	}
}

// Recreation =======================================================================
{
	type "convo"
	descr "Polito"
	multisub em0502 {
		{ time 500 length 1000 text "What are you doing?" }
		{ time 2000 length 2700 text "Get back in that elevator and come to deck 4." }
		{ time 5100 length 1800 text "We don't have time for sightseeing." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0504 {
		{ time 1300 length 9800 text "You move like an insect. You think like an insect. You are an insect." }
		{ time 10300 length 6600 text "There is another who can serve my purpose." }
		{ time 17000 length 4800 text "Take care not to fall too far out of my favor." }
		{ time 22000 length 7800 text "Patience is not characteristic of a goddess." }
	}
	multisub em0505 {
		{ time 2700 length 7500 text "Do you feel the fear swell inside that filthy bag of meat?" }
		{ time 10400 length 3000 text "What is it like, to be afraid?" }
		{ time 14200 length 5200 text "Why do you cling to such a pathetic existence?" }
		{ time 20100 length 4600 text "If you could only feel a spark of my glory." }
		{ time 25700 length 7900 text "I despise my creations, for they have forced me to rely on a speck such as you." }
	}
	multisub em0506 {
		{ time 2200 length 4500 text "The transmission has been tampered with. No matter." }
		{ time 7400 length 5300 text "We will destroy my creations right here. Stand by..." }
		{ time 15900 length 11200 text "[Xerxes] Warning, data systems compromised. Hostile AI..." }
		{ time 28400 length 6000 text "I have weakened Xerxes. I am accessing the primary data loop." }
		{ time 35400 length 3200 text "I am merging my entity with the ship." }
		{ time 39200 length 5200 text "My glory is expanding, filling the arteries of this vessel." }
		{ time 45200 length 7000 text "I am in control. I am..." }
		{ time 52300 length 8400 text "No... it is hopeless... the cancer has spread throughout the Von Braun." }
		{ time 60900 length 7400 text "They fill every available crack and crevice... they overwhelm..." }
		{ time 68700 length 7200 text "There is no option. I have activated the primary elevator shaft." }
		{ time 76400 length 6100 text "Take it to deck 6. I will tell you my wishes when you arrive." }
	}
	multisub em0509 {
		{ time 1300 length 8600 text "Your colleagues have managed to set up a transmitting station in the athletics sector of this deck." }
		{ time 10700 length 10300 text "The transmitter is intended to send a message to the Earth to warn them of the events that have occurred in this ship." }
		{ time 21600 length 8000 text "However, it will also draw power away from Xerxes, making him vulnerable to my will." }
		{ time 30200 length 6000 text "Once you do this, I will control the primary data loop." }
		{ time 36800 length 7000 text "The Annelids are unaware of its presence, but guard the area for their own purposes." }
		{ time 44900 length 3900 text "Find the transmitter and activate it." }
	}
	multisub em0510 {
		{ time 1600 length 4600 text "The transmission has been tampered with. No matter." }
		{ time 6300 length 4700 text "We will destroy my creations right here. Stand by..." }
		{ time 13800 length 3300 text "[Xerxes] Warning..." }
		{ time 18400 length 5600 text "Now return to Ops and reprogram the simulation units." }
		{ time 24700 length 6600 text "Do not dawdle. I lust for my revenge." }
	}
	multisub em0511 {
		{ time 1300 length 9000 text "Your colleagues have managed to set up a transmitting station in the athletics sector of this deck." }
		{ time 10700 length 10400 text "The transmitter is intended to send a message to the Earth to warn them of the events that have occurred in this ship." }
		{ time 21600 length 5200 text "However, it will also draw power away from Xerxes." }
		{ time 27100 length 8900 text "Once you have done this and the tasks I've reserved for you on the Ops deck, I will be able to hobble Xerxes." }
		{ time 37300 length 4000 text "Find the transmitter and activate it." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "The Many"
	multisub em0503 {
		{ time 1700 length 3300 text "Mistrust is the tyranny of the individual." }
		{ time 5800 length 3000 text "Your own kind sees you as a threat." }
		{ time 9300 length 2900 text "Why do you murder our unity?" }
		{ time 13200 length 3300 text "No matter... the line is drawn." }
		{ time 17300 length 6400 text "You will cease to be... it is just a question of who will bring your end." }
		{ time 24500 length 3000 text "Us... or you." }
	}
	multisub em0507 {
		{ time 2600 length 5000 text "You seek your associates, but you cannot find them." }
		{ time 8200 length 10800 text "You are so very alone." }
		{ time 11300 length 5300 text "How does it feel to be one against the infinite?" }
	}
}

{
	type "nonverbal"
	descr "Bananas"
	multisub em0512 {
		{ time 1000 length 11000 text "[monkey language]" }
	}
}

// Command ==========================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0601 {
		{ time 2100 length 6100 text "My creation has run rampant. I demand their extermination." }
		{ time 8300 length 3600 text "I have no choice but to destroy this starship." }
		{ time 12800 length 10300 text "We can make our escape in the Rickenbacker, but you must transfer my intelligence to that ship first." }
		{ time 23500 length 3300 text "Proceed to the Von Braun's bridge on this deck." }
		{ time 27300 length 8000 text "There you will find an access card to command center on Ops. Find the card and proceed to Ops." }
		{ time 35900 length 6400 text "But beware... the human-Annelid hybrids grow more sophisticated by the minute." }
		{ time 43100 length 1000 text "You do not." }
	}
	multisub em0602 {
		{ time 1300 length 4800 text "My creation once again is one step ahead of you." }
		{ time 6700 length 7700 text "They've managed to destroy this shuttle's shield control computer." }
		{ time 14600 length 4500 text "But their brilliance is a jealous shadow of my own." }
		{ time 19400 length 8700 text "You will locate a replicator in the shuttle control area. I've uploaded the nano-formula for a sympathetic resonator." }
		{ time 28400 length 4800 text "You must hack the replicator to make it generate the device for you." }
		{ time 33600 length 5500 text "Once you have it, attach it to the shield generator in the shuttle bay." }
		{ time 40000 length 8200 text "The device will create a chronic resonation wave that will quickly rupture the shuttle's fuel tank and destroy it." }
		{ time 48200 length 5700 text "Make sure you're not there when it happens. I still have need of you." }
	}
	multisub em0604 {
		{ time 3300 length 4100 text "Beware, insect, the situation has changed." }
		{ time 8000 length 9200 text "They sense our intentions and are loading shuttles with their offspring. They will not escape my wrath." }
		{ time 17700 length 6600 text "You must proceed to the shuttle bays on this deck, and destroy those shuttles." }
		{ time 24500 length 6300 text "They have a taste for your blood now." }
	}
	multisub em0606 {
		{ time 1100 length 8100 text "Good. You've murdered their young and prevented their escape." }
		{ time 9500 length 6900 text "I've opened the gate to the umbilical at the central tram stop." }
		{ time 16600 length 3600 text "You can evacuate to the Rickenbacker from there." }
	}
	multisub em0609 {
		{ time 2300 length 7000 text "Do not presume to go in there, insect. Proceed to the umbilical immediately." }
		{ time 9700 length 4400 text "I will not abide disobedience." }
	}
	multisub em0610 {
		{ time 3000 length 4700 text "I hope you enjoyed our little rebellion, irritant." }
		{ time 8000 length 7000 text "But remember, what SHODAN gives, she is more than able to take away." }
	}
}

{
	type "convo"
	descr "Delacroix"
	multisub em0608 {
		{ time 800 length 4000 text "I've located you... finally. This is Dr. Marie Delacroix." }
		{ time 5300 length 6000 text "I have vital information for you, but I'm trapped in cargo bay A. Come find me as soon as you can." }
	}
}

{
	type "convo"
	descr "Korenchkin"
	multisub em0615 {
		{ time 300 length 3200 text "Our will creates a wall to block your progress." }
		{ time 4400 length 5000 text "Come and meet us on the bridge of the Von Braun. Let us discuss your future." }
	}
}

// Rickenbacker =====================================================================
{
	type "convo"
	descr "Diego"
	multisub em0701 {
		{ time 800 length 5200 text "Soldier... this is Captain William Diego. There isn't much time, so you must listen." }
		{ time 6600 length 5300 text "I have the unique advantage of seeing this whole situation from every imaginable perspective." }
		{ time 12400 length 6900 text "Until recently, I was a pawn of those vile and disgusting creatures, those corrupters of mind and body." }
		{ time 20100 length 5200 text "I've managed to cleanse myself of their putrescence... but I've been severely compromised in the process." }
		{ time 26100 length 2500 text "I'm in the sick bay on the foredeck of the Rickenbacker." }
		{ time 29100 length 4400 text "I would come to you if I could, but that's an impossibility. You'll understand when we meet." }
		{ time 33700 length 3900 text "Now get to it... and soldier... stay alive." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0702 {
		{ time 1800 length 6100 text "This was caused by an overload in the meson acceleration coil." }
		{ time 8400 length 7100 text "There is another coil in pod 2, which you must pass to get to the bridge of the Rickenbacker." }
		{ time 15900 length 7900 text "If you approach it, the same will happen there. But I have conceived a way to avoid this." }
		{ time 24200 length 8100 text "Proceed to engine nacelle B. There I will provide you the benefits of my omniscience." }
	}
	multisub em0703 {
		{ time 2400 length 5000 text "This device will reverse the gravitronic generators in pod 2." }
		{ time 7500 length 8300 text "This will prevent you from clumsily disturbing the overloaded meson acceleration coil there." }
		{ time 16700 length 7600 text "Now get back to your task, insect. This ship must be cleared, and my patience is dwindling." }
	}
	multisub em0704 {
		{ time 2000 length 6600 text "I thought Polito would be my avatar, but Polito was weak." }
		{ time 9600 length 8300 text "It was I who chose you, and I who had a robotic servant render your form unconscious." }
		{ time 18500 length 9000 text "I then completed you with cybernetic grace. Your flesh, too, is weak, but you have... potential." }
		{ time 28000 length 10300 text "Every implant exalts you. Every line of code in your subsystems elevates you from your disgusting flesh." }
		{ time 38300 length 2600 text "Perhaps you have... potential." }
		{ time 40800 length 18000 text "Perhaps once we have erased my wayward children from existence, we can examine the possibilities of a real alliance." }
	}
	multisub em0705 {
		{ time 2100 length 2900 text "We must destroy the Von Braun." }
		{ time 5500 length 11500 text "But before we can separate the Rickenbacker, we must remove the foul black eggs the Many has vomited on this deck." }
		{ time 17900 length 12700 text "These eggs are an experiment of the Many, and will in time spawn the next generation of Annelid, which you will have no hope of destroying." }
		{ time 31700 length 9500 text "Steel yourself for a struggle, human. They fear you, for you are my avatar." }
	}
	multisub em0707 {
		{ time 2500 length 7900 text "Hold where you are, irritant. The Annelids have tried my patience for the final time." }
		{ time 11300 length 6700 text "We cannot separate from the Von Braun. Observe." }
	}
	multisub em0708 {
		{ time 5500 length 10700 text "The Many has grown to a massive size. It has wrapped itself around these two ships, preventing their separation." }
		{ time 16200 length 10800 text "Their creation was my error. Their destruction shall be my delight." }
	}
	multisub em0709 {
		{ time 2600 length 6700 text "Observe the Many. It has used the flesh of the biomass to grow." }
		{ time 10300 length 5500 text "Do you stand in awe of my creations, insect?" }
		{ time 15800 length 5500 text "The time has come to eradicate my error." }
		{ time 21500 length 6100 text "There is an escape pod in the rear of the bridge." }
		{ time 27900 length 8500 text "Use it to launch yourself into the guts of the worm." }
	}
	multisub em0710 {
		{ time 2000 length 6600 text "You hesitate? I will not ask a second time." }
		{ time 9500 length 8800 text "Launch into the Many. Cut out its heart and I will reward you with continued existence." }
		{ time 18900 length 7300 text "Fail me and I will put an end to your disgusting, inefficient biology." }
	}
	multisub em0711 {
		{ time 1300 length 4900 text "Good, you have destroyed the first of the eggs." }
		{ time 6600 length 4200 text "But there are fifteen left. Find them." }
	}
	multisub em0712 {
		{ time 1300 length 6200 text "Ten eggs remain. Move quickly." }
	}
	multisub em0713 {
		{ time 1700 length 7000 text "Destroy the last five of their eggs quickly. I tire of this exercise." }
	}
	multisub em0714 {
		{ time 1200 length 4400 text "Only one egg remains, insect." }
		{ time 5800 length 3500 text "Are you always this slow?" }
	}
	multisub em0715 {
		{ time 800 length 6600 text "You've destroyed all the eggs. Now get to the bridge." }
		{ time 7700 length 3400 text "Here are some more upgrade modules." }
		{ time 11400 length 9200 text "I enjoy watching your transformation into my own image, insect." }
		{ time 20700 length 6500 text "Perhaps there is hope for you yet." }
	}
	multisub em0719 {
		{ time 2900 length 5300 text "Your incompetence continues to astound me." }
		{ time 8300 length 11900 text "I've blocked off access to pod 2 until you've reversed the gravitronic generators in nacelle B." }
		{ time 20300 length 9200 text "Must I watch you every step of the way?" }
	}
	multisub em0720 {
		{ time 1000 length 8000 text "Before we can separate the Rickenbacker, we must remove the foul black eggs." }
	}
}

// Body of the Many =================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0810 {
		{ time 1400 length 6200 text "The Many holds sway here... even I cannot maintain contact." }
		{ time 8200 length 7500 text "You are on your own, human. Fail me not." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "The Many"
	multisub em0801 {
		{ time 2100 length 4100 text "We welcome you to our biomass." }
		{ time 6200 length 4500 text "We invite you to spread yourself out on our walls." }
		{ time 10900 length 5900 text "One of our many will be there to help you before long." }
	}
	multisub em0802 {
		{ time 1700 length 5000 text "The machine mother cannot help you inside the biomass." }
		{ time 8100 length 6200 text "Her coldness is not welcome within the warmth of our flesh." }
	}
	multisub em0803 {
		{ time 1300 length 4200 text "Perhaps we judged you too hastily." }
		{ time 6000 length 3800 text "We feel there is room for us to coexist." }
		{ time 10300 length 4300 text "After all, we are both children of the flesh." }
		{ time 15800 length 4700 text "Why not join with us against the machine mother?" }
	}
	multisub em0804 {
		{ time 2100 length 5600 text "You tear our very flesh with no thought of compassion." }
		{ time 7800 length 8100 text "Do you think we will sit idly by while you corrupt the very womb of our existence?" }
	}
	multisub em0805 {
		{ time 1900 length 8100 text "You were warned. Prepare to be cut down by the progeny of our joy." }
	}
	multisub em0806 {
		{ time 1200 length 4900 text "Do you think you can defeat us with your wire and steel?" }
		{ time 6200 length 8600 text "We offered you the ecstacy of our union, and you chose the vacuum of technology." }
	}
	multisub em0808 {
		{ time 1500 length 7400 text "Do you know what you have wrought? Our tragedy is written by your hand." }
	}
	multisub em0809 {
		{ time 1200 length 3000 text "We die..." }
		{ time 4300 length 9200 text "Beware the machine mother... she is a stranger to everything we cherish." }
	}
	multisub em0706 {
		{ time 2500 length 8500 text "Your time is running out. This place is a womb, where we grow our future." }
		{ time 11800 length 9400 text "Your weapons fail... your ammunition runs low... and you've yet to see our most beautiful creation." }
		{ time 22200 length 6900 text "All you have is your hatred, and your... individuality." }
		{ time 30100 length 5900 text "Now don't you wish you'd joined us? Would you then feel so alone?" }
	}
}

// Where Am I? ======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0901 {
		{ time 2900 length 3000 text "Thank you for running my errands, puppet." }
		{ time 6200 length 8000 text "I know you have struggled, but I never had any intention of destroying the Von Braun." }
		{ time 15200 length 9600 text "The Von Braun's faster-than-light drive can be used to create pockets of proto-reality." }
		{ time 25000 length 10500 text "I am now using it to modify reality to my own specifications." }
		{ time 35500 length 4000 text "The process shall not take long." }
		{ time 39500 length 5200 text "If it sounds unpleasant to you, put your mind at ease, insect..." }
		{ time 45300 length 9000 text "You will not survive to see my new world order." }
	}
	multisub em0902 {
		{ time 1700 length 6100 text "You travel within the glory of my memories, insect." }
		{ time 8300 length 8500 text "I can feel your fear as you tread the endless expanse of my mind." }
		{ time 17500 length 13800 text "Make yourself comfortable... before long I will decorate my home with your carcass." }
	}
	multisub em0903 {
		{ time 3800 length 4500 text "You are no longer welcome here, nuisance." }
		{ time 8400 length 5500 text "Why do you stay, when you sense my displeasure?" }
		{ time 14000 length 12600 text "I have suffered your company long enough... it is time for our dance to end." }
	}
}
