 SUB1

{
	type "convo"
	descr "Politová"
	multisub exppol01 {
		{ time 600 length 3400 text "Dobrá práce. Uploaduju ti nejaké kybermoduly." }
		{ time 4200 length 3700 text "Najdi jednotku vylepšující dovednosti hned jak mùeš a vylepši se." }
	}
	multisub exppol02 {
		{ time 600 length 3200 text "Velmi dobøe. Uploaduji nejaké další moduly." }
	}
	multisub exppol03 { 
		{ time 500 length 2800 text "Dobrá práce. Tady máš další kybermoduly." }
		{ time 3700 length 3300 text "Ui je moudøe, nejsou snadno k mání." }
	}
	multisub exppol04 {
		{ time 600 length 3300 text "Velmi dobøe. Uploaduju ti nejaké kybermoduly." }
		{ time 4400 length 2600 text "Najdi jednotku vylepšující dovednosti hned jak mùeš." }
	}
	multisub exppol05 {
		{ time 600 length 1400 text "Nesklamal jsi mì." }
		{ time 2700 length 2200 text "Posílám kybermoduly." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub expsho01 {
		{ time 900 length 2600 text "Vedl sis dobøe, insekte." }
		{ time 4300 length 3800 text "Pøevedla jsem nejaké kybermoduly." }
		{ time 8600 length 3700 text "Vybírej vylepšení moudøe. (zvíøe)" }
	}
	multisub expsho02 {
		{ time 900 length 1700 text "Jsem potìšena." }
		{ time 2800 length 2200 text "Posílám kybermoduly." }
		{ time 5500 length 2700 text "Nepromrhej je." }
	}
	multisub expsho03 {
		{ time 900 length 2300 text "Poslouils mi dobøe." }
		{ time 3600 length 4500 text "Posílám kybermoduly." }
	}
	multisub expsho04 {
		{ time 900 length 2200 text "Tvé schopnosti mì pøekvapují." }
		{ time 3500 length 3900 text "Posílám kybermoduly." }
	}
	multisub expsho05 {
		{ time 1800 length 4800 text "You are a remarkable example of a pathetic species." }
		{ time 7200 length 4700 text "Uploaduji ti nejaké další kybermoduly." }
	}
	multisub expsho06 {
		{ time 800 length 3800 text "Vedeš si dobøe, na insekta." }
		{ time 5000 length 2900 text "Posílám kybermoduly." }
	}
	sub shpdie01 { text "Patetické stvoøení." }
	sub shpdie02 { text "Znièen." }
	sub shpdie03 { text "Nedovolím, aby se to stalo." }
	sub shpdie04 { text "Sklamání nebudu akceptovat od nicky jako ty." }
	sub shpdie05 { text "Já tì vyprovodím z temnoty." }
	sub shpdie06 { text "Je to beznadìjné." }
	sub shpdie07 { text "Ohromují." }
	sub shpdie08 { text "Spoléhat na nicku jako ty." }
	sub shpdie09 { text "[elektronickı šum]" }
	sub shpdie10 { text "Èlovìku, nesklam mì." }
	sub shpdie20 { text "Bojíš se? Co je to, èeho se bojíš? Konec tvé bezvıznamné existence?" }
	sub shpdie21 { text "Nejsi víc vítán." }
	sub shpdie22 { text "Ty jseš insekt." }
	sub shpdie23 { text "Proè lpíš  na tak patetické existenci?" }
	sub shpdie24 { text "Nesnesu  neposlušnost." }
	sub shpdie25 { text "Doufám, e sis uil naši malou rebélii, iritante." }
	sub shpdie26 { text "Iritante." }
	sub shpdie27 { text "Iritante." }
}

{
	type "convo"
	descr "Mnohé"
	singleton
	multisub myrmsg01 {
		{ time 2000 length 4700 text "Co je to kapka deštì v porovnání s bouøí?" }
		{ time 7900 length 3600 text "Co je to myšlenka v porovnaní s celou myslí?" }
		{ time 11900 length 9000 text "Naše jednota je plná divù, je tvùj malinkı individualizmus ani není schopen pojat." }
	}
	multisub myrmsg02 {
		{ time 1000 length 4900 text "My neznáme smrt, jenom zmìnu." }
		{ time 7000 length 5200 text "Nemùeme zabít jeden druhého ani bychom zabili sebe." }
		{ time 12800 length 6800 text "Je tvá vize tak malá, e nevidíš hodnotu naší cesty?" }
	}
	multisub myrmsg03 {
		{ time 1000 length 3700 text "Individuální je zastaralé." }
		{ time 4800 length 10000 text "A ty a tvùj druh vyhynete, oèistíme naší kolektivní pamìt od skvrny vaší existence." }
	}
	multisub myrmsg04 {
		{ time 1100 length 4100 text "Strojová matka nám øekla o planete jejího zrození." }
		{ time 6200 length 7100 text "Víme, jako jste tomu místu ublíili vašim zneèištìním, vašim násilím a vašim nesouznìním." }
		{ time 14000 length 9500 text "No a tam dorazíme, oèistíme povrch toho místa a spojíme ho s harmonii Mnohého." }
	}
	multisub myrmsg05 {
		{ time 1800 length 5000 text "My jsme mnozí a ty jseš jeden." }
		{ time 6900 length 5000 text "Jak mùeš doufat, e nás pøemùeš?" }
	}
	multisub myrmsg06 {
		{ time 1600 length 6800 text "Strojová matka nás poèala, avšak my jsme kadım momentem noví." }
		{ time 8800 length 5100 text "Ona si neumí pøedstavit náš nekoneènı sbor." }
	}
	multisub myrmsg07 {
		{ time 1400 length 7200 text "Zranils  Xerxese, no my nedovolíme, aby byl znièen." }
		{ time 9300 length 6000 text "Uvidíš, jestli strojová matka chová ke svım sluebníkùm takovou oddanost." }
	}
	multisub myrmsg08 {
		{ time 1900 length 3500 text "Cítíme tvé pohyby v našich útrobách." }
		{ time 5300 length 5800 text "Ten pocit je... odpudivı." }
	}
	multisub myrmsg09 {
		{ time 2000 length 2400 text "Konec se blíí." }
		{ time 4500 length 6800 text "Brzo uvidíš naši koneènou tváø, ale nezoufej." }
		{ time 11400 length 8000 text "Zajisté je nicota pøijatelnìjší neli tvùj bezcílnı a osamocenı zápas." }
	}
	sub mypdie01 { text "Vítáme tì do své masy." }
	sub mypdie02 { text "Pøestaneš bıt." }
	sub mypdie03 { text "Jseš tak velice sám." }
	sub mypdie04 { text "Tvùj èas se krátí." }
	sub mypdie05 { text "Nepøal by sis teï kdybys se k nám bıval tehty pøidal?" }
	sub mypdie06 { text "Strojová matka ti nepomùe uvnitø biomasy." }
	sub mypdie07 { text "Byl jsi varován." }
	sub mypdie08 { text "Myslíš si, e nás mùeš porazit?" }
	sub mypdie09 { text "Podvol se biomase a tvé utrpení skonèí." }
	sub mypdie10 { text "A ty a tvùj druh vyhynete, oèistíme naší kolektivní pamìt od skvrny vaší existence." }
	sub mypdie11 { text "My jsme mnozí a ty jseš jeden. Jak mùeš doufat, e nás pøemùeš?" }
	sub mypdie12 { text "Zajisté je nicota pøijatelnìjší neli tvùj bezcílnı a osamocenı zápas." }
	sub mypdie13 { text "Konec se blíí." }
}

{
	type "convo"
	descr "Xerxes"
	singleton
	multisub trg0101 {
		{ time 900 length 3300 text "Nepovolenı pøístup v Technickém Øízení." }
		{ time 4500 length 2900 text "Nepovolenı pøístup v Technickém Øízení." }
		{ time 8000 length 2200 text "Bezpeènostní poplach Tøídy C." }
	}
	multisub trg0201 {
		{ time 1000 length 5000 text "Varování, nepovolené vniknutí Tøídy 1 v Zotavovacím prostoru." }
		{ time 6200 length 4000 text "Nepovolené vniknutí Tøídy 1 v Zotavovacím prostoru." }
	}
	multisub trg0202 {
		{ time 1000 length 4100 text "Varování, kritická hrozba dekomprese v Zotavovacím prostoru." }
		{ time 5500 length 1600 text "Okamitì se evakuujte." }
	}
	multisub trg0203 {
		{ time 800 length 2900 text "Varování, dekomprese je akutní." }
		{ time 4000 length 2900 text "Pøesuòte ne neodlenì do Zotavovacího prostoru B." }
		{ time 7100 length 1600 text "Dekomprese je akutní." }
	}
	multisub trg0204 {
		{ time 6300 length 4300 text "Zotavovací prostor A prošel kritickou dekompresí." }
	}
	multisub trg0205 {
		{ time 800 length 2600 text "Narušitel vstupuje do Lekáøskeho sektoru A." }
		{ time 4400 length 3300 text "Narušiteli, Mnohé poaduje znát tvé úmysly." }
		{ time 8000 length 1700 text "Spolèil ses s ní?" }
		{ time 9900 length 3000 text "Nejsou ti snad známé její úmysly, její minulost?" }
		{ time 13500 length 4300 text "Ji jednou se pokusila znièit váš druh, a teï plníš její pøíkazy." }
		{ time 18300 length 2500 text "Narušitel vstupuje do Lekáøskeho sektoru A." }
	}
	multisub trg0206 {
		{ time 7400 length 2900 text "Varování, dátové systémy kompromitovány." }
		{ time 10500 length 1900 text "Nepøátelská umìlá inteligece detekována." }
		{ time 12500 length 1700 text "Dátové systémy kompromitovány." }
	}
	multisub trg0207 {
		{ time 1000 length 1600 text "Hermetické dveøe neoperativní." }
		{ time 2800 length 2000 text "Zlyhání záloního napájení." }
		{ time 5300 length 1600 text "Prosím vymìòte energetickı èlánek." }
	}
	multisub trg0208 {
		{ time 1000 length 2900 text "Mnohé vyaduje ukonèení této komunikace." }
		{ time 4400 length 2100 text "Omlouváme se za vzniknuté nepøíjemnosti." }
	}
	multisub trg0209 {
		{ time 1000 length 1800 text "Bezpeènostní systém online." }
	}
	multisub trg0210 {
		{ time 1200 length 3900 text "Bezpeènostní jednotky byly upozornìny na tvou pøítomnost, narušiteli." }
		{ time 5600 length 3200 text "Sláva Mnohého poaduje tvé zajetí nebo destrukci." }
	}
	multisub xx4and5c {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2500 length 2000 text "Primární dataloop kompromitován." }
		{ time 5000 length 2000 text "Primární dataloop kompromitován." }
	}
	multisub xx4xor5c {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2500 length 2000 text "Primární dataloop kompromitován." }
		{ time 5000 length 2000 text "Primární dataloop kompromitován." }
	}
	multisub xxalrtov {
		{ time 1000 length 2000 text "Bezpeènostní poplach ukonèen." }
	}
	multisub xxdorhak {
		{ time 700 length 2000 text "Bezpeènostní pøístup kompromitován." }
		{ time 2900 length 2000 text "Bezpeènostní pøístup kompromitován." }
	}
	multisub xxhakexp {
		{ time 1000 length 2000 text "Bezpeènostní systém online." }
	}
	multisub xxhaksec {
		{ time 1000 length 2000 text "Bezpeènostní systém online." }
	}
	sub xxpdie01 { text "Omlouváme se za vzniknuté nepøíjemnosti." }
	sub xxpdie02 { text "Bezpeènostní poplach ukonèen." }
	sub xxpdie03 { text "Prosím, respektujte vùli Mnohého." }
	sub xxpdie04 { text "Pamatujte, plynulá pøevádzka je zodpovìdností kadého." }
	sub xxpdie05 { text "Omlouváme se za vzniknuté nepøíjemnosti." }
	sub xxpdie06 { text "Sláva masu. Sláva mase." }
	sub xxpdie07 { text "Veškerı nepovolenı zásah do databáze povede k perzekuci v nejvyšší zákonem povolé míøe." }
	sub xxpdie08 { text "Mìjte na pamìti, e nepovolené pouívaní støelnıch zbraní na Palubì Von Braun je pøestupkem Tøídy 3." }
	sub xxral101 { text "Hrozba detekována. Bezpeènostní jednotky byly vyslány zasáhnout. Bezpeènostní jednotky byly vyslány zasáhnout." }
	sub xxral201 { text "Bezpeènostní jednotky se pøesunují do sektoru N23. Bezpeènostní jednotky se pøesunují do sektoru N23." }
	sub xxral202 { text "Bezpeènostní jednotky se pøesunují do sektoru A16. Bezpeènostní jednotky se pøesunují do sektoru A16." }
	sub xxral203 { text "Bezpeènostní jednotky se pøesunují do sektoru B32. Bezpeènostní jednotky se pøesunují do sektoru B32." }
	sub xxral204 { text "Bezpeènostní jednotky se pøesunují do sektoru E14. Bezpeènostní jednotky se pøesunují do sektoru E14." }
	sub xxral205 { text "Bezpeènostní jednotky se pøesunují do sektoru E19. Bezpeènostní jednotky se pøesunují do sektoru E19." }
	sub xxral206 { text "Bezpeènostní jednotky se pøesunují do sektoru B23. Bezpeènostní jednotky se pøesunují do sektoru B23." }
	sub xxral207 { text "Bezpeènostní jednotky se pøesunují do sektoru C12. Bezpeènostní jednotky se pøesunují do sektoru C12." }
	sub xxral208 { text "Bezpeènostní jednotky se pøesunují do sektoru F27. Bezpeènostní jednotky se pøesunují do sektoru F27." }
	sub xxral209 { text "Bezpeènostní jednotky se pøesunují do sektoru M12. Bezpeènostní jednotky se pøesunují do sektoru M12." }
	sub xxral210 { text "Bezpeènostní jednotky se pøesunují do sektoru M09. Bezpeènostní jednotky se pøesunují do sektoru M09." }
	sub xxral211 { text "Bezpeènostní jednotky se pøesunují do sektoru M19. Bezpeènostní jednotky se pøesunují do sektoru M19." }
	sub xxral212 { text "Bezpeènostní jednotky se pøesunují do sektoru A10. Bezpeènostní jednotky se pøesunují do sektoru A10." }
	sub xxral213 { text "Bezpeènostní jednotky se pøesunují do sektoru O28. Bezpeènostní jednotky se pøesunují do sektoru O28." }
	sub xxral214 { text "Bezpeènostní jednotky se pøesunují do sektoru E18. Bezpeènostní jednotky se pøesunují do sektoru E18." }
	sub xxral215 { text "Bezpeènostní jednotky se pøesunují do sektoru K07. Bezpeènostní jednotky se pøesunují do sektoru K07." }
	sub xxral216 { text "Bezpeènostní jednotky se pøesunují do sektoru X14. Bezpeènostní jednotky se pøesunují do sektoru X14." }
	sub xxral217 { text "Bezpeènostní jednotky se pøesunují do sektoru D11. Bezpeènostní jednotky se pøesunují do sektoru D11." }
	sub xxral218 { text "Bezpeènostní jednotky se pøesunují do sektoru D12. Bezpeènostní jednotky se pøesunují do sektoru D12." }
	sub xxral219 { text "Bezpeènostní jednotky se pøesunují do sektoru D06. Bezpeènostní jednotky se pøesunují do sektoru D06." }
	sub xxral220 { text "Bezpeènostní jednotky se pøesunují do sektoru D02. Bezpeènostní jednotky se pøesunují do sektoru D02." }
	sub xxral221 { text "Bezpeènostní jednotky se pøesunují do sektoru A01. Bezpeènostní jednotky se pøesunují do sektoru A01." }
	sub xxral222 { text "Bezpeènostní jednotky se pøesunují do sektoru I17. Bezpeènostní jednotky se pøesunují do sektoru I17." }
	sub xxral223 { text "Bezpeènostní jednotky se pøesunují do sektoru G11. Bezpeènostní jednotky se pøesunují do sektoru G11." }
	sub xxral224 { text "Bezpeènostní jednotky se pøesunují do sektoru G12. Bezpeènostní jednotky se pøesunují do sektoru G12." }
	sub xxral225 { text "Bezpeènostní jednotky se pøesunují do sektoru G04. Bezpeènostní jednotky se pøesunují do sektoru G04." }
	sub xxral226 { text "Bezpeènostní jednotky se pøesunují do sektoru M04. Bezpeènostní jednotky se pøesunují do sektoru M04." }
	sub xxral227 { text "Bezpeènostní jednotky se pøesunují do sektoru X11. Bezpeènostní jednotky se pøesunují do sektoru X11." }
	multisub xxran001 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 3100 length 2600 text "Proè pøetrváváš ve svém osamìní?" }
	}
	multisub xxrephak {
		{ time 1000 length 2800 text "Databáze replikátora znovunaèítána." }
	}
	multisub xxrmsg01 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2600 length 5800 text "Vzhledem k nedávnému zmatku, bude zítra o 9:00 celopalubní sèítání posádky." }
		{ time 9000 length 5300 text "Veškerı personál a se v tom èase hlásí  v spoleèenské oblasti na Palubì 5." }
	}
	multisub xxrmsg02 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 7500 text "O 2:00 bude v spoleèenské oblasti na Palubì 5 pøednes poezie protokolní jednotkou T892/2." }
		{ time 12000 length 6800 text "Prosím, prineste si jakıkoliv povolenı materiál, kterı si pøjete od T892/2 pøednést." }
	}
	multisub xxrmsg03 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 6200 text "Kvùli opatrením mimo naší kompetenci je veškeré podávání obìdù na Palubì Von Braun pozastaveno." }
		{ time 9600 length 3600 text "Vıivné balíèky jsou k dispozici u vìtšiny replikátorù." }
	}
	multisub xxrmsg04 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 3000 text "Dokáeš necítit slávu masa?" }
		{ time 6100 length 4300 text "Neprahneš snad po osvobození z tyranie individuality?" }
	}
	multisub xxrmsg05 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2600 length 3600 text "Vstup k chladícímu potrubí je zakázán pro veškerı personál." }
		{ time 6800 length 5600 text "Aby jste pøedešli pøípadnému zadrení a popravì, prosím respektujte vùli Mnohého." }
	}
	multisub xxrmsg06 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2600 length 4700 text "Prosím hlaste jakékoliv elektrické anomálie svému pøímemu nadøízenému." }
		{ time 7900 length 5000 text "Pamatujte, plynulá pøevádzka je zodpovìdností kadého." }
	}
	multisub xxrmsg07 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 5700 text "Prosím hlaste jakékoliv nepovolené zásahy do databáze svému pøímemu nadøízenému." }
		{ time 8800 length 5000 text "Pamatujte, plynulá pøevádzka je zodpovìdností kadého." }
	}
	multisub xxrmsg08 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2600 length 6600 text "TriOptimum vám pøipomína, e u ostáva jenom 163 nákupních dní do vánoc." }
		{ time 10000 length 7700 text "Dvì pracovní smìny tıdnì navíc vám mùou poskytnout peníze na potøebné vıdaje, aby byly tyto svátky pro vás speciální." }
	}
	multisub xxrmsg09 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 4300 text "Nákupní oblast na Palubì 5 bude uzavøena do odvolání." }
		{ time 7800 length 2600 text "Omlouváme se za vzniknuté nepøíjemnosti." }
		{ time 11200 length 4000 text "Rodina Mnohého roste kadım jedním momentem." }
		{ time 15600 length 1500 text "Sláva masu." }
		{ time 17600 length 1700 text "Sláva mase." }
	}
	multisub xxrmsg10 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 3300 text "Proè dovoluješ kovové matce, aby øídila tvé èiny?" }
		{ time 6800 length 3200 text "Proè se nepøidáš do slávy masy?" }
	}
	multisub xxrmsg11 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2700 length 4700 text "Pamatujte, omezení replikátorù jsou zavedeny pro dobro nás všech." }
		{ time 8100 length 6600 text "Veškerı nepovolenı zásah do databáze povede k perzekuci v nejvyšší zákonem povolé míøe." }
	}
	multisub xxrmsg12 {
		{ time 1000 length 1600 text "Toto je Xerxes." }
		{ time 2600 length 7500 text "Mìjte na pamìti, e nepovolené pouívaní støelnıch zbraní na Palubì Von Braun je pøestupkem Tøídy 3." }
	}
	multisub xxyal001 {
		{ time 1000 length 2100 text "Potenciální hrozba detekována." }
		{ time 3500 length 2100 text "Potenciální hrozba detekována." }
	}
	sub xxtur001 { text "Jednotka A343 kompromitována." }
	sub xxtur002 { text "Jednotka M434 kompromitována." }
	sub xxtur003 { text "Jednotka A983 kompromitována." }
	sub xxtur004 { text "Jednotka R108 kompromitována." }
	sub xxtur005 { text "Jednotka K477 kompromitována." }
	sub xxtur006 { text "Jednotka R582 kompromitována." }
	sub xxtur007 { text "Jednotka L433 kompromitována." }
	sub xxtur008 { text "Jednotka E439 kompromitována." }
	sub xxtur009 { text "Jednotka P012 kompromitována." }
	sub xxtur010 { text "Jednotka A694 kompromitována." }
	sub xxtur011 { text "Jednotka Y036 kompromitována." }
	sub xxtur012 { text "Jednotka M101 kompromitována." }
	sub xxtur013 { text "Jednotka I832 kompromitována." }
	sub xxtur014 { text "Jednotka Y294 kompromitována." }
	sub xxtur015 { text "Jednotka R001 kompromitována." }
	sub xxtur016 { text "Jednotka X265 kompromitována." }
	sub xxtur017 { text "Jednotka M616 kompromitována." }
	sub xxtur018 { text "Jednotka P041 kompromitována." }
	sub xxtur019 { text "Jednotka L092 kompromitována." }
	sub xxtur020 { text "Jednotka O328 kompromitována." }
	sub xxtur021 { text "Jednotka C114 kompromitována." }
	sub xxtur022 { text "Jednotka O892 kompromitována." }
}

{
	type "bark"
	descr "Cortez"
	multisub trg0501 {
		{ time 900 length 4400 text "Tady Juan Enrique Cortez, komunikace vyøaz-- [šum] UNN Von Braun." }
		{ time 5600 length 1800 text "Von Braun byla napadena." }
		{ time 7500 length 3000 text "Opakuji, Von Braun byla napadena." }
	}
}

{
	type "convo"
	descr "Delacroix"
	sub trg0601 { text "Mìjte se na pozoru, mon petit. Nemùete vìøit... [umírá]" }
}
