SUB1

{
	type "convo"
	descr "Rozhlas"
	singleton

	multisub trg0001 {
		{ time 00 length 3000 text "Vítejte v náborovém zařízení Ramsey Center UNN." }
		{ time 3000 length 2200 text "Dívejte se pod nohy při vystupování z vlaku." }
		{ time 5200 length 4700 text "Gravšachty na konci  chodby vás vyvezou na úroveň ulice s tréninkovým a náborovým centrem." }
		{ time 10000 length 2200 text "Prosím, pokračujte ke gravšachtám." }
	}

	sub trg0002 { text "Vstupte do gravšachty, aby jste vystoupali na úroveň ulice." }
}

{
	type "convo"
	descr "Trenér"

	multisub trg0004 {
		{ time 00 length 3800 text "Než si vyberete svou kariéru, budete se chtít naučit základním schopnostem." }
		{ time 3800 length 2450 text "Nejprve by jste měli jít do centra Základního Výcviku." }
		{ time 6270 length 3700 text "Až budete hotovi se Základním Výcvikem, pokračujte do oblasti s Pokročilým Výcvikem." }
	}

	multisub trg0014 {
		{ time 00 length 4400 text "Pokud jste dokončili základný výcvik, jste připraveni k pokročilým lekcem, které poskytujeme tady." }
		{ time 4500 length 4700 text "Pokročilý výcvik vás obeznámí se třemi klíčovými oblastmi armádní služby--" }
		{ time 9160 length 4000 text "Zbraňový výcvik, Technický výcvik, a Psionický výcvik." }
		{ time 13170 length 3500 text "Vstupte do kyberlinkové budky dle výběru, aby ste zahájili výcvik v dané oblasti." }
		{ time 16800 length 7000 text "Až dokončíte výcvik ve všech třech oblastech, pokračujte přímo do náborového centra, kde si zvolíte a zahájíte svou armádní kariéru." }
	}

	multisub trg0031 {
		{ time 00 length 2000 text "Toto je místo volby, vojáku." }
		{ time 2000 length 3000 text "Tady se přihlásíte do jedného ze tří odvětví armády." }
		{ time 5000 length 3700 text "Jakmile se rozhodnete pro svou kariéru, už není cesty zpět." }
		{ time 8700 length 6100 text "Raketoplán vás vyveze na orbitální vesmírnou stanici UNN, kde dostanete brífing k vaší roční stáži." }
		{ time 15000 length 1000 text "Hodně štěstí." }
	}

	// Basic training

	multisub trg0005 {
		{ time 600 length 4700 text "Vstupte do této kyberlinkové budky, aby jste zahájili základní výcvik, který potřebujete ve službě." }
		{ time 5500 length 3200 text "Uvnitř nadobudnete základní schopnosti potřebné pro začátek." }
	}

	multisub trg0006 {
		{ time 00 length 1000 text "Vítej, nováčku." }
		{ time 1200 length 4900 text "Dokud jsi v našem virtálním výcvikovém kurzu, poskytneme ti simulované kyber-rozhraní." }
		{ time 6370 length 4800 text "Toto výcvikové rozhraní je identické se skutečným kyber-rozhraním armádní třídy." }
	}

	multisub trg0007 {
		{ time 00 length 1800 text "Těd si to skusme." }
		{ time 2100 length 1000 text "Hýbej myší." }
		{ time 3700 length 1700 text "Vidíš jak se tvůj pohled mění, kam se podíváš?" }
		{ time 5900 length 1600 text "To značí, že jsi Střeleckém módu." }
		{ time 8200 length 1000 text "Stiskni klávesu Tab." }
		{ time 10300 length 4500 text "Toto tě přepne do Uživatelského módu, kde můžeš používat myš na interakci s věcmi v rozhraní." }
		{ time 16160 length 7000 text "Otevři svůj primární MFD - neboli multi-funkční displej - klikem na tlačidlo MFD na spodu rozhraní." }
		{ time 24570 length 2800 text "Tato obrazovka ukazuje tvé dovednosti v různych oblastech." }
		{ time 27600 length 3700 text "Až budeš připraven pokračovat, stiskni klávesu Tab pro návrat do Střeleckého módu." }
		{ time 32200 length 2860 text "Skus si přepínat mezi módmi než se ti to dostane do ruky." }
		{ time 35800 length 3500 text "Následuj červenou čáru na zemi k další tréninkové stanici." }
	}

	multisub trg0008 {
		{ time 00 length 5560 text "Používání věcí jako jsou tlačítka nebo počítače, si vyžaduje vycentrovat je na obrazovce a pak na ně kliknout pravým." }
		{ time 5920 length 2380 text "Všechny použitelné věci budou mít kolem názvu lomené závorky." }
		{ time 8910 length 2500 text "Označ tlačítko na sloupě a pak klikni pravým." }
		{ time 11600 length 1500 text "To aktivuje výtah." }
		{ time 13800 length 700 text "Zkus si to." }
		{ time 16300 length 3800 text "Pokud vidíš svůj inventár, znamená to, že jsi v užívatelském módu." }
		{ time 20500 length 2000 text "Stiskni Tab pro návrat do Střeleckého módu." }
	}

	multisub trg0009 {
		{ time 00 length 3800 text "Předměty zvedneš tak, že je vycentruješ na obrazovce klikneš pravým." }
		{ time 3890 length 2930 text "Toto automaticky umístí předmět do tvého inventáře." }
		{ time 7170 length 2800 text "Pro zobrazení inventáře stiskni klávesu Tab." }
		{ time 10150 length 4510 text "Věcmi múže přemísťovať v inventáři levým klikem a táhnutím." }
		{ time 15000 length 5150 text "Předmět upustíš tak, že ho přetáhneš z inventáře do volného 3D prostoru a uvolníš tlačítko." }
	}

	multisub trg0010 {
		{ time 00 length 1600 text "Vidíš tu bednu před sebou?" }
		{ time 1900 length 2900 text "Prohledáš ji tak, že ji vycentruješ na obrazovce klikneš pravým." }
		{ time 5020 length 4120 text "Pokud jsi v užívatelskem módu, jednoduše namiř kurzorem na bednu a klikni pravým." }
		{ time 9440 length 3260 text "Obsah bedny vemeš jednoducho levým klikem na předmět." }
		{ time 12870 length 2840 text "To automaticky přemístí předmět do tvého inventáře." }
		{ time 15980 length 4170 text "Okno obsahu uzavřeš přechodem to Střeleckého módu stiskem klávesy Tab." }
	}

	multisub trg0011 {
		{ time 00 length 2500 text "Teď je čas naučit se skákat a vylézat." }
		{ time 2700 length 2500 text "Vyskočíš jednoduše stiskem mezeríku." }
		{ time 6050 length 3940 text "Na některé povrchy se dá vylézt podržením mezerníku." }
		{ time 10740 length 4410 text "Vylézání ti umožní vyzvednout se nad okraje vyšších míst před tebou." }
		{ time 15690 length 1020 text "Zkus si to." }
	}

	multisub trg0012 {
		{ time 00 length 3300 text "Po řebříku se leze tak, že do něj jenom vkročíš a podíváš se nahoru." }
		{ time 3600 length 2500 text "Tím automaticky začneš šplhat." }
	}

	multisub trg0032 {
		{ time 00 length 2300 text "Předmět před tebou je léčebné sérum." }
		{ time 2500 length 2700 text "Vezmi ho a stiskni Tab pro přechod to Užívateského módu." }
		{ time 5700 length 4300 text "Pravým klikem na léčebné sérum ho použiješ čímž si obnovíš zopár bodů zdraví." }
		{ time 10500 length 4000 text "Tvé body zdraví jsou zobrazeny pruhem v levém dolním rohu rozhraní." }
		{ time 15000 length 3900 text "Mnoho předmetů se dá v inventáři použít pravým klikem na ně." }
	}

	multisub trg0033 {
		{ time 00 length 3600 text "Jeden z nejužitečnějších nástrojů, které máš jako voják je tvé PDA." }
		{ time 4000 length 4000 text "Toto zařízení ukládá audio nahrávky, e-maily a jiné užitečné informace." }
		{ time 8700 length 4000 text "Klikni na ikonu disku naspodu rozhraní pro otevření displeje PDA." }
		{ time 13300 length 3000 text "V současnosti je obsah tvého  PDA prázdný." }
		{ time 16700 length 2300 text "Teď vem audio nahrávku přimo před tebou." }
	}

	multisub trg0013 {
		{ time 600 length 900 text "Vedl sis dobře." }
		{ time 1900 length 6400 text "Pamatuj, pokud je ti nejasné cokoliv z toho, co jsme se učili, můžeš si trénink zopakovat kolikrát budeš chtít." }
	}

	// Weapons training

	multisub trg0015 {
		{ time 650 length 6200 text "Dobrá zelenáči, pokud se chceš naučit používat zbraň, abys vůbec mohl pomyslet na to stát se Mariňákem, pojď dál." }
		{ time 7200 length 1500 text "Sháníme nějaké dobré chlapy." }
	}

	multisub trg0016 {
		{ time 00 length 1400 text "Fajn, že tě máme na palubě." }
		{ time 1700 length 8900 text "Můžeš si všimnout, že uvnitř kyberlinkové budky ti UNN laskavě poskytla virtuální kyber-rozhraní a všechny nasimulované úrovně dovedností, které potřebuješ pro dokončení  tréninku." }
		{ time 10800 length 3400 text "Ale nebuď z toho na větvy. Zmizí jakmile opustíš budku." }
	}

	multisub trg0017 {
		{ time 00 length 2100 text "Teď tě naučíme zacházet se zbraní." }
		{ time 2500 length 4900 text "Vem si pistoli a zásobník ze stola. Zbraň můžeš vytasit dvěma způsoby." }
		{ time 7700 length 5800 text "Otevři inventář, a přetáhni pistoli do políčka pro zbraně napravo od inventáře." }
		{ time 13800 length 4500 text "Pokud je to na tebe příliš pomalé, můžeš použít klávesové skratky. Stiskni 2." }
		{ time 18900 length 3700 text "Pokud se pistole nachází v inventáři, automaticky ji vytasíš." }
		{ time 23000 length 6300 text "Pro přebíjení zásobníků stiskni kláves R nebo klikni na tlačítko Nabít v pravém dolním horu rozhraní." }
		{ time 29700 length 6100 text "Potom co si nabil zbraň, vystřel na atrapu robota levým klikem myši ve Střeleckém módu." }
		{ time 36500 length 3100 text "Všimni si ako z jeho zdraví ubívá, když po něm pálíš." }
	}

	multisub trg0018 {
		{ time 00 length 3500 text "Některé věci se musí nabít energí, než je budeš moct používat." }
		{ time 3900 length 3800 text "Vem laserovou pistoli. A pak použi nabíjecí stanici poblíž." }
		{ time 8100 length 3500 text "Nabíjecí stanice napumpuje šťávu do všech tvých energetických předmětů." }
		{ time 11800 length 2500 text "Zbraně, baterie, na co si zmyslíš." }
	}

	multisub trg0019 {
		{ time 00 length 3600 text "Zbraně nejsou víno. Nejsou lepší čím jsou starší." }
		{ time 3900 length 4700 text "Barevná tečka v pravém dolním rohu rozhraní ti napoví v jaké kondici zbraň je." }
		{ time 8800 length 1900 text "Zelená je dobrá. Červená je špatná." }
		{ time 11200 length 6600 text "Na boj s neduhem opotřebení může voják s dovedností údržby použít Příruční nástroj na údržbu zbraní pro zlepšení kondice své zbraně." }
		{ time 18500 length 4300 text "Vezmi nástroj, otevři inventář a přetáhni nástroj na svoji pistoli." }
		{ time 23100 length 3800 text "Měj na paměti, že každý nástroj jde použít jenom jednou." }
	}

	multisub trg0020 {
		{ time 500 length 2400 text "Dobrá prace, teď jsi připraven pro Mariňáky." }
		{ time 3500 length 2900 text "Podívej se také na jiné oblasti výcviku než sa přihlásíš." }
		{ time 6800 length 1200 text "Můžou se ti hodit." }
	}

	// Technical training

	multisub trg0021 {
		{ time 600 length 3800 text "Inside, we'll teach you the basics of some technical skills you'll need in the Navy." }
	}

	multisub trg0022 {
		{ time 100 length 500 text "Welcome." }
		{ time 1200 length 7300 text "You'll notice when you're in the cyberlink booth, we'll provide you with a temporary cyber-interface and the skills you need to accomplish the training tasks." }
		{ time 8800 length 2600 text "But they'll only last so long as you're in the booth." }
	}

	multisub trg0023 {
		{ time 00 length 2700 text "The object in front of you is a container of nanites." }
		{ time 2900 length 4900 text "Nanites are consumed whenever you perform technical tasks, such as hacking or repairing." }
		{ time 8200 length 8200 text "When you pick up the container of nanites, they do not go in your general inventory, but are instead displayed in Use mode on the bottom-left of your screen." }
		{ time 17000 length 3000 text "Walk over to the keypad by the door and try out hacking." }
	}

	multisub trg0034 {
		{ time 00 length 1800 text "Use the keypad by right-clicking on it." }
		{ time 2300 length 3300 text "To the right of the number pad, you'll see an orange tab labeled \"Hack\"." }
		{ time 6000 length 1100 text "Left-click on the tab." }
		{ time 7800 length 3600 text "Text will appear, indicating the difficulty of the hack and any bonuses that apply." }
		{ time 12400 length 1800 text "Click on the Start button to begin hacking." }
		{ time 14900 length 1400 text "You'll see a grid of nodes." }
		{ time 16500 length 2500 text "Clicking on a node will either turn it bright or dark." }
		{ time 20000 length 3900 text "To succesfully hack, you must connect three bright nodes in a straight line." }
		{ time 24500 length 2500 text "Beware of the ICE nodes with the red outlines." }
		{ time 27400 length 5300 text "If one of these turns dark, you fail the hack and you might break the item you are working on, or worse." }
		{ time 33500 length 5900 text "You can restart your hack attempt at any time by hitting the Reset button, though you'll have to pay the nanite cost again." }
	}

	multisub trg0024 {
		{ time 00 length 2900 text "You can use nanites to buy items from replicators." }
		{ time 3100 length 2100 text "To use a replicator, right-click on it." }
		{ time 5600 length 2200 text "Then left-click on the item you wish to purchase." }
		{ time 8300 length 2500 text "The item you purchased will drop into the slot below." }
		{ time 11500 length 2600 text "Make sure you pick up your purchases before you leave." }
	}

	multisub trg0025 {
		{ time 600 length 1900 text "You learned the basics of the technical skills." }
		{ time 3000 length 6000 text "There are several other technical skills you'll learn throughout the course of your career, such as repairing items and modifying weapons." }
		{ time 9500 length 3500 text "The cyber-interfaces for these tasks are similar to the hacking interface." }
		{ time 13500 length 3200 text "Before you enlist in the Navy, try out the other training courses." }
		{ time 17000 length 700 text "They'll be useful." }
	}

	// Psionics training

	multisub trg0026 {
		{ time 700 length 3000 text "Inside you will learn how to reach out with your mind." }
		{ time 4200 length 2100 text "Do not let fear block your path." }
	}

	multisub trg0027 {
		{ time 00 length 6600 text "We've provided you with a virtual interface and the temporary ability to project simulated psionic powers." }
		{ time 7000 length 3900 text "Once you leave this area, these powers will be lost to you." }
	}

	multisub trg0028 {
		{ time 00 length 4900 text "The red bar at the lower left of your screen tells you how many psi points you have." }
		{ time 5200 length 4300 text "Psi points symbolize the current ability to use your psi powers." }
		{ time 9800 length 2900 text "Psi hypos replenish your psi points." }
		{ time 13000 length 4000 text "Try using a psi hypo and watch your psi points increase." }
		{ time 17400 length 4000 text "When you've reached your maximum in psi points, move to the next station." }
	}

	multisub trg0029 {
		{ time 00 length 5500 text "This psi amp amplifies your psi powers and lets you project them into the real world." }
		{ time 5800 length 3700 text "To equip it, pick it up and then hit the tilde key." }
		{ time 10000 length 4300 text "Firing the psi amp activates your currently selected psi discipline." }
		{ time 14700 length 5800 text "You currently have access to two disciplines, Cryokinesis and Kinetic Redirection." }
		{ time 21200 length 5000 text "Go into Use mode and click on the arrows on the bottom-right of the screen." }
		{ time 26700 length 3300 text "This will cycle through your available psi disciplines." }
		{ time 30400 length 7000 text "Later, clicking on the arrows above the number to the left will allow you to select psi disciplines from higher tiers." }
		{ time 37900 length 7000 text "Use Cryokinesis to destroy the robot, and Kinetic Redirection to pull that nanite container towards you." }
		{ time 45500 length 8500 text "Be careful, holding down the mouse button can augment the power, but holding it down for too long will cause burnout, which will damage you." }
		{ time 54500 length 3800 text "If you run out of psi points, use another psi hypo." }
	}

	multisub trg0030 {
		{ time 600 length 3600 text "Mastery of the mind is a slow but rewarding process." }
		{ time 4600 length 2700 text "Return to this area if you need more guidance." }
		{ time 7800 length 5800 text "Before you enlist in the OSA, it would be useful to experiment in the other training courses." }
	}
}

{
	type "convo"
	descr "Trainer"

	multisub init_0 {
		{ time 00 length 2400 text "Welcome to space station Wake Island, Marine." }
		{ time 2500 length 2700 text "So you survived basic training at Camp Lejeune." }
		{ time 5400 length 3900 text "Better still, you managed to learn a thing or two about standard weapons." }
		{ time 9800 length 2000 text "But now it's time for the real deal." }
		{ time 12600 length 3800 text "Your tour of duty will consist of four postings over four years." }
		{ time 16900 length 3300 text "The Corps demands a lot of you grunts, but the Corps is generous." }
		{ time 20500 length 1900 text "You get to choose your own postings." }
		{ time 23100 length 4200 text "Head up to the shuttle bays in the center of Wake Island and you'll be briefed on what's ahead." }
		{ time 27900 length 4000 text "When you find the right posting, head into that bay to accept the assignment." }
		{ time 32300 length 1000 text "Good luck, Marine!" }
	}

	multisub init_1 {
		{ time 00 length 2800 text "Welcome aboard the space station Chesapeake Bay, sailor." }
		{ time 3200 length 3900 text "It looks like you've picked up some standard weapon skills at basic on Coronado Island." }
		{ time 7500 length 1600 text "Now it's time for your tour of duty." }
		{ time 9600 length 2900 text "Your tour will consist of four postings over four years." }
		{ time 12800 length 3200 text "In this man's navy you're given a choice of three different postings a year." }
		{ time 16400 length 3500 text "It's up to you to decide what kind of career you want to have, so choose wisely." }
		{ time 20400 length 2700 text "Just approach your shuttle bay to receive a briefing on a posting." }
		{ time 23600 length 4000 text "If you think that posting is right for you, head into that bay to accept the assignment." }
	}

	multisub init_2 {
		{ time 00 length 4000 text "The OSA welcomes you to orbital station Chun Lo." }
		{ time 4200 length 4000 text "Ready yourself to feel the limitations of your mind slipping away." }
		{ time 8700 length 3200 text "We will guide your path over the next four years." }
		{ time 12200 length 4600 text "The shuttle bays at the center of this station will ferry you to your next stage of growth." }
		{ time 17300 length 3500 text "When you've chosen, head into the appropriate shuttle bay." }
		{ time 21100 length 3200 text "Get ready to learn things you've never imagined." }
	}

	// Marine briefings

	multisub brief01 {
		{ time 600 length 4500 text "If you're partial to spending time with a lot of high explosives, this posting is for you." }
		{ time 5600 length 5800 text "There's a lot of heavy lifting, but ordnance also gets the first pick of booze and other goodies coming aboard the supply ship Gallo." }
		{ time 11850 length 1100 text "Lock and load!" }
	}

	multisub brief02 {
		{ time 850 length 4700 text "The Navy maintains a survival training school on the surface of Io, the third moon of Jupiter." }
		{ time 6100 length 3600 text "Pros: there's no better way to improve stamina and survival skills." }
		{ time 9950 length 3200 text "Cons: the 21.2% mortality rate." }
		{ time 13550 length 3700 text "Plus, you've gotta spend the year with a bunch of Navy skanks." }
	}

	multisub brief03 {
		{ time 900 length 7700 text "Not every boarding party has the luxury of gravity, so the Corps strongly recommends every one of its brethren get in some zero-g training." }
		{ time 9150 length 3200 text "A year aboard the training station Guadalcanal should suffice." }
	}

	multisub brief04 {
		{ time 700 length 6100 text "A tour of duty aboard the Antigua should let you pick up some one-on-one beam weapon training from Gunnery Sergeant Malloy." }
		{ time 7200 length 2700 text "But heads up, she's a world-class SOB." }
	}

	multisub brief05 {
		{ time 800 length 7400 text "The automated asteroid ore facility in JM-432 supply the UNN shipyards, so they're crucial to defense." }
		{ time 8500 length 3000 text "However, they're also prime candidates for hackers." }
		{ time 11500 length 7100 text "Somebody has gotten their claws into the primary data loop and they need a team to head in there and blast their way past the automated defense systems." }
	}

	multisub brief06 {
		{ time 800 length 5800 text "Dummy ammunition, live ammunition, moving targets, stationary targets, live targets..." }
		{ time 7300 length 4400 text "The Port MacArthur training facility has enough hardware to warm the heart of any leatherneck." }
	}

	multisub brief07 {
		{ time 700 length 3900 text "The UNN Secretary-General's office needs a full staff of armed guards." }
		{ time 5000 length 4200 text "When things are dull, it requires a lot of standing around looking good in a uniform." }
		{ time 9700 length 4000 text "When things are bad, it can require fending off a psi-terrorist assault." }
	}

	multisub brief08 {
		{ time 700 length 3400 text "The Polidies trading station's long been a haven for the black market." }
		{ time 4400 length 4000 text "However, up until now they have not interfered with the running of station operations." }
		{ time 9100 length 6900 text "Recent reports indicate that the Polidies command staff has been overthrown, and the station is under the control of a self-appointed \"Magnate\"." }
		{ time 16500 length 3700 text "This must be rectified and a Marine presence maintained on the station." }
	}
 
	multisub brief09 {
		{ time 800 length 5400 text "The Colony Air Service gets the dregs of the fleet, and the Antigua is the dregs of the dregs." }
		{ time 7000 length 6800 text "You'll learn a lot about recalcitrant machinery on a tour of duty aboard the Antigua, if it doesn't blow you to hell and back first." }
	}

	// Navy briefings

 	multisub brief10 {
		{ time 800 length 5200 text "The UNN Lucille is looking for an ops training officer to learn the ship's navigation and data control systems." }
		{ time 6400 length 3700 text "You'll get your feet wet with the high-tech systems, but also expect some heavy lifting." }
	}

	multisub brief11 {
		{ time 900 length 4600 text "The UNN Lucille is looking for an engineer's mate to help maintain the ship's core energy systems." }
		{ time 5900 length 3800 text "There's some heavy lifting involved, sailor, but you'll learn your way around the high-tech equipment." }
	}

	multisub brief12 {
		{ time 800 length 3600 text "The UNN Lucille is looking for volunteers for their military police detachment." }
		{ time 4900 length 4500 text "Those sailors can get pretty rowdy on these year-long cruises, so you better not be afraid of a tussle." }
	}

	multisub brief13 {
		{ time 800 length 6300 text "The UNN Carfax is undertaking a mission to examine a newly discovered class B comet approaching the outer solar system." }
		{ time 8000 length 5500 text "You'll likely pick up some useful skills working with the high-tech navigation systems aboard this newly commissioned heavy cruiser." }
	}

	multisub brief14 {
		{ time 800 length 4600 text "The UNN Pierce is ferrying liberated political prisoners back home from their detention near Saturn." }
		{ time 6100 length 6300 text "The Pierce has been assigned a detachment of Marines and needs sailors to load, administer, and maintain the arms on board the ship." }
	}

	multisub brief15 {
		{ time 800 length 3200 text "LaVerne, Florida hosts the Navy's premiere Tactical Training School." }
		{ time 4500 length 4400 text "While maybe not as respected as the Marine's facility at Fort Bush, there's a lot to be learned here." }
	}

	multisub brief16 {
		{ time 800 length 9500 text "The Navy's Marie Curie Research Facility on Aquinas IV is currently conducting research on a new strain of spaceborne virus that killed 220,000 citizens of New Atlanta." }
		{ time 11100 length 4500 text "To lift the quarantine, we must determine how the virus pierced the city's micronanite shielding." }
	}

	multisub brief17 {
		{ time 800 length 4500 text "The Navy maintains a survival training school on the surface of Io, the third moon of Jupiter." }
		{ time 5900 length 3700 text "Pros: there's no better way to improve stamina and survival skills." }
		{ time 10000 length 3100 text "Cons: the 21.2% mortality rate." }
	}

	multisub brief18 {
		{ time 900 length 3800 text "The Navy strongly encourages every sailor to undertake some amount of zero-g training." }
		{ time 5400 length 4300 text "A year at the Yamamoto space station in Earth's orbit will more than suffice." }
	}

	// OSA briefings

	multisub brief19 {
		{ time 800 length 4100 text "The sensory deprivation tanks aboard the TOS Shao Ling await you." }
		{ time 5300 length 6400 text "There, you will spend a solitary year focused in a meditation on motion and sound, and how they may serve your will." }
	}

	multisub brief20 {
		{ time 700 length 4200 text "The sensory deprivation tanks abord the TOS Ru Nang await you." }
		{ time 5400 length 3800 text "A year in meditation on the nature of matter will grant you power over it." }
	}

	multisub brief21 {
		{ time 800 length 5400 text "The sensory deprivation tanks abord the TOS Chu Lun are modulated for your training." }
		{ time 6700 length 6700 text "You shall spend a year in contemplation of mass - both yours and that of objects - until you can bend them to your intentions." }
	}

	multisub brief22 {
		{ time 900 length 7900 text "Sifting the thoughts of treachery and disloyalty from the morass of emotion and internal conflict that fill most mundanes can be disquieting." }
		{ time 9200 length 7700 text "You shall spend a year building the general strength of your mind, while learning how to probe the thoughts of the less capable without losing yourself." }
	}

	multisub brief23 {
		{ time 900 length 5800 text "Doctor Chandrisvilan's research labs have produced many of this decade's advances in psionic technique." }
		{ time 7000 length 5200 text "You shall spend a year serving his genius, learning to understand his insights and whims." }
	}

	multisub brief24 {
		{ time 800 length 2900 text "Your body has been neglected in your training of your mind." }
		{ time 4100 length 3700 text "On Io, you will find soldiers who wish to test their endurance." }
		{ time 8200 length 4400 text "You will surpass their physical prowess without compromising your mental dicipline." }
	}

	multisub brief25 {
		{ time 800 length 5600 text "Acts of political terrorism and corporate coercion disturb corporate and political stability." }
		{ time 6900 length 5700 text "You shall spend a year battling these chaotic elements, both psionically and by physical force." }
	}

	multisub brief26 {
		{ time 800 length 4900 text "In the grand scheme, individuals are no more important than pieces on a game board." }
		{ time 5900 length 5600 text "Occasionally it becomes necessary to remove a piece, without disturbing the flow of the game." }
		{ time 12200 length 3700 text "These removals will be done in silence and with complete secrecy." }
		{ time 16300 length 2600 text "You shall spend a year learning these skills." }
	}

	multisub brief27 {
		{ time 800 length 3700 text "Many threats to security can only be defeated from inside." }
		{ time 4800 length 5200 text "Your mind shall be carefully blanked and conditioned with the nature and past of a criminal." }
		{ time 10600 length 8400 text "Join with the criminal and rebellious, endure their squalor and chaos, and then, when it is time, liquidate them from within." }
	}
}
