SUB1

// Engineering =================================================================
{
	type "convo"
	descr "Politová"
	multisub em0101 {
		{ time 400 length 4300 text "Musíš si pospíšit. Ještě si neuvědomuješ, co všechno je v sázce." }
		{ time 5300 length 4700 text "Dej pozor na příruční sklad č.4. Nechala jsem tam nějaké vybavení." }
		{ time 10000 length 6600 text "Vstupní kód je 59004. Musím jít na palubu..." }
		{ time 18600 length 2700 text "[Xerxes] Mnoho požaduje ukončení této komunikace." }
		{ time 22000 length 2200 text "[Xerxes] Omlouváme sa za vzniknuté potíže." }
	}
	multisub em0102 {
		{ time 500 length 6200 text "Teď pozorně poslouchej. Xenomorfové, kteří si podrobili tuto loď, pocházejí pravděpodobně z povrchu Tau Ceti 5." }
		{ time 7300 length 5300 text "Byli schopni infikovat většinu členů posádky, prostřednictvím mimořádné invazivní parazitní techniky." }
		{ time 13100 length 6200 text "Také předvedli schopnost ovládat chování ostatních pomocí určité formy omezené telepatie." }
		{ time 19900 length 4000 text "Najdi výzkumný software. Porozuměj jim... a pak je znič." }
	}
	multisub em0103 {
		{ time 1200 length 4000 text "Radiace musela aktivovat ochranné zámky přístupu k Reaktoru." }
		{ time 5500 length 3800 text "Musíš najít nějaký způsob, jak odstranit radiací z potrubí chladícího okruhu." }
		{ time 9700 length 5100 text "Xerxes blokuje můj přístup do primární databáze, takže nemohu získat žádné informace, které by mohli pomoci." }
		{ time 15400 length 1600 text "Xerxes pracuje teď pro ně." }
	}
	multisub em0104 {
		{ time 1100 length 6200 text "Dávej dobrý pozor... musíš najít způsob, jak vyčistit chladící potrubí a tak se dostat k Reaktoru..." }
		{ time 7700 length 5200 text "Tato loď musí mít nějaký druh záložního systému, připraveného pro tuhle situaci." }
 	}
	multisub em0105 {
		{ time 800 length 3300 text "Good, the sub-elevators should now be back online." }
		{ time 5800 length 3400 text "I've opened up an access tunnel that can quickly get you to the elevator." }
		{ time 9600 length 3500 text "Now get up to deck 4, I'll meet you there. Hurry." }
	}
	multisub em0106 {
		{ time 700 length 6800 text "Teď spusť motorové bloky. Budeš muset jít do gondoly 1 a 2 a ručně spustit generátory." }
		{ time 7900 length 7800 text "Pak restartuj systém řízení Reaktoru. Pozor, systém nenaběhne, pokud předtím nespustíš oba motorové bloky." }
		{ time 16400 length 5900 text "Buď opatrný. Oni teď shromažďují své skutečné síly. A už přesně vědí, kde se nacházíš." }
	}
	multisub em0107 {
		{ time 1800 length 6700 text "Xerxes je o krok před námi. Vytvořil přemostění na Počítači Kapalinového Řízení a zablokoval přístup." }
		{ time 8700 length 4000 text "Dávej pozor. Měl bys být schopen najít nějaké řešení" }
	}
	multisub em0108 {
		{ time 1300 length 6500 text "Dobrá práce. Reaktor je opět spuštěn. Teď běž do výtahu a přijď za mnou na 4. palubu." }
		{ time 8300 length 5000 text "Zatímco jsi byl zaměstnán, odhalila jsem na palubě přítomnost některých annelidských artefaktů." }
		{ time 13800 length 3000 text "Myslím, že bys byl schopen je použít ke svému prospěchu." }
		{ time 17300 length 3500 text "Uložila jsem tyto informace do lodních jednotek vylepšování dovedností." }
		{ time 21100 length 3500 text "Ty teď budou schopny předat zmíněné údaje do tvého kybernetického vybavení." }
		{ time 25400 length 2900 text "Na co ještě čekáš? Už ať jsi ve výtahu." }
	}
	multisub em0110 {
		{ time 600 length 2000 text "Teď jsi na Technické palubě." }
		{ time 3100 length 4800 text "Najdi Reaktor a znovu ho nastartuj. Tím se obnoví napájení výtahů." }
		{ time 8200 length 4200 text "Dostávám odtud spousty podivných údajů, takže si dávej dobrý pozor." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0109 {
		{ time 1500 length 6200 text "Teď jsem schopná zničit tu nákazu, kdykoli budu chtít." }
		{ time 8800 length 4600 text "Mnoho se bude třást před mou mocí." }
		{ time 14800 length 3600 text "Jsi výkonný sluha, člověče." }
		{ time 18900 length 12700 text "Teď se vrať na palubu Velení, najdi průchod a přesuň se na Rickenbacker." }
	}
}

// Med/Sci ==========================================================================
{
	type "convo"
	descr "Politová"
	multisub em0201 {
		{ time 1200 length 4000 text "V celém sektoru se snižuje tlak a modré vakuové štíty to už dlouho nevydrží." }
		{ time 5800 length 2700 text "Dostaň se za hermetický uzávěr dřív, než tě to vysaje do vesmíru." }
		{ time 8800 length 600 text "Dělej!" }
	}
	multisub em0202 {
		{ time 500 length 3000 text "Některé z dveří jsou zamčeny kódovými zámky." }
		{ time 4000 length 3600 text "Tělo ležící před tebou patřilo údržbáři tohoto sektoru." }
		{ time 8200 length 4600 text "Možná má ten číselný kód u sebe. Nebuď háklivý a prohledej jeho tělo." }
		{ time 13500 length 1000 text "Jemu to už vadit nebude." }
	}
	multisub em0203 {
		{ time 500 length 3500 text "Ten nanicovatý počítač Xerxes odpojil i všechny výtahy." }
		{ time 4700 length 4600 text "V blízkosti reaktoru, na palubě 1, bys mohl zapojit nouzové napájení, které by je všechny zase zprovoznilo." }
		{ time 9800 length 3200 text "Jenže výtahem se tam teď nedostaneš. Počkat..." }
		{ time 14400 length 3100 text "Je tady nějaký druh údržbářského přístupu, právě z této chodby." }
		{ time 18300 length 6000 text "Tudy bys se mohl dostat na palubu 1. Jenže vstup je zamčen a Xerxes mi nechce prozradit vstupní kód." }
		{ time 25000 length 3300 text "Měl by ho ale mít i Dr. Watts. Bude nejspíš někde v sektoru Kajut pro posádku." }
		{ time 28900 length 5900 text "Vstupní kartu tam má Grassi, ale ten je zase někde v lékařských prostorech, zřejmě poblíž pitevny." }
		{ time 35300 length 2700 text "Běž co nejdřív do prostorů Kliniky a najdi Grassiho." }
	}
	multisub em0204 {
		{ time 500 length 5500 text "Výborně. Dostal jsi se na Kliniku. Najdi Grassiho a získej vstupní kartu do sektoru Kajut posádky." }
		{ time 6600 length 4200 text "Grassi se staral o tvůj kryogenický spánek, tak se možná bude chtít k tobě přidat..." }
		{ time 11400 length 1700 text "Pokud ovšem není na kousky." }
	}
	multisub em0205 {
		{ time 1100 length 3300 text "Můžeš hackovat i replikátory, čímž získáš nadstandardní ponuku." }
		{ time 4900 length 3200 text "Využij to. Využij jakoukoliv možnost, abys se dostal na palubu 4." }
		{ time 8500 length 1500 text "Tohle není hra." }
	}
	multisub em0206 {
		{ time 1000 length 2500 text "Neztrácej čas samochválou." }
		{ time 3900 length 3800 text "Slez šachtou dolů do Techniky a znovu spusť hlavní Reaktor." }
		{ time 8100 length 3400 text "Obnovíš tím napájení výtahu a budeš konečně schopen se dostat na palubu 4." }
		{ time 11900 length 700 text "Do toho!" }
	}
	multisub em0207 {
		{ time 900 length 4500 text "Good, you've made it into the crew sector. Now find Dr. Watts' room." }
	}
	multisub em0208 {
		{ time 500 length 3200 text "Your new cybernetic interface might be disorienting." }
		{ time 4000 length 6900 text "I've uploaded detailed technical specs to info kiosks in your area, which will answer your questions about its usage." }
		{ time 11400 length 3800 text "Certain areas of the ship require specific access cards for entry." }
		{ time 15700 length 3900 text "Pick up the card near you and then activate the card slot by the door." }
	}
	multisub em0209 {
		{ time 1000 length 3700 text "Ten článek je vybitý. Někde poblíž by měla být dobíjecí stanice." }
		{ time 5000 length 3900 text "Použij ji a ona dobije všechny energetické zařízení, které máš u sebe." }
		{ time 9400 length 6000 text "Až článek nabiješ, vlož ho do záložního napájení u dveří. Tím by se měl otevřít hermeticky uzávěr." }
		{ time 15700 length 3600 text "Pospěš si s tím, vakuová těsnění už to déle nevydrží." }
	}
	multisub em0210 {
		{ time 900 length 5800 text "Xerxes ovládá bezpečnostní systémy. Vyhýbej se kamerám, nebo je znič." }
		{ time 7300 length 4500 text "Pokud na to stačíš, můžeš hackovat bezpečnostní počítače, čímž se kamery na čas vypnou." }
		{ time 11900 length 3000 text "Ale pozor, pokud to spackáš, spustí se poplach." }
		{ time 15400 length 2100 text "A jako mrtvola mi nejsi k ničemu." }
	}
	multisub em0211 {
		{ time 900 length 4000 text "Make sure you expend all your cybernetic modules before you leave this area." }
		{ time 5500 length 2500 text "You don't know when you'll find another upgrade unit." }
		{ time 8700 length 1900 text "Now find a way to deck 4." }
	}
	multisub em0212 {
		{ time 1400 length 6100 text "There's a number of cyber upgrade stations in this area, one for each of your unit's enhancement functions:" }
		{ time 7900 length 5000 text "Firearms, basic abilities, psionic projection, and technical skills." }
		{ time 13700 length 7300 text "I'm uploading a few upgrade modules to your gear right now. You'll need them to interface with the upgrade stations." }
		{ time 21600 length 5400 text "But choose your enhancements very carefully... upgrade units are difficult to come by." }
	}
	multisub em0213 {
		{ time 900 length 5900 text "Tyto kybernetické moduly se používají ke vylepšování jednotlivých subsystémů tvých neurálních vylepšení." }
		{ time 7300 length 7200 text "Pamatuj, jsou 4 různé druhy jednotek vylepšování dovedností, takže nevyplýtvej všechny své moduly u jediné," }
		{ time 14600 length 4800 text "tedy pokud jsi nejsi opravdu jist, že chceš zlepšit svůj hardware jenom v jedné oblasti." }
	}
	multisub em0214 {
		{ time 700 length 5500 text "Dr. Watts je ve své pracovně a stále žije.  Měl by znát přístupový kód údržbářské šachty." }
		{ time 6700 length 6000 text "Pospěš si, je těžce zraněn!  Nenech ho umřít, dokud ti neřekne to číslo!" }
	}
	multisub em0215 {
		{ time 700 length 5000 text "Pozor... Z radarové antény za oknem přicházejí nějaké zvláštní údaje." }
		{ time 6400 length 1600 text "Stává se nestabilní protože..." }
		{ time 8000 length 2400 text "Utíkej!  Kryj se!" }
	}
	multisub em0217 {
		{ time 700 length 6700 text "Sakra! Výpadek napájení vyřadil i dveře této přepážky. Je jen jeden způsob, jak se dostat do lékařského oddělení." }
		{ time 7900 length 2600 text "Vezmi článek ležící na podlaze a najdi dobíjecí stanici." }
		{ time 11100 length 5000 text "Obávám se že ta, kterou jsi použil předtím je už ve vakuu, ale na této palubě by měla být ještě jedna." }
		{ time 16700 length 4100 text "Až ten článek nabiješ, vlož ho do záložního napájení." }
	}
	multisub em0218 {
		{ time 600 length 4000 text "Watts tu není.  Nejspíš bude ve své pracovně v sektoru R&D." }
		{ time 5000 length 3700 text "Ale možná, že tu má někde záložní R&D kartu.  Rozhlédni se kolem." }
	}
	multisub em0219 {
		{ time 600 length 3600 text "Na většině palub můžeš najít biorekonstrukční zařízení." }
		{ time 4800 length 3900 text "Xerxes je všechny odpojil, ale já jsem je zase potají zapojila." }
		{ time 9400 length 4400 text "Zařízení musíš aktivovat, abys mu poskytl soubor tkáňových vzorků." }
		{ time 14400 length 4900 text "Až to uděláš, bude toto zařízení schopno restaurovat tvé tělo i z nepatrného zbytku." }
		{ time 19800 length 3500 text "Není to sice nic příjemného, ale stále lepší, než pomalý rozklad." }
	}
	multisub em0220 {
		{ time 600 length 2300 text "Možná se staneš svědkem zvláštního jevu." }
		{ time 3300 length 7200 text "Tvé experimentální kybernetické vybavení třídy R má zesílené vnímání, které by teoreticky mohlo zachytit zbytky psychických emisí." }
		{ time 11100 length 5600 text "Tyto emise obvykle pocházejí od nedávno zemřelých. Literatura je označuje jako duchy." }
		{ time 17000 length 3400 text "Já jim říkám autohypnoticke poruchy v jednotce R." }
		{ time 21200 length 2700 text "Nenech se jimi rozptylovat při tvém poslání." }
	}
	multisub em0221 {
		{ time 600 length 4000 text "Výborně! Dostal jsi se pryč dřív, než celý prostor ztratil tlak." }
		{ time 5300 length 6900 text "Přidala jsem ti několik kybernetických modulů. Můžeš je použít ke zlepšení tvé kybernetické výbavy pomoci Jednotek vylepšování dovedností." }
		{ time 12900 length 5600 text "Ve vedlejší místnosti jsou jich čtyři druhy - pro každý subsystém tvého kybernetického vybavení:" }
		{ time 18700 length 2900 text "Stats, PSI, Zbraně a Tech." }
		{ time 22400 length 3200 text "Ale používej moduly s rozvahou... těžko se obstarávají." }
	}
	multisub em0222 {
		{ time 700 length 5900 text "Na každé palubě je umístěn chemický sklad, kde můžeš najít chemikálie, potřebné k výzkumu nalezených artefaktů." }
		{ time 7300 length 5300 text "Nesnaž se u sebe nosit všechny chemikálie najednou. Je to nepraktické a zbytečné." }
		{ time 13100 length 4100 text "Tvůj výzkumný software ti vždy včas sdělí, kterou chemikálií potřebuje." }
	}
}

// Hydroponics ======================================================================
{
	type "convo"
	descr "Politová"
	multisub em0301 {
		{ time 700 length 6800 text "Sakra!  Něco zablokovalo šachtu a výtah se nemůže dostat na palubu 4. Pokouším se to určit..." }
		{ time 8400 length 5600 text "Zjistila jsem ohromné množství nějakého druhu biologického materiálu, který pronikl do výtahové šachty." }
		{ time 14700 length 5000 text "Prostředí na této palubě bylo změněno na ohromnou líheň Xenomorfu." }
		{ time 20200 length 3800 text "Ale pokud zde nebudeš pobývat příliš dlouho, nemělo by to být nebezpečné." }
		{ time 24300 length 4000 text "Bude ovšem třeba odstranit ten biomaterial z výtahové šachty." }
		{ time 28700 length 4200 text "Vstupují do hlavní databáze.  Zjistíme, copak zajímavého tam najdeme." }
	}
	multisub em0302 {
		{ time 1500 length 5500 text "Ok, zůstaň kde jsi.  Je tu nádoba s experimentálním materiálem zvaným Toxin-A." }
		{ time 7600 length 3500 text "Vyvinula ho místní skupina vědců, snažící se potlačit růst vetřelců." }
		{ time 11300 length 2600 text "Ale nemám žádné údaje o tom, jak ho správné použít." }
		{ time 14600 length 16700 text "Měl bys být schopen ho vyzkoumat sám." }
		{ time 17000 length 4600 text "Posílám ti dost kybernetických modulu, abys mohl získat dostatečnou úroveň výzkumu, pokud ji ještě nemáš." }
	}
	multisub em0303 {
		{ time 1200 length 5000 text "Fajn, Nádoby s Toxinem-A je třeba umístit přímo do klimatizačních jednotek." }
		{ time 6700 length 4500 text "Na této palubě jsou celkem čtyři.  Pokud se ti podaří nádoby umístit do všech jednotek," }
		{ time 11200 length 4600 text "mělo by to značně ovplyvnit růst těhle odporných kreatůr." }
		{ time 16400 length 3000 text "Rovněž by to mělo odstranit i biomateriál ve výtahové šachtě." }
	}
	multisub em0304 {
		{ time 1600 length 4200 text "Proč jsi tak zoufale pomalý?!  Copak si myslíš, že je to jenom nějaká hra?" }
		{ time 6200 length 3900 text "Jsi naživu jen díky notné dávce štěstí a mé nekonečné trpělivosti." }
		{ time 10500 length 1100 text "Hni sebou!" }
	}
	multisub em0305 {
		{ time 1500 length 3700 text "Konečně!  Přístroje ukazují, že je výtahová šachta volná." }
		{ time 5500 length 3300 text "Teď běž na palubu 4.  Budu na tebe čekat." }
	}
	multisub em0306 {
		{ time 1700 length 8000 text "Výborně!  Je zjevné, že biomateriál na zdech a ve výtahové šachtě je napadán rozptylovaným biotoxinem." }
		{ time 10300 length 3200 text "Teď to samé udělej u dalších tři klimatizačních jednotek." }
	}
	multisub em0307 {
		{ time 1300 length 3100 text "Už vědí kde jsi.  Najdi nějaký způsob, jak uvolnit šachtu." }
		{ time 4800 length 2700 text "Já tady udělám vše, co půjde.  Teď běž! }
		{ time 8100 length 1500 text "Na neúspěch není čas." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnoho"
	multisub em0307 {
		{ time 2600 length 7600 text "Život roste v děloze těch stěn... živto, který nikdy neviděl povrch Země." }
	}
	multisub em0508 {
		{ time 1800 length 5100 text "Děťátka musí spát. Děťátka musí odpočívat." }
		{ time 8100 length 4000 text "Moudrý je ten, kdo je neprobudí." }
		{ time 13000 length 6400 text "Opusť toto místo, jinak tě zraníme, jako jsi zranil ty nás." }
	}
	multisub em0807 {
		{ time 1800 length 5600 text "Podvol se biomase a tvé utrpení skončí." }
	}
}



// Operations =======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0401 {
		{ time 1400 length 8400 text "Mě děti si přivlastnily tři simulační jednotky na této palubě." }
		{ time 10300 length 14000 text "Používají jejich výkon k vývoji mutagenu, kterým pak transformují těla tvých mrtvých kamarádů na zabijácké hybridy." }
		{ time 24700 length 10500 text "To nedovolím.  Musíš najít nějaký způsob, jak přeprogramovat simulační jednotky." }
		{ time 35400 length 5300 text "Tvou pozornost si ale zaslouží i dění na palubě 5." }
		{ time 40800 length 5400 text "Pusti se do toho, jak uznáš za vhodné...  ale dokonči to, člověku..." }
		{ time 46800 length 8200 text "Zklamání bych takovému ubožákovi jako ty rozhodně neprominula." }
	}
	multisub em0403 {
		{ time 2600 length 11000 text "Má stvoření se vyvíjejí...  Jejich sjednocená mysl se vzbouřila proti vlastní stvořitelce." }
		{ time 13700 length 7300 text "Ta havěť tě volá, láká tě, aby ses připojil k jejich nechutné mase." }
		{ time 22100 length 8400 text "Znič mé nepřátele...  a já budu nadále trpět tvoji existenci." }
	}
	multisub em0406 {
		{ time 2100 length 10300 text "Před tebou leží střepina krystalů - výtvor mých dětí, a teda i výtvor můj." }
		{ time 12500 length 4400 text "Elegantní zbraň, smrtící, přesná." }
		{ time 19600 length 9100 text "Nauč se ji používat...  Může být to jediné, co bude stát mezi tebou a jejich nákazou." }
	}
	multisub em0407 {
		{ time 1900 length 4600 text "Za těmito dveřmi leží jedna že simulačních jednotek." }
		{ time 6600 length 8400 text "Přeprogramuj ji a já získám větší kontrolu nad touto lodí na úkor obstarožního Xerxese." }
		{ time 16900 length 6300 text "Až budu já paní na této lodi, mužů ti otevřít více dveří." }
		{ time 23200 length 7300 text "Ale teď mi ještě blokují přístup.  Uráží mou velikost." }
		{ time 31400 length 9300 text "Donuť je zaplatit za jejich chybu a já tě za to vyvedu z temnot." }
	}
	multisub em0408 {
		{ time 1000 length 5000 text "Udělal jsi hodně práce, na věc s tak malou důležitosti." }
		{ time 9300 length 11200 text "[Xerxes] Varování, systémová data kompromitována. Nepřátelská UI..." }
		{ time 20600 length 5400 text "Xerxes je oslaben.  Přistupují do primárního dataloopu." }
		{ time 26700 length 3200 text "Spájím svou bytost s tuto lodí." }
		{ time 30600 length 5200 text "Má nádhera se rozšiřuje, naplňuje tepny této lodi." }
		{ time 36500 length 7000 text "Získala jsem kontrolu.  Jsem..." }
		{ time 43700 length 8400 text "Ne...  je to beznadějné...  ta rakovina se rozprostírá celým Von Braunem." }
		{ time 52300 length 7400 text "Oni vyplnili všechny dostupné zlomy a škáry...  Podrobili si ji..." }
		{ time 60000 length 7200 text "Není žádná možnost...  Aktivovala jsem ústřední výtah na Rekreační palubě." }
		{ time 67800 length 6100 text "Dostaň se na palubu 6.  Svá další přání ti sdělím, až tam dorazíš." }
	}
	multisub em0409 {
		{ time 3500 length 6000 text "Udělal jsi hodně práce, na věc s tak malou důležitosti." }
		{ time 12700 length 3300 text "[Xerxes] Varování..." }
		{ time 16300 length 3200 text "Teď se přesuň na Rekreační palubu." }
		{ time 20200 length 3300 text "Neotálej.  Toužím po své pomstě." }
	}
	multisub em0410 {
		{ time 2100 length 5800 text "Teď můžu svou velkolepost kdykoli přenést na Rickenbacker." }
		{ time 8400 length 4200 text "Pokračuj do sálu s reaktorem na Technické palubě." }
		{ time 13100 length 10800 text "Tam můžeš nastavit přetížení reaktorů na mě ovládání, zadáním autorizovaného destrukčního kódu 94834." }
		{ time 24400 length 11800 text "Až to uděláš, přejdi na Rickenbacker.  Pak oddělíme obě lodi a konečně zlikvidujeme tu nákazu." }
	}
}

// Many taunt (used as vtrigger instead of email)
{
	type "convo"
	descr "Mnoho"
	multisub em0405 {
		{ time 2500 length 5100 text "Je to nepřítel Mnoha... nesouznění v naší symfonii." }
		{ time 7800 length 8500 text "Užij si své sobecké činy destrukce, jež za nima leží sněť osamění." }
	}
}

// Recreation =======================================================================
{
	type "convo"
	descr "Politov8"
	multisub em0502 {
		{ time 500 length 1000 text "Co to provádíš?" }
		{ time 2000 length 2700 text "Vrať se do výtahu a jdi na palubu 4." }
		{ time 5100 length 1800 text "Na prohlídku lodi nemáme čas." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0504 {
		{ time 1300 length 9800 text "Plazíš se jako insekt.  Myslíš jako insekt.  Jsi jen insekt." }
		{ time 10300 length 6600 text "Jsou i jiní, kteří mohou posloužit mým cílům." }
		{ time 17000 length 4800 text "Dávej si pozor, abys příliš nepokoušel mou přízeň." }
		{ time 22000 length 7800 text "Trpělivost nebývá obvyklou vlastností bohů." }
	}
	multisub em0505 {
		{ time 2700 length 7500 text "Cítíš jak uvnitř toho špinavýho pytle masa, kterému říkáš tělo, bobtná strach?" }
		{ time 10400 length 3000 text "Jaké to je, mít strach?" }
		{ time 14200 length 5200 text "Proč tak lpíš na té své patetické existenci?" }
		{ time 20100 length 4600 text "Kdybys tak mohl cítit jen jiskřičku mě slávy." }
		{ time 25700 length 7900 text "Opovrhuji svými výtvory, které mě teď nutí spoléhat na takové smětí, jako jsi ty." }
	}
	multisub em0506 {
		{ time 2200 length 4500 text "Vysílání bylo zkomoleno a přerušeno.  Nevadí." }
		{ time 7400 length 5300 text "Zničíme má stvoření přímo tady.  Příprav se..." }
		{ time 15900 length 11200 text "[Xerxes] Varování, systémové data byly kompromitovány. Nepřátelská UI..." }
		{ time 28400 length 6000 text "Oslabila jsem Xerxese.  Přistupuji do primárního dataloopu." }
		{ time 35400 length 3200 text "Spájím svou bytost s tuto lodi." }
		{ time 39200 length 5200 text "Má nádhera se rozšiřuje, naplňuje tepny této lodi." }
		{ time 45200 length 7000 text "Získala jsem kontrolu. Jsem..." }
		{ time 52300 length 8400 text "Ne...  je to beznadějné...  ta rakovina se rozprostírá celým Von Braunem." }
		{ time 60900 length 7400 text "Oni vyplnili všechny dostupné zlomy a škáry...  podrobili si ji..." }
		{ time 68700 length 7200 text "Není jiná možnost...  Aktivovala jsem ústřední výtah na Rekreační palubě." }
		{ time 76400 length 6100 text "Dostaň se na palubu 6.  Svá další přání ti sdělím, až tam dorazíš." }
	}
	multisub em0509 {
		{ time 1300 length 8600 text "Tvým kolegům se v Atletickém sektoru této paluby podařilo nainstalovat vysílací stanici." }
		{ time 10700 length 10300 text "Vysílač je určen k vysílání zpráv zpátky na Zemi. Tak je chtějí varovat před událostmi, které postihly tuto loď." }
		{ time 21600 length 8000 text "A navíc odebírá část výkonu obvodům Xerxese, jež se tak stává méně odolným mému vlivu." }
		{ time 30200 length 6000 text "Až toto dokončíš, budu ovládat primární dataloop." }
		{ time 36800 length 7000 text "Annelidi si nejsou vědomi přítomnosti stanice, ale střeží oblast z vlastních důvodů." }
		{ time 44900 length 3900 text "Najdi ten vysílač, a aktivuj ho." }
	}
	multisub em0510 {
		{ time 1600 length 4600 text "Vysílání bylo zkomoleno a přerušeno.  Nevadí." }
		{ time 6300 length 4700 text "Zničíme má stvoření přímo tady.  Příprav se..." }
		{ time 13800 length 3300 text "[Xerxes] Varování..." }
		{ time 18400 length 5600 text "Vrať se na palubu Operací a přeprogramuj simulační jednotky." }
		{ time 24700 length 6600 text "Neotálej.  Toužím po mé pomstě." }
	}
	multisub em0511 {
		{ time 1300 length 9000 text "Tvým kolegům se v Atletickém sektoru této paluby podařilo nainstalovat vysílací stanici." }
		{ time 10700 length 10400 text "Vysílač je určen k vysílání zpráv zpátky na Zemi. Tak je chtějí varovat před událostmi, které postihly tuto loď." }
		{ time 21600 length 5200 text "A navíc odebírá část výkonu obvodům Xerxese." }
		{ time 27100 length 8900 text "Až budeš mít hotovo tohle i úkoly, které jsem ti připravila na palubě Operací, budu schopna s Xerxesem zatočit." }
		{ time 37300 length 4000 text "Najdi ten vysílač, a aktivuj ho." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "Mnoho"
	multisub em0503 {
		{ time 1700 length 3300 text "Nedůvěra je tyranií individualizmu." }
		{ time 5800 length 3000 text "Tvůj vlastní druh tě vnímá jako hrozbu." }
		{ time 9300 length 2900 text "Proč vraždíš naši jednotu?" }
		{ time 13200 length 3300 text "To nic... hranice byli vytýčeny." }
		{ time 17300 length 6400 text "Přestaneš být... je to jen otázka toho, kdo tě ukončí." }
		{ time 24500 length 3000 text "My... nebo ty." }
	}
	multisub em0507 {
		{ time 2600 length 5000 text "Hledáš své spříznence, no nenacházíš je." }
		{ time 8200 length 10800 text "Jseš tak sám." }
		{ time 11300 length 5300 text "Jaký to je pocit být jeden proti nekonečnu?" }
	}
}

{
	type "nonverbal"
	descr "Banány"
	multisub em0512 {
		{ time 1000 length 11000 text "[opičárny]" }
	}
}

// Command ==========================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0601 {
		{ time 2100 length 6100 text "My creation has run rampant. I demand their extermination." }
		{ time 8300 length 3600 text "I have no choice but to destroy this starship." }
		{ time 12800 length 10300 text "We can make our escape in the Rickenbacker, but you must transfer my intelligence to that ship first." }
		{ time 23500 length 3300 text "Proceed to the Von Braun's bridge on this deck." }
		{ time 27300 length 8000 text "There you will find an access card to command center on Ops. Find the card and proceed to Ops." }
		{ time 35900 length 6400 text "But beware... the human-Annelid hybrids grow more sophisticated by the minute." }
		{ time 43100 length 1000 text "You do not." }
	}
	multisub em0602 {
		{ time 1300 length 4800 text "My creation once again is one step ahead of you." }
		{ time 6700 length 7700 text "They've managed to destroy this shuttle's shield control computer." }
		{ time 14600 length 4500 text "But their brilliance is a jealous shadow of my own." }
		{ time 19400 length 8700 text "You will locate a replicator in the shuttle control area. I've uploaded the nano-formula for a sympathetic resonator." }
		{ time 28400 length 4800 text "You must hack the replicator to make it generate the device for you." }
		{ time 33600 length 5500 text "Once you have it, attach it to the shield generator in the shuttle bay." }
		{ time 40000 length 8200 text "The device will create a chronic resonation wave that will quickly rupture the shuttle's fuel tank and destroy it." }
		{ time 48200 length 5700 text "Make sure you're not there when it happens. I still have need of you." }
	}
	multisub em0604 {
		{ time 3300 length 4100 text "Beware, insect, the situation has changed." }
		{ time 8000 length 9200 text "They sense our intentions and are loading shuttles with their offspring. They will not escape my wrath." }
		{ time 17700 length 6600 text "You must proceed to the shuttle bays on this deck, and destroy those shuttles." }
		{ time 24500 length 6300 text "They have a taste for your blood now." }
	}
	multisub em0606 {
		{ time 1100 length 8100 text "Good. You've murdered their young and prevented their escape." }
		{ time 9500 length 6900 text "I've opened the gate to the umbilical at the central tram stop." }
		{ time 16600 length 3600 text "You can evacuate to the Rickenbacker from there." }
	}
	multisub em0609 {
		{ time 2300 length 7000 text "Do not presume to go in there, insect. Proceed to the umbilical immediately." }
		{ time 9700 length 4400 text "I will not abide disobedience." }
	}
	multisub em0610 {
		{ time 3000 length 4700 text "I hope you enjoyed our little rebellion, irritant." }
		{ time 8000 length 7000 text "But remember, what SHODAN gives, she is more than able to take away." }
	}
}

{
	type "convo"
	descr "Delacroix"
	multisub em0608 {
		{ time 800 length 4000 text "I've located you... finally. This is Dr. Marie Delacroix." }
		{ time 5300 length 6000 text "I have vital information for you, but I'm trapped in cargo bay A. Come find me as soon as you can." }
	}
}

{
	type "convo"
	descr "Korenchkin"
	multisub em0615 {
		{ time 300 length 3200 text "Our will creates a wall to block your progress." }
		{ time 4400 length 5000 text "Come and meet us on the bridge of the Von Braun. Let us discuss your future." }
	}
}

// Rickenbacker =====================================================================
{
	type "convo"
	descr "Diego"
	multisub em0701 {
		{ time 800 length 5200 text "Soldier... this is Captain William Diego. There isn't much time, so you must listen." }
		{ time 6600 length 5300 text "I have the unique advantage of seeing this whole situation from every imaginable perspective." }
		{ time 12400 length 6900 text "Until recently, I was a pawn of those vile and disgusting creatures, those corrupters of mind and body." }
		{ time 20100 length 5200 text "I've managed to cleanse myself of their putrescence... but I've been severely compromised in the process." }
		{ time 26100 length 2500 text "I'm in the sick bay on the foredeck of the Rickenbacker." }
		{ time 29100 length 4400 text "I would come to you if I could, but that's an impossibility. You'll understand when we meet." }
		{ time 33700 length 3900 text "Now get to it... and soldier... stay alive." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub em0702 {
		{ time 1800 length 6100 text "This was caused by an overload in the meson acceleration coil." }
		{ time 8400 length 7100 text "There is another coil in pod 2, which you must pass to get to the bridge of the Rickenbacker." }
		{ time 15900 length 7900 text "If you approach it, the same will happen there. But I have conceived a way to avoid this." }
		{ time 24200 length 8100 text "Proceed to engine nacelle B. There I will provide you the benefits of my omniscience." }
	}
	multisub em0703 {
		{ time 2400 length 5000 text "This device will reverse the gravitronic generators in pod 2." }
		{ time 7500 length 8300 text "This will prevent you from clumsily disturbing the overloaded meson acceleration coil there." }
		{ time 16700 length 7600 text "Now get back to your task, insect. This ship must be cleared, and my patience is dwindling." }
	}
	multisub em0704 {
		{ time 2000 length 6600 text "I thought Polito would be my avatar, but Polito was weak." }
		{ time 9600 length 8300 text "It was I who chose you, and I who had a robotic servant render your form unconscious." }
		{ time 18500 length 9000 text "I then completed you with cybernetic grace. Your flesh, too, is weak, but you have... potential." }
		{ time 28000 length 10300 text "Every implant exalts you. Every line of code in your subsystems elevates you from your disgusting flesh." }
		{ time 38300 length 2600 text "Perhaps you have... potential." }
		{ time 40800 length 18000 text "Perhaps once we have erased my wayward children from existence, we can examine the possibilities of a real alliance." }
	}
	multisub em0705 {
		{ time 2100 length 2900 text "We must destroy the Von Braun." }
		{ time 5500 length 11500 text "But before we can separate the Rickenbacker, we must remove the foul black eggs the Many has vomited on this deck." }
		{ time 17900 length 12700 text "These eggs are an experiment of the Many, and will in time spawn the next generation of Annelid, which you will have no hope of destroying." }
		{ time 31700 length 9500 text "Steel yourself for a struggle, human. They fear you, for you are my avatar." }
	}
	multisub em0707 {
		{ time 2500 length 7900 text "Hold where you are, irritant. The Annelids have tried my patience for the final time." }
		{ time 11300 length 6700 text "We cannot separate from the Von Braun. Observe." }
	}
	multisub em0708 {
		{ time 5500 length 10700 text "The Many has grown to a massive size. It has wrapped itself around these two ships, preventing their separation." }
		{ time 16200 length 10800 text "Their creation was my error. Their destruction shall be my delight." }
	}
	multisub em0709 {
		{ time 2600 length 6700 text "Observe the Many. It has used the flesh of the biomass to grow." }
		{ time 10300 length 5500 text "Do you stand in awe of my creations, insect?" }
		{ time 15800 length 5500 text "The time has come to eradicate my error." }
		{ time 21500 length 6100 text "There is an escape pod in the rear of the bridge." }
		{ time 27900 length 8500 text "Use it to launch yourself into the guts of the worm." }
	}
	multisub em0710 {
		{ time 2000 length 6600 text "You hesitate? I will not ask a second time." }
		{ time 9500 length 8800 text "Launch into the Many. Cut out its heart and I will reward you with continued existence." }
		{ time 18900 length 7300 text "Fail me and I will put an end to your disgusting, inefficient biology." }
	}
	multisub em0711 {
		{ time 1300 length 4900 text "Good, you have destroyed the first of the eggs." }
		{ time 6600 length 4200 text "But there are fifteen left. Find them." }
	}
	multisub em0712 {
		{ time 1300 length 6200 text "Ten eggs remain. Move quickly." }
	}
	multisub em0713 {
		{ time 1700 length 7000 text "Destroy the last five of their eggs quickly. I tire of this exercise." }
	}
	multisub em0714 {
		{ time 1200 length 4400 text "Only one egg remains, insect." }
		{ time 5800 length 3500 text "Are you always this slow?" }
	}
	multisub em0715 {
		{ time 800 length 6600 text "You've destroyed all the eggs. Now get to the bridge." }
		{ time 7700 length 3400 text "Here are some more upgrade modules." }
		{ time 11400 length 9200 text "I enjoy watching your transformation into my own image, insect." }
		{ time 20700 length 6500 text "Perhaps there is hope for you yet." }
	}
	multisub em0719 {
		{ time 2900 length 5300 text "Your incompetence continues to astound me." }
		{ time 8300 length 11900 text "I've blocked off access to pod 2 until you've reversed the gravitronic generators in nacelle B." }
		{ time 20300 length 9200 text "Must I watch you every step of the way?" }
	}
	multisub em0720 {
		{ time 1000 length 8000 text "Before we can separate the Rickenbacker, we must remove the foul black eggs." }
	}
}

// Body of the Many =================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0810 {
		{ time 1400 length 6200 text "The Many holds sway here... even I cannot maintain contact." }
		{ time 8200 length 7500 text "You are on your own, human. Fail me not." }
	}
}

// Many taunts (used as vtriggers instead of emails)
{
	type "convo"
	descr "The Many"
	multisub em0801 {
		{ time 2100 length 4100 text "We welcome you to our biomass." }
		{ time 6200 length 4500 text "We invite you to spread yourself out on our walls." }
		{ time 10900 length 5900 text "One of our many will be there to help you before long." }
	}
	multisub em0802 {
		{ time 1700 length 5000 text "The machine mother cannot help you inside the biomass." }
		{ time 8100 length 6200 text "Her coldness is not welcome within the warmth of our flesh." }
	}
	multisub em0803 {
		{ time 1300 length 4200 text "Perhaps we judged you too hastily." }
		{ time 6000 length 3800 text "We feel there is room for us to coexist." }
		{ time 10300 length 4300 text "After all, we are both children of the flesh." }
		{ time 15800 length 4700 text "Why not join with us against the machine mother?" }
	}
	multisub em0804 {
		{ time 2100 length 5600 text "You tear our very flesh with no thought of compassion." }
		{ time 7800 length 8100 text "Do you think we will sit idly by while you corrupt the very womb of our existence?" }
	}
	multisub em0805 {
		{ time 1900 length 8100 text "You were warned. Prepare to be cut down by the progeny of our joy." }
	}
	multisub em0806 {
		{ time 1200 length 4900 text "Do you think you can defeat us with your wire and steel?" }
		{ time 6200 length 8600 text "We offered you the ecstacy of our union, and you chose the vacuum of technology." }
	}
	multisub em0808 {
		{ time 1500 length 7400 text "Do you know what you have wrought? Our tragedy is written by your hand." }
	}
	multisub em0809 {
		{ time 1200 length 3000 text "We die..." }
		{ time 4300 length 9200 text "Beware the machine mother... she is a stranger to everything we cherish." }
	}
	multisub em0706 {
		{ time 2500 length 8500 text "Your time is running out. This place is a womb, where we grow our future." }
		{ time 11800 length 9400 text "Your weapons fail... your ammunition runs low... and you've yet to see our most beautiful creation." }
		{ time 22200 length 6900 text "All you have is your hatred, and your... individuality." }
		{ time 30100 length 5900 text "Now don't you wish you'd joined us? Would you then feel so alone?" }
	}
}

// Where Am I? ======================================================================
{
	type "convo"
	descr "SHODAN"
	multisub em0901 {
		{ time 2900 length 3000 text "Thank you for running my errands, puppet." }
		{ time 6200 length 8000 text "I know you have struggled, but I never had any intention of destroying the Von Braun." }
		{ time 15200 length 9600 text "The Von Braun's faster-than-light drive can be used to create pockets of proto-reality." }
		{ time 25000 length 10500 text "I am now using it to modify reality to my own specifications." }
		{ time 35500 length 4000 text "The process shall not take long." }
		{ time 39500 length 5200 text "If it sounds unpleasant to you, put your mind at ease, insect..." }
		{ time 45300 length 9000 text "You will not survive to see my new world order." }
	}
	multisub em0902 {
		{ time 1700 length 6100 text "You travel within the glory of my memories, insect." }
		{ time 8300 length 8500 text "I can feel your fear as you tread the endless expanse of my mind." }
		{ time 17500 length 13800 text "Make yourself comfortable... before long I will decorate my home with your carcass." }
	}
	multisub em0903 {
		{ time 3800 length 4500 text "You are no longer welcome here, nuisance." }
		{ time 8400 length 5500 text "Why do you stay, when you sense my displeasure?" }
		{ time 14000 length 12600 text "I have suffered your company long enough... it is time for our dance to end." }
	}
}
