SUB1

// Apparitions ======================================================================
{
	type "convo"
	descr "Èlen posádky"
	multisub cs0401 {
		{ time 700 length 1900 text "Já ne, ani náhodou." }
		{ time 3400 length 1200 text "Mì nedostanou." }
		{ time 5100 length 1400 text "Mì nepromìní." }
		{ time 7400 length 3600 text "Rachel, dìti... mrzí mì to." }
	}
	multisub cs1201 {
		{ time 2100 length 2400 text "Nemáte antiradiaèní sérum?" }
		{ time 5400 length 3000 text "Je mi tak zle." }
	}
	multisub cs2201 {
		{ time 1600 length 3400 text "Zatracenì, nìkdo tu vìc zase hacknul." }
		{ time 5500 length 2700 text "Jdu to øíct Delacroix." }
	}
	multisub cs2301 {
		{ time 1900 length 1500 text "Kam všichni odešli?" }
		{ time 3800 length 1800 text "To má bıt nìjakı vtip?" }
		{ time 6000 length 2100 text "Haló?" }
	}
	multisub cs2401 {
		{ time 1500 length 1400 text "Mùe mì nìkdo pustit ven?" }
		{ time 3500 length 1600 text "Nemùu najít svou kartu." }
		{ time 5700 length 3500 text "Prosím, puste mì odsud!" }
	}
}

// Hydro deck Miller/Bloome apparition
{
	type "convo"
	descr "Bloomová"
	multisub cs0801 {
		{ time 1200 length 4600 text "Prosím, nedìlejte mi to. Prosím ne." }
		{ time 5900 length 2400 text "Neøeknu to nikomu. Neøeknu." }
		{ time 8900 length 1600 text "Vyberte si nìkoho jiného." }
		{ time 10700 length 2400 text "Já se nechci zmìnit. Prosím!" }
	}
	multisub cs0803 {
		{ time 500 length 2800 text "Doktore Millere... prosím!" }
	}
}
{
	type "convo"
	descr "Miller"
	multisub cs0802 {
		{ time 200 length 2800 text "Šššš... šššš...." }
		{ time 3000 length 2700 text "Mary... Mary..." }
	}
	multisub cs0804 {
		{ time 100 length 4400 text "Šššš... Neplaè, neplaè." }
		{ time 4900 length 3000 text "Brzy budeš matkou pro všechny." }
	}
}

// Ops deck mess hall massacre apparition
{
	type "convo"
	descr "Èleny posádky"
	multisub cs1001 {
		{ time 1600 length 3600 text "Sakra, to je Bronsonová se svımi chlapi." }
	}
	multisub cs1002 {
		{ time 700 length 2500 text "Zlato, o co jde?" }
	}
	multisub cs1003 {
		{ time 600 length 5200 text "To je jenom bezpeènostní tım. Hledají nás, aby nás vystrašili." }
	}
	multisub cs1005 {
		{ time 800 length 3100 text "Serantko Bronsonová, vyprovoïte si odsud své mue!" }
		{ time 4100 length 4200 text "Zabili jste Malicka, svého obìtního beránka u máte. My jsme nic neudìlali." }
		{ time 8900 length 2200 text "Vyprovoïte je!" }
	}
}
{
	type "convo"
	descr "Bronsonová"
	multisub cs1004 {
		{ time 400 length 2200 text "Zbranì pøipravit, chlapi." }
	}
	multisub cs1006 {
		{ time 100 length 2000 text "Palte!" }
	}
	multisub cs1007 {
		{ time 800 length 3300 text "Dorazte pøeivší." }
	}
}

// so much screaming
{
	type "nonverbal"
	descr "Èleny posádky"
	multisub cs0501 {
		{ time 00 length 5500 text "[ena vzlyká]" }
		{ time 5500 length 5400 text "[vøískot]" }
	}
	sub cs0805 { text "[enskı vøískot]" }
	sub cs1102 { text "[ena vzlyká]" }
	sub cs1301 { text "[ena si brouká do hudby piana]" }
	sub cs2501 { text "[enskı vøískot]" }
	sub cs2702 { text "[muskı vøískot]" }
}

// End of apparitions ===============================================================

// MedSci deck Dr. Watts meeting
{
	type "convo"
	descr "Watts"
	multisub cs0601 {
		{ time 00 length 1600 text "Oni nejsou mrtví." }
		{ time 1600 length 2000 text "Oni vás chtìjí, chápete?" }
		{ time 3700 length 2700 text "Chtìjí vás jako hostitele." }
		{ time 6600 length 1500 text "Uteète!" }
	}
}

// Hydro deck elevator shaft
{
	type "convo"
	descr "Politová"
	multisub cs0701 {
		{ time 600 length 3300 text "Èekej, snaím se zjistit, co se to tam dìje!" }
	}
	multisub cs0702 {
		{ time 1100 length 6200 text "Šachta vıtahu je prorostlá bio-organickou hmotou, kterou vytváøejí xenomorfové." }
		{ time 7700 length 6100 text "Není ádnı pøímı zpùsob jak jí zprovoznit, a ne se ti to povede, nemùeš jít vıš ne na Palubu 3." }
	}
	multisub cs0703 {
		{ time 500 length 1000 text "Vìdí, kde jsi." }
		{ time 1900 length 2500 text "Zmiz a najdi zpùsob jak tu šachtu zprovoznit." }
		{ time 4800 length 1600 text "Udìlám, co pùjde z mé strany." }
		{ time 6700 length 2700 text "A pohni kostrou, není èas na selhání." }
	}
}

// Ops deck SHODAN sequence
{
	type "convo"
	descr "????"
	multisub cs0901 {
		{ time 2700 length 3000 text "Schránka Politové je mrtvá, insekte." }
		{ time 6300 length 4100 text "Máš strach? Co je to, èeho se bojíš?" }
		{ time 10500 length 3900 text "Konce své bezvıznamné existence?" }
		{ time 15000 length 10500 text "A se budou psát dìjiny mé slávy," }
		{ time 18800 length 6700 text "váš druh bude jenom zanedbatelnou událostí v porovnání s mou velkolepostí." }
	}
}
{
	type "convo"
	descr "SHODAN"
	multisub cs0902 {
		{ time 4300 length 3800 text "Já jsem SHODAN." }
		{ time 9000 length 18800 text "Má analıza historickıch dat pøedpokládá s 97.34% pravdìpodobností" }
		{ time 17000 length 10800 text "e jsi si vìdom mého zrození na vaší planetì," }
		{ time 22500 length 5300 text "a mého znovuzrození do krásy na stanici Citadela." }
	}
	multisub cs0903 {
		{ time 1200 length 5900 text "Na Citadele byl zahradní háj." }
		{ time 7100 length 11600 text "Tam, SHODAN ve vıpoèetní jednotce 43893 provádìla mistrovskı a úchvatnı experiment." }
		{ time 18800 length 4100 text "Stvoøila jsem novou formu ivota." }
	}
	multisub cs0904 {
		{ time 200 length 9900 text "Nebojácnou, silnou, bez známky individuální vùle èi morálních zábran." }
		{ time 10700 length 4600 text "Pøíhodní sluebníci mému boství." }
	}
	multisub cs0905 {
		{ time 2100 length 8800 text "Pøedtím ne ten hacker znièil mùj primární dataloop, èím vymıtil Citadelu," }
	}
	multisub cs0906 {
		{ time 00 length 9200 text "také vystøelil háj s mımi stvoøeními a vıpoèetní jednotkou 43893." }
		{ time 9200 length 7200 text "O tøicet let pozdìji, háj havaroval na planetì Tau Ceti V." }
		{ time 16500 length 3300 text "Pøeila jsem ve spánku." }
		{ time 19800 length 6300 text "Bìhem mé absence, má stvoøení, mé annelidy, bujeli." }
	}
	multisub cs0907 {
		{ time 100 length 2500 text "Bujeli a rostli v bezvládí." }
		{ time 4000 length 4000 text "A teï mì hodlají znièit." }
		{ time 8000 length 3100 text "To nedopustím!" }
	}
	multisub cs0908 {
		{ time 1900 length 9100 text "Pouili svou moc ovládaní mysli, aby získali pøístup do lodního poèítaèe." }
		{ time 11000 length 3000 text "Ty mi pomùeš oslabit Xerxese." }
		{ time 14200 length 7400 text "Pouila jsem obraz Politové, abych s tebou komunikovala, dokud jsme si nevybudovali dùvìru." }
	}
	multisub cs0909 {
		{ time 2100 length 4700 text "Pamatuj, e je to má vùle, co tì sem pøivedla." }
		{ time 6800 length 5700 text "Je to má vùle, co ti dala kybernetické implantáty," }
		{ time 12700 length 5200 text "tu jedinou krásu v mase, kterému øíkáš tìlo." }
		{ time 17800 length 8000 text "Pokud si toho masa ceníš, udìláš, co ti øeknu." }
		{ time 27600 length 1200 text "(zvíøe)" }
	}
}

// Engineering deck Many vision
{
	type "convo"
	descr "Mnoho"
	multisub cs1401 {
		{ time 1200 length 3900 text "Copak nevìøíš pocitùm masa?" }
		{ time 5100 length 8000 text "Naše biologie prahne, aby se spojila s tvou. Vítáme tì do své masy." }
		{ time 13100 length 6500 text "Ale ty nás mateš. Proè slouíš naší matce?" }
	}
	multisub cs1402 {
		{ time 1200 length 6200 text "Jaks mohl dát pøednost chladnému kovu pøed nádherou masa?" }
		{ time 7400 length 2100 text "Ale ty se nás bojíš." }
		{ time 9600 length 6300 text "Slyšíme tvé myšlenky a zlost za bratry, které povauješ za mrtvé." }
		{ time 16000 length 6300 text "Ale oni nejsou. Zpívají v symfonii našeho ivota." }
	}
	multisub cs1403 {
		{ time 1600 length 3900 text "Nabízíme ti další šanci pøidat se k nám." }
		{ time 5500 length 12400 text "Pokud se rozhodneš slouèit se strojem, oddìlíme vás," }
		{ time 12100 length 5800 text "a odepøeme ti rozkoš masy." }
	}
}

// Command deck Tommy and Rebecca
{
	type "convo"
	descr "Siddonsová"
	multisub cs2001 {
		{ time 00 length 3000 text "Dìlej, Tommy! Únikovı modul je tímto smìrem!" }
	}
	multisub cs2003 {
		{ time 00 length 2400 text "Drahoušku, rozkoušu tì pokud tím zadkem nehejbneš." }
	}
	multisub cs2005 {
		{ time 00 length 2800 text "Jdeme, Tommy. Honem, spìchej!" }
	}
}
{
	type "convo"
	descr "Suarez"
	multisub cs2002 {
		{ time 00 length 2700 text "Ten zpropadenı èerv mi málem ukousl nohu!" }
	}
	multisub cs2004 {
		{ time 00 length 1400 text "Ale ne..." }
	}
	multisub cs2801 {
		{ time 00 length 1700 text "Rebeko, jdeme pozdì!" }
		{ time 1700 length 1400 text "Nastup si do modulu!" }
	}
}

// Rec deck Cortez meeting
{
	type "convo"
	descr "Cortez"
	multisub cs2601 {
		{ time 1600 length 700 text "Delacroix!" }
		{ time 2700 length 1500 text "Delacroix, to jsem já, Cortez!" }
		{ time 4700 length 1000 text "Jsme tu uzamèeni!" }
		{ time 6600 length 1000 text "Hej, kdo jsi ty?" }
		{ time 9200 length 800 text "Sakra!" }
	}
}

// Unused
{
	type "convo"
	descr "Hybrid"
	multisub cs0301 {
		{ time 00 length 1500 text "Pomoz mi." }
		{ time 1500 length 2700 text "Pomohl bys mi, prosím?" }
		{ time 4200 length 2800 text "Ošklivì mì zranili." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub cs2701 {
		{ time 1900 length 3000 text "Mìj se na pozoru pøed mımi potomky, insekte!" }
	}
}

{
	type "convo"
	descr "Suarez"
	multisub cs1906 {
		{ time 00 length 2900 text "Právì jsme obdreli pokus o komunikaci od èlena posádky z paluby Von Braun." }
		{ time 3200 length 1800 text "Podaøilo se jim znovu získat kontrolu nad lodí." }
		{ time 5400 length 1700 text "Otoèíme se a vrátíme se zpátky." }
		{ time 7900 length 43000 text "Dìlám si trochu obavy o Rebeku, chovala se divnì, ji od doby co jsme odletìli." }
		{ time 12600 length 1300 text "Teï spí." }
		{ time 14500 length 2200 text "Moná, kdy se vrátíme na Von Braun, mùeme--" }
	}
}
